### ISSUE TITLE
Compute fbank

### ISSUE THREAD

**Issue by Cirediallo** [k2-fsa/icefall#1030]
Hi,
I'm trying to train on tedlium dataset but during phase 3 I've the error as below
I'm training on TPU with 35GB RAM and 225GB for the hard drive
```
Extracting and storing features (chunks progress):   0% 0/15 [14:14<?, ?it/s]
Traceback (most recent call last):
  File "/content/icefall/egs/tedlium3/ASR/./local/compute_fbank_tedlium.py", line 109, in <module>
    compute_fbank_tedlium()
  File "/content/icefall/egs/tedlium3/ASR/./local/compute_fbank_tedlium.py", line 91, in compute_fbank_tedlium
    cut_set = cut_set.compute_and_store_features(
  File "/usr/local/lib/python3.10/dist-packages/lhotse/cut/set.py", line 2079, in compute_and_store_features
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/usr/local/lib/python3.10/dist-packages/lhotse/manipulation.py", line 30, in combine
    return reduce(add, manifests)
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/lhotse/cut/set.py", line 2079, in <genexpr>
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
@pzelasko said in #249 that I should use `KaldifeatFbank` instead is it the the `FBank` occurrences I've to change in the script or there is another script. 
Thanks.

**Comment by csukuangfj** [comment]
Are there any more logs?

And what is the value of `cur_num_jobs` and how many CPUs does your computer have?
https://github.com/k2-fsa/icefall/blob/61ec3a7a8fc8be859b23a821e568950fb898b37a/egs/tedlium3/ASR/local/compute_fbank_tedlium.py#L89

**Comment by Cirediallo** [comment]
No there is not more logs that all the rest is the keyboard interrupt.
I'm not using CPU but TPU(Google Colab)
`cur_num_jobs` is `15` but I just relaunch the script and it's running. I'll update if it changes

**Comment by csukuangfj** [comment]
I am not sure whether kaldifeat works on TPU or not.

Does it work when you set num_jobs to 1?

**Comment by Cirediallo** [comment]
It seems to work when I set the value to 1. Can you elaborate more what's the purpose of `cur_num_jobs` ?
