### ISSUE TITLE
YESNO recipe assertionError

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/icefall#1064]
I have successfully installed k2, lhotse and other requirements from icefall. When i tried to run the yesno recipe, it came out the following error.

```
2023-05-16 14:10:07 (prepare.sh:27:main) dl_dir: /home/icefall/egs/yesno/ASR/download
2023-05-16 14:10:07 (prepare.sh:30:main) Stage 0: Download data
2023-05-16 14:10:07 (prepare.sh:39:main) Stage 1: Prepare yesno manifest
2023-05-16 14:10:08 (prepare.sh:45:main) Stage 2: Compute fbank for yesno
2023-05-16 14:10:09,653 INFO [compute_fbank_yesno.py:66] train already exists - skipping.
2023-05-16 14:10:09,653 INFO [compute_fbank_yesno.py:66] test already exists - skipping.
2023-05-16 14:10:09 (prepare.sh:51:main) Stage 3: Prepare lang
2023-05-16 14:10:11 (prepare.sh:66:main) Stage 4: Prepare G
2023-05-16 14:10:11 (prepare.sh:92:main) Stage 5: Compile HLG
2023-05-16 14:10:12,216 INFO [compile_hlg.py:128] Processing data/lang_phone
2023-05-16 14:10:12,216 INFO [lexicon.py:168] Loading pre-compiled data/lang_phone/Linv.pt
2023-05-16 14:10:12,217 INFO [compile_hlg.py:52] Building ctc_topo. max_token_id: 3
2023-05-16 14:10:12,218 INFO [compile_hlg.py:56] Loading G.fst.txt
2023-05-16 14:10:12,218 INFO [compile_hlg.py:66] Intersecting L and G
2023-05-16 14:10:12,220 INFO [compile_hlg.py:68] LG shape: (0, None)
2023-05-16 14:10:12,220 INFO [compile_hlg.py:70] Connecting LG
2023-05-16 14:10:12,220 INFO [compile_hlg.py:72] LG shape after k2.connect: (0, None)
2023-05-16 14:10:12,220 INFO [compile_hlg.py:74] <class 'torch.Tensor'>
2023-05-16 14:10:12,220 INFO [compile_hlg.py:75] Determinizing LG
2023-05-16 14:10:12,220 INFO [compile_hlg.py:78] <class 'torch.Tensor'>
2023-05-16 14:10:12,221 INFO [compile_hlg.py:80] Connecting LG after k2.determinize
2023-05-16 14:10:12,221 INFO [compile_hlg.py:83] Removing disambiguation symbols on LG
Traceback (most recent call last):
  File "./local/compile_hlg.py", line 140, in <module>
    main()
  File "./local/compile_hlg.py", line 130, in main
    HLG = compile_HLG(lang_dir)
  File "./local/compile_hlg.py", line 91, in compile_HLG
    assert isinstance(LG.aux_labels, k2.RaggedTensor)
AssertionError
```

**Comment by csukuangfj** [comment]
![Screenshot 2023-05-16 at 14 12 29](https://github.com/k2-fsa/icefall/assets/5284924/9760f5f6-b94b-4c4a-bc51-6b9d33424b7e)


```
ls -lh data/lm
ls -lh data/lang_phone
```

**Comment by PPGGG** [comment]
@csukuangfj Thanks a lot. It finally worked out.

**Comment by csukuangfj** [comment]
> @csukuangfj Thanks a lot. It finally worked out.

How did you fix it? It may be helpful for other users.

**Comment by PPGGG** [comment]
@csukuangfj I just deleted all the data and re-ran `prepare.sh`. I think the problem might be where I run `prepare.sh` with a previous version of k2 and lhotse .
