### ISSUE TITLE
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

### ISSUE THREAD

**Issue by bsshruthi22** [k2-fsa/icefall#1081]
I am training pruned_transducer_stateless7 ASR for my custom dataset (of about 50hrs) using k2. The script has been taken from librispeech and modified to suit my dataset
command used:
    ./pruned_transducer_stateless7/train.py \
  --world-size 1 \
  --full-libri 0 \
  --num-epochs 30 \
  --exp-dir pruned_transducer_stateless7/exp \
  --max-duration 10 \
  --use-fp16 True.
I encounter the error below while running,
2023-05-22 16:25:42,228 INFO [utils.py:1490] Filtering uneven-sized batch, original batch size is 1, retained batch size is 0.
2023-05-22 16:25:42,338 INFO [train.py:1185] Saving batch to pruned_transducer_stateless7/exp/batch-bdd640fb-0667-1ad1-1c80-317fa3b1799d.pt
2023-05-22 16:25:42,339 INFO [train.py:1191] features shape: torch.Size([0, 1964, 80])
2023-05-22 16:25:42,339 INFO [train.py:1195] num tokens: 0
Traceback (most recent call last):
  File "./pruned_transducer_stateless7/train.py", line 1258, in <module>
    main()
  File "./pruned_transducer_stateless7/train.py", line 1251, in main
    run(rank=0, world_size=1, args=args)
  File "./pruned_transducer_stateless7/train.py", line 1106, in run
    scan_pessimistic_batches_for_oom(
  File "./pruned_transducer_stateless7/train.py", line 1215, in scan_pessimistic_batches_for_oom
    loss, _ = compute_loss(
  File "./pruned_transducer_stateless7/train.py", line 681, in compute_loss
    simple_loss, pruned_loss = model(
  File "/home/administrator/anaconda3/envs/k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/administrator/hdd/DeepSpeech/Sishir/icefall/egs/English_ASR/ASR/pruned_transducer_stateless7/model.py", line 117, in forward
    encoder_out, x_lens = self.encoder(x, x_lens)
  File "/home/administrator/anaconda3/envs/k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/administrator/hdd/DeepSpeech/Sishir/icefall/egs/English_ASR/ASR/pruned_transducer_stateless7/zipformer.py", line 283, in forward
    assert x.size(0) == lengths.max().item(), (x.shape, lengths, lengths.max())
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

Kindly let me know.Thanks in advance.

**Comment by bsshruthi22** [comment]
I have successfully run conformer ctc with the same data before.For pruneless transducer, I didnt run prepare.sh again.I used the same manifests and fbank as earlier

**Comment by csukuangfj** [comment]
@bsshruthi22 
Could you try https://github.com/k2-fsa/icefall/pull/1082
