### ISSUE TITLE
Training stuck

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/icefall#1084]
It seems that the training stuck in the wee hours of the morning today. Any suggestion ?

```
2023-05-23 02:56:53,214 INFO [train_tt.py:1100] (0/3) Computing validation loss
2023-05-23 02:56:53,215 INFO [train_tt.py:1075] (2/3) Epoch 1, batch 12000, loss[loss=0.3022, simple_loss=0.3004, pruned_loss=0.152, over 13492.00 frames. ], tot_loss[loss=0.2753, simple_loss=0.2972, pruned_loss=0.1267, over 1979032.42 frames. ], batch size: 49, lr: 3.10e-02,
2023-05-23 02:56:53,215 INFO [train_tt.py:1100] (2/3) Computing validation loss
2023-05-23 02:56:53,217 INFO [train_tt.py:1075] (1/3) Epoch 1, batch 12000, loss[loss=0.5526, simple_loss=0.4628, pruned_loss=0.3212, over 19759.00 frames. ], tot_loss[loss=0.279, simple_loss=0.3001, pruned_loss=0.129, over 2019508.32 frames. ], batch size: 79, lr: 3.10e-02,
2023-05-23 02:56:53,217 INFO [train_tt.py:1100] (1/3) Computing validation loss
2023-05-23 02:57:48,717 INFO [zipformer.py:2441] (0/3) attn_weights_entropy = tensor([1.4177, 2.1075, 1.8620, 2.1185], device='cuda:0'), covar=tensor([0.3002, 0.1221, 0.2248, 0.0611], device='cuda:0'), in_proj_covar=tensor([0.0818, 0.0986, 0.0705, 0.0706], device='cuda:0'), out_proj_covar=tensor([0.0009, 0.0011, 0.0009, 0.0008], device='cuda:0')
```

**Comment by csukuangfj** [comment]
Could you please press
```
ctrl + c
```
and show the output?

**Comment by PPGGG** [comment]
```
^CTraceback (most recent call last):
  File "pruned_transducer_stateless7_streaming/train_tt.py", line 1505, in <module>
    main()
  File "pruned_transducer_stateless7_streaming/train_tt.py", line 1496, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 99, in join
    ready = multiprocessing.connection.wait(
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/anaconda3/envs/k2/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
^CProcess Process-3:2:
Process Process-3:11:
Process Process-3:1:
Traceback (most recent call last):
Error in atexit._run_exitfuncs:
Process Process-1:1:
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
Traceback (most recent call last):
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Process Process-1:2:
    pid, sts = os.waitpid(self.pid, flag)
Process Process-2:2:
KeyboardInterrupt
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f15d63cfee0>
Traceback (most recent call last):
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):         
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
    self._shutdown_workers()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1301, in _shutdown_workers
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt        
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/anaconda3/envs/k2/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
KeyboardInterrupt
  File "/home/anaconda3/envs/k2/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f15d63cfee0>
Traceback (most recent call last):       
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1301, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/home/anaconda3/envs/k2/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/anaconda3/envs/k2/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 151211) is killed by signal: Interrupt. 
```

**Comment by csukuangfj** [comment]
Sorry, I cannot see any thing abnormal from the logs.

**Comment by PPGGG** [comment]
The tensorboard log is below, now i am trying to train the model again.

![Screenshot 2023-05-23 at 11 01 34](https://github.com/k2-fsa/icefall/assets/11624203/613e3ba5-00da-4c06-88cc-fa5b68af71b7)

**Comment by PPGGG** [comment]
@csukuangfj May i ask whether the training status perform normal, based on the information from tensorboard ?

**Comment by csukuangfj** [comment]
Have you shuffled your data by following
https://github.com/k2-fsa/icefall/blob/585e7b224fddeae5a45bef3fc1cf8fb30dcef503/egs/librispeech/ASR/prepare.sh#L130

**Comment by PPGGG** [comment]
> Have you shuffled your data by following
> 
> https://github.com/k2-fsa/icefall/blob/585e7b224fddeae5a45bef3fc1cf8fb30dcef503/egs/librispeech/ASR/prepare.sh#L130

Not yet. Do i need to shuffle the data ?

**Comment by csukuangfj** [comment]
Yes, I recommend doing that. 

After doing that, you won't see an oscillated loss curve.

**Comment by csukuangfj** [comment]
> @csukuangfj May i ask whether the training status perform normal, based on the information from tensorboard ?

Everything seems to be fine as the training loss is going down.

**Comment by PPGGG** [comment]
> > @csukuangfj May i ask whether the training status perform normal, based on the information from tensorboard ?
> 
> Everything seems to be fine as the training loss is going down.

The training stuck again. 

`torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKIL`. 

It's that could be the problem of PyTorch ? The version of PyTorch is `1.10.0`

**Comment by csukuangfj** [comment]
> process 0 terminated with signal SIGKIL.

looks like there is an OOM error.

You can post the output of
```
dmesg | tail -n 100
```

**Comment by PPGGG** [comment]
```
[11169290.470076] Skipping core dump
[11172882.297591] Pid 348658(awk) over core_pipe_limit
[11172882.297594] Skipping core dump
[11172882.305090] Pid 348670(awk) over core_pipe_limit
[11172882.305093] Skipping core dump
[11176473.339486] Pid 299973(awk) over core_pipe_limit
[11176473.339488] Skipping core dump
[11176473.348016] Pid 300245(awk) over core_pipe_limit
[11176473.348018] Skipping core dump
[11179256.214305] Pid 348151(bash) over core_pipe_limit
[11179256.214310] Skipping core dump
[11180038.720374] nr_pdflush_threads exported in /proc is scheduled for removal
[11180065.219213] Pid 15763(awk) over core_pipe_limit
[11180065.219217] Skipping core dump
[11180065.234807] Pid 15776(awk) over core_pipe_limit
[11180065.234812] Skipping core dump
```

**Comment by csukuangfj** [comment]
Did you add `-n 100` to tail?

**Comment by PPGGG** [comment]
```
dmesg | tail -n 100
[11101868.259045] Skipping core dump
[11104643.198804] Pid 243578(awk) over core_pipe_limit
[11104643.198809] Skipping core dump
[11104643.215021] Pid 243587(awk) over core_pipe_limit
[11104643.215025] Skipping core dump
[11108234.155248] Pid 345917(awk) over core_pipe_limit
[11108234.155253] Skipping core dump
[11108234.171350] Pid 345926(awk) over core_pipe_limit
[11108234.171354] Skipping core dump
[11111825.473752] Pid 118237(awk) over core_pipe_limit
[11111825.473757] Skipping core dump
[11111825.486921] Pid 118246(awk) over core_pipe_limit
[11111825.486926] Skipping core dump
[11115417.435994] Pid 255010(awk) over core_pipe_limit
[11115417.435998] Skipping core dump
[11115417.453704] Pid 255019(awk) over core_pipe_limit
[11115417.453710] Skipping core dump
[11119009.448146] Pid 348552(awk) over core_pipe_limit
[11119009.448151] Skipping core dump
[11119009.465651] Pid 348561(awk) over core_pipe_limit
[11119009.465656] Skipping core dump
[11122600.314934] Pid 78041(awk) over core_pipe_limit
[11122600.314939] Skipping core dump
[11122600.333114] Pid 78050(awk) over core_pipe_limit
[11122600.333119] Skipping core dump
[11126192.264312] Pid 164889(awk) over core_pipe_limit
[11126192.264317] Skipping core dump
[11126192.281883] Pid 164898(awk) over core_pipe_limit
[11126192.281886] Skipping core dump
[11129783.498279] Pid 253428(awk) over core_pipe_limit
[11129783.498284] Skipping core dump
[11129783.523996] Pid 253440(awk) over core_pipe_limit
[11129783.524000] Skipping core dump
[11133375.072514] Pid 340125(awk) over core_pipe_limit
[11133375.072519] Skipping core dump
[11133375.092462] Pid 340137(awk) over core_pipe_limit
[11133375.092467] Skipping core dump
[11136967.074484] Pid 70799(awk) over core_pipe_limit
[11136967.074490] Skipping core dump
[11136967.099136] Pid 70812(awk) over core_pipe_limit
[11136967.099141] Skipping core dump
[11140558.150500] Pid 157592(awk) over core_pipe_limit
[11140558.150505] Skipping core dump
[11140558.174614] Pid 157605(awk) over core_pipe_limit
[11140558.174618] Skipping core dump
[11142892.694331] Pid 214349(awk) over core_pipe_limit
[11142892.694336] Skipping core dump
[11142893.106180] Pid 214387(awk) over core_pipe_limit
[11142893.106185] Skipping core dump
[11142893.142903] Pid 214394(awk) over core_pipe_limit
[11142893.142907] Skipping core dump
[11142893.172105] Pid 214405(awk) over core_pipe_limit
[11142893.172109] Skipping core dump
[11144150.157660] Pid 244399(awk) over core_pipe_limit
[11144150.157665] Skipping core dump
[11144150.174787] Pid 244408(awk) over core_pipe_limit
[11144150.174791] Skipping core dump
[11147741.126442] Pid 330610(awk) over core_pipe_limit
[11147741.126446] Skipping core dump
[11147741.144128] Pid 330619(awk) over core_pipe_limit
[11147741.144133] Skipping core dump
[11151332.503370] Pid 60638(awk) over core_pipe_limit
[11151332.503375] Skipping core dump
[11151332.519518] Pid 60647(awk) over core_pipe_limit
[11151332.519522] Skipping core dump
[11154924.194066] Pid 146381(awk) over core_pipe_limit
[11154924.194072] Skipping core dump
[11154924.210783] Pid 146391(awk) over core_pipe_limit
[11154924.210787] Skipping core dump
[11158516.494327] Pid 233548(awk) over core_pipe_limit
[11158516.494329] Skipping core dump
[11158516.512570] Pid 233557(awk) over core_pipe_limit
[11158516.512575] Skipping core dump
[11162107.479786] Pid 327182(awk) over core_pipe_limit
[11162107.479790] Skipping core dump
[11162107.495822] Pid 327191(awk) over core_pipe_limit
[11162107.495826] Skipping core dump
[11165698.592077] Pid 55539(awk) over core_pipe_limit
[11165698.592082] Skipping core dump
[11165698.609907] Pid 55548(awk) over core_pipe_limit
[11165698.609911] Skipping core dump
[11169290.462111] Pid 299344(awk) over core_pipe_limit
[11169290.462113] Skipping core dump
[11169290.470074] Pid 299368(awk) over core_pipe_limit
[11169290.470076] Skipping core dump
[11172882.297591] Pid 348658(awk) over core_pipe_limit
[11172882.297594] Skipping core dump
[11172882.305090] Pid 348670(awk) over core_pipe_limit
[11172882.305093] Skipping core dump
[11176473.339486] Pid 299973(awk) over core_pipe_limit
[11176473.339488] Skipping core dump
[11176473.348016] Pid 300245(awk) over core_pipe_limit
[11176473.348018] Skipping core dump
[11179256.214305] Pid 348151(bash) over core_pipe_limit
[11179256.214310] Skipping core dump
[11180038.720374] nr_pdflush_threads exported in /proc is scheduled for removal
[11180065.219213] Pid 15763(awk) over core_pipe_limit
[11180065.219217] Skipping core dump
[11180065.234807] Pid 15776(awk) over core_pipe_limit
[11180065.234812] Skipping core dump
```

**Comment by csukuangfj** [comment]
Can you look at the dmesg output locally and see if there are `oom` (out of memory) logs ?

**Comment by PPGGG** [comment]
> Can you look at the dmesg output locally and see if there are `oom` (out of memory) logs ?

The memory of my server should be enough i guess, which is 512G. I just to try to improve the process limit of my server, and see whether if the training works properly.

**Comment by uni-saurabh-vyas** [comment]
I am facing similar issue, with DDP training gets stuck, what was the solution ?

**Comment by danpovey** [comment]
I suspect there is some confusion about the number of batches in the validation data - i.e. it's different between worker threads - and this causes an error while shutting down the validation data loaders.
I wonder whether you might have made any code changes that would affect the valid dataloaders?
Making sure your lhotse is up to date is probably a good idea regardless.

**Comment by danpovey** [comment]
Also it's relevant what the validation data loader is in asr_datamodule.py (may depend whether args.on_the_fly_feats is true or false), and what the options etc. were (first line of the training log, options and code versions should be printed.)

**Comment by uni-saurabh-vyas** [comment]
Commenting here, if its useful for someone

The error was caused due to SIGKILL, the reason, as one of our team members found was due to issue in data itself(alignment issues like audio and transcript mismatch).
 
It checks Whether number of frames of utterance is greater than number of BPE units of that utterance, so if it is not greater than no. of frames is not greater than no. of BPE units then it will throw some assertion error.
