### ISSUE TITLE
TypeError: load(): incompatible function arguments.

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/icefall#1098]
I just git clone the latest icefall code and followed the document https://icefall.readthedocs.io/en/latest/model-export/export-ncnn-zipformer.html, trying to decode the audio using the exported model, still get the same error:

```
python pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py \
>   --tokens ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/data/lang_bpe_500/tokens.txt \
>   --encoder-param-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.param \
>   --encoder-bin-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.bin \
>   --decoder-param-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.param \
>   --decoder-bin-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.bin \
>   --joiner-param-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.param \
>   --joiner-bin-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.bin \
>   ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/test_wavs/1089-134686-0001.wav
2023-05-25 22:48:47,713 INFO [streaming-ncnn-decode.py:376] {'tokens': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/data/lang_bpe_500/tokens.txt', 'encoder_param_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.param', 'encoder_bin_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.bin', 'decoder_param_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.param', 'decoder_bin_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.bin', 'joiner_param_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.param', 'joiner_bin_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.bin', 'sound_filename': './icefall-asr-liTraceback (most recent call last):ess7-streaming-2022-12-29/test_wavs/1089-134686-0001.wav'}
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 446, in <module>
    main()
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 378, in main
    model = Model(args)
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 109, in __init__
    self.init_encoder(args)
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 210, in init_encoder
    encoder_net.load_model(encoder_model)
  File "/home/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/ncnn_custom_layer.py", line 223, in load_model
    bias = md.load(self.num_channels, self.upsample, 0)
TypeError: load(): incompatible function arguments. The following argument types are supported:
    1. (self: ncnn.ncnn.ModelBinFromDataReader, w: int, type: int) -> ncnn::Mat

Invoked with: <ncnn.ncnn.ModelBinFromDataReader object at 0x7efe9d4fb470>, 384, 2, 0
```

**Comment by csukuangfj** [comment]
>  followed the document https://icefall.readthedocs.io/en/latest/model-export/export-ncnn-zipformer.html

Did you really follow the above documentation to install ncnn?
That is, did you use
https://github.com/csukuangfj/ncnn


Please show the output of `git log` of your ncnn repository.

**Comment by csukuangfj** [comment]
@PPGGG 

Please check that you are indeed strictly following the documentation and you are not using
https://github.com/tencent/ncnn/

**Comment by PPGGG** [comment]
Thanks @csukuangfj . I clone your https://github.com/csukuangfj/ncnn again and install ncnn. Then i got rid of the previous problems. And i have successfully ran the document example. Thanks a lot!

```
2023-05-26 11:27:51,044 INFO [streaming-ncnn-decode.py:384] Constructing Fbank computer
2023-05-26 11:27:51,045 INFO [streaming-ncnn-decode.py:387] Reading sound files: ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/test_wavs/1089-134686-0001.wav
2023-05-26 11:27:51,049 INFO [streaming-ncnn-decode.py:392] torch.Size([106000])
2023-05-26 11:27:51,059 INFO [streaming-ncnn-decode.py:399] number of states: 35
2023-05-26 11:27:53,250 INFO [streaming-ncnn-decode.py:437] ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/test_wavs/1089-134686-0001.wav
2023-05-26 11:27:53,251 INFO [streaming-ncnn-decode.py:438] AFTER EARLY NIGHTFALL THE YELLOW LAMPS WOULD LIGHT UP HERE AND THERE THE SQUALID QUARTER OF THE BROTHELS
```

 However, when i tried to export my own Chinese model, i met the following problem :
 
```
 2023-05-26 11:29:44,705 INFO [streaming-ncnn-decode.py:384] Constructing Fbank computer
2023-05-26 11:29:44,706 INFO [streaming-ncnn-decode.py:387] Reading sound files: /home/data/aishell/data_aishell/wav/test/S0764/BAC009S0764W0122.wav
2023-05-26 11:29:44,707 INFO [streaming-ncnn-decode.py:392] torch.Size([65840])
2023-05-26 11:29:44,715 INFO [streaming-ncnn-decode.py:399] number of states: 35
Traceback (most recent call last):
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 446, in <module>
    main()
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 426, in main
    encoder_out, states = model.run_encoder(frames, states)
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 260, in run_encoder
    ret, ncnn_out0 = ex.extract("out0")
  File "/home/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/ncnn_custom_layer.py", line 116, in forward
    x = x + cached_len * cached_avg[0]
ValueError: operands could not be broadcast together with shapes (16,160) (1,384)
```

**Comment by PPGGG** [comment]
@csukuangfj I want to cry. Finally i got the correct answer. Really appreciate your kindness and patience !
