### ISSUE TITLE
how to train the hlg？

### ISSUE THREAD

**Issue by boshs** [k2-fsa/icefall#1143]
is there a recipe of training hlg on aishell？

**Comment by marcoyang1998** [comment]
Please have a look at [here](https://github.com/k2-fsa/icefall/blob/d667dc365b3259179c9d54bd32a1bb2bd8afa4f0/egs/aishell/ASR/prepare.sh#L237) to see how a G is created.

After having the G, you can compose it with L and H to construct HLG. This step is described [here](https://github.com/k2-fsa/icefall/blob/d667dc365b3259179c9d54bd32a1bb2bd8afa4f0/egs/aishell/ASR/prepare.sh#L262)

**Comment by boshs** [comment]
thanks! 
but when stage 9 ,appeared the following：
2023-06-21 19:35:49,288 INFO [compile_hlg.py:122] LG shape after k2.remove_epsilon: (2842839, None)
Traceback (most recent call last):
  File "./local/compile_hlg.py", line 167, in <module>
    main()
  File "./local/compile_hlg.py", line 157, in main
    HLG = compile_HLG(lang_dir, args.lm)
  File "./local/compile_hlg.py", line 124, in compile_HLG
    LG = k2.connect(LG)
  File "/home/shiyanshi/anaconda3/envs/k2/lib/python3.8/site-packages/k2/fsa_algo.py", line 522, in connect
    if fsa.properties & fsa_properties.ACCESSIBLE != 0 and \
  File "/home/shiyanshi/anaconda3/envs/k2/lib/python3.8/site-packages/k2/fsa.py", line 446, in properties
    raise RuntimeError(
RuntimeError: The fsa attribute (labels) has been inappropriately modified like:
    fsa.labels[xxx] = yyy
The correct way should be like:
    labels = fsa.labels
    labels[xxx] = yyy
    fsa.labels = labels

**Comment by wangtiance** [comment]
@boshs It looks the same as https://github.com/k2-fsa/icefall/pull/1039. Updating your k2 version may solve it.

**Comment by kli017** [comment]
conda search -c k2-fsa k2 cannot find a version of 1.24.3

**Comment by pkufool** [comment]
> conda search -c k2-fsa k2 cannot find a version of 1.24.3

You can find pre-built wheels here https://huggingface.co/csukuangfj/k2/blob/main/cuda.md
