### ISSUE TITLE
Zipformer Model Training Error

### ISSUE THREAD

**Issue by saurabhbarge** [k2-fsa/icefall#1163]
We are trying to train the zipformer model on our own data using the Librispeech recipe, the model trains without any error for a small subset of data, but after giving more data to the model for training we are encountering this error,

```
Traceback (most recent call last):
  File "/home/ubuntu/STT/icefall/egs/sb/s5/./zipformer/train.py", line 1337, in <module>
    main()
  File "/home/ubuntu/STT/icefall/egs/sb/s5/./zipformer/train.py", line 1330, in main
    run(rank=0, world_size=1, args=args)
  File "/home/ubuntu/STT/icefall/egs/sb/s5/./zipformer/train.py", line 1208, in run
    train_one_epoch( 
  File "/home/ubuntu/STT/icefall/egs/sb/s5/./zipformer/train.py", line 1013, in train_one_epoc
    valid_info = compute_validation_loss(
  File "/home/ubuntu/STT/icefall/egs/sb/s5/./zipformer/train.py", line 813, in compute_validation_loss
    loss, loss_info = compute_loss( 
  File "/home/ubuntu/STT/icefall/egs/sb/s5/./zipformer/train.py", line 760, in compute_loss 
    simple_loss, pruned_loss = model(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/STT/icefall/egs/sb/s5/zipformer/model.py", line 136, in forward
    assert torch.all(x_lens > 0)
AssertionError

```
can someone please help me resolving this

Thanks in Advance

**Comment by marcoyang1998** [comment]
It looks like one of your input data has zero length. Could you please check you experiment directory and see if any data is stored? The script should automatically save the batch that is causing the training to crash. Then, could you print out the shape of `x` when throwing out this error?

**Comment by desh2608** [comment]
It seems the error happens in `compute_validation_loss`. This could just be because you haven't applied the filter to `remove_long_and_short` cuts on the validation set.

**Comment by saurabhbarge** [comment]
Applying the filter to the validation set worked and the model started training without any errors. Thank you all.
