### ISSUE TITLE
Decoding using pruned_transducer_stateless7_streaming/decode.py  failing with pretrained librispeech models

### ISSUE THREAD

**Issue by uni-manjunath-ke** [k2-fsa/icefall#1210]
I downloaded pretrained librispeech models from https://huggingface.co/Zengwei/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/tree/main and using them for decoding through pruned_transducer_stateless7_streaming/decode.py  script.

This fails giving assertion error. Please suggest. If I use the same models with ./pruned_transducer_stateless7_streaming/streamingdecode.py, the decoding happens.
stack trace:

./pruned_transducer_stateless7_streaming/decode.py --epoch 30 --avg 1 --exp-dir /mnt/efs/manju/if/repos/streaming_asr/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp --max-duration 600        --decode-chunk-len 64 --decoding-method greedy_search --bpe-model /mnt/efs/manju/if/repos/streaming_asr/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/data/lang_bpe_500/bpe.model --use-averaged-model False --manifest-dir /mnt/efs/manju/if/repos/ds-e2e-asr-testing/scripts

2023-08-10 07:37:56,013 INFO [decode.py:779] Decoding started
2023-08-10 07:37:56,014 INFO [decode.py:785] Device: cuda:0
2023-08-10 07:37:56,023 INFO [decode.py:795] {'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 50, 'reset_interval': 200, 'valid_interval': 3000, 'feature_dim': 80, 'subsampling_factor': 4, 'warm_step': 2000, 'env_info': {'k2-version': '1.23.4', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': '62e404dd3f3a811d73e424199b3408e309c06e1a', 'k2-git-date': 'Mon Jan 30 02:26:16 2023', 'lhotse-version': '1.13.0.dev+git.c1a1268.clean', 'torch-version': '1.13.1', 'torch-cuda-available': True, 'torch-cuda-version': '11.6', 'python-version': '3.9', 'icefall-git-branch': 'master', 'icefall-git-sha1': '00256a7-clean', 'icefall-git-date': 'Wed Aug 9 01:40:58 2023', 'icefall-path': '/mnt/efs/manju/if/repos/streaming_asr/ds-icefall', 'k2-path': '/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2/__init__.py', 'lhotse-path': '/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/lhotse/__init__.py', 'hostname': 'ip-10-40-6-153', 'IP address': '127.0.0.1'}, 'epoch': 30, 'iter': 0, 'avg': 1, 'use_averaged_model': False, 'exp_dir': PosixPath('/mnt/efs/manju/if/repos/streaming_asr/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp'), 'bpe_model': '/mnt/efs/manju/if/repos/streaming_asr/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/data/lang_bpe_500/bpe.model', 'lang_dir': PosixPath('data/lang_bpe_500'), 'decoding_method': 'greedy_search', 'beam_size': 4, 'beam': 20.0, 'ngram_lm_scale': 0.01, 'max_contexts': 8, 'max_states': 64, 'context_size': 2, 'max_sym_per_frame': 1, 'num_paths': 200, 'nbest_scale': 0.5, 'use_shallow_fusion': False, 'lm_type': 'rnn', 'lm_scale': 0.3, 'tokens_ngram': 2, 'backoff_id': 500, 'num_encoder_layers': '2,4,3,2,4', 'feedforward_dims': '1024,1024,2048,2048,1024', 'nhead': '8,8,8,8,8', 'encoder_dims': '384,384,384,384,384', 'attention_dims': '192,192,192,192,192', 'encoder_unmasked_dims': '256,256,256,256,256', 'zipformer_downsampling_factors': '1,2,4,8,2', 'cnn_module_kernels': '31,31,31,31,31', 'decoder_dim': 512, 'joiner_dim': 512, 'short_chunk_size': 50, 'num_left_chunks': 4, 'decode_chunk_len': 64, 'full_libri': True, 'mini_libri': False, 'manifest_dir': PosixPath('/mnt/efs/manju/if/repos/ds-e2e-asr-testing/scripts'), 'max_duration': 600, 'bucketing_sampler': True, 'num_buckets': 30, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'shuffle': True, 'drop_last': True, 'return_cuts': True, 'num_workers': 2, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': True, 'input_strategy': 'PrecomputedFeatures', 'lm_vocab_size': 500, 'lm_epoch': 7, 'lm_avg': 1, 'lm_exp_dir': None, 'rnn_lm_embedding_dim': 2048, 'rnn_lm_hidden_dim': 2048, 'rnn_lm_num_layers': 3, 'rnn_lm_tie_weights': True, 'transformer_lm_exp_dir': None, 'transformer_lm_dim_feedforward': 2048, 'transformer_lm_encoder_dim': 768, 'transformer_lm_embedding_dim': 768, 'transformer_lm_nhead': 8, 'transformer_lm_num_layers': 16, 'transformer_lm_tie_weights': True, 'res_dir': PosixPath('/mnt/efs/manju/if/repos/streaming_asr/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/greedy_search'), 'suffix': 'epoch-30-avg-1-streaming-chunk-size-64-context-2-max-sym-per-frame-1', 'blank_id': 0, 'unk_id': 2, 'vocab_size': 500}
2023-08-10 07:37:56,023 INFO [decode.py:797] About to create model
2023-08-10 07:37:57,012 INFO [zipformer.py:405] At encoder stack 4, which has downsampling_factor=2, we will combine the outputs of layers 1 and 3, with downsampling_factors=2 and 8.
2023-08-10 07:37:57,025 INFO [checkpoint.py:112] Loading checkpoint from /mnt/efs/manju/if/repos/streaming_asr/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/epoch-30.pt
2023-08-10 07:38:00,995 INFO [decode.py:950] Number of model parameters: 70369391
2023-08-10 07:38:00,995 INFO [asr_datamodule.py:465] About to get test-clean cuts
2023-08-10 07:38:01,007 INFO [asr_datamodule.py:472] About to get test-other cuts
Traceback (most recent call last):
  File "/mnt/efs/manju/if/repos/streaming_asr/ds-icefall/egs/librispeech/ASR/./pruned_transducer_stateless7_streaming/decode.py", line 991, in <module>
    main()
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/efs/manju/if/repos/streaming_asr/ds-icefall/egs/librispeech/ASR/./pruned_transducer_stateless7_streaming/decode.py", line 968, in main
    results_dict = decode_dataset(
  File "/mnt/efs/manju/if/repos/streaming_asr/ds-icefall/egs/librispeech/ASR/./pruned_transducer_stateless7_streaming/decode.py", line 647, in decode_dataset
    for batch_idx, batch in enumerate(dl):
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 60, in fetch
    data = self.dataset[possibly_batched_index]
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/lhotse/dataset/speech_recognition.py", line 113, in __getitem__
    input_tpl = self.input_strategy(cuts)
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/lhotse/dataset/input_strategies.py", line 120, in __call__
    return collate_features(
  File "/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/lhotse/dataset/collation.py", line 129, in collate_features
    assert all(cut.has_features for cut in cuts)
AssertionError

**Comment by desh2608** [comment]
This is because `streaming_decode.py` computes the Fbank features on-the-fly during decoding, whereas `decode.py` expects pre-computed features. You need to either compute features beforehand, or specify `--on-the-fly-feats true` as an extra argument.

**Comment by uni-manjunath-ke** [comment]
Sure, Thanks. that works
