### ISSUE TITLE
error in replicating the work - "decoding with language models"

### ISSUE THREAD

**Issue by laishramrahul** [k2-fsa/icefall#1228]
Hi all, I am following the example given in this link https://k2-fsa.github.io/icefall/decoding-with-langugage-models/shallow-fusion.html. However, I am getting the following error, please help 

./pruned_transducer_stateless7_streaming/decode.py     --epoch 99     --avg 1     --use-averaged-model False     --exp-dir $exp_dir     --bpe-model ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/data/lang_bpe_500/bpe.model     --max-duration 600     --decode-chunk-len 32     --decoding-method modified_beam_search
2023-08-29 12:18:45,013 INFO [decode.py:779] Decoding started
2023-08-29 12:18:45,013 INFO [decode.py:785] Device: cuda:0
Traceback (most recent call last):
  File "/home/laishram/workspace/k2/icefall/egs/librispeech/ASR/./pruned_transducer_stateless7_streaming/decode.py", line 991, in <module>
    main()
  File "/home/laishram/workspace/k2/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laishram/workspace/k2/icefall/egs/librispeech/ASR/./pruned_transducer_stateless7_streaming/decode.py", line 788, in main
    sp.load(params.bpe_model)
  File "/home/laishram/workspace/k2/venv/lib/python3.11/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laishram/workspace/k2/venv/lib/python3.11/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by csukuangfj** [comment]
Please show the filesize of your bpe.model
```
ls -lh bpe.model
```

**Comment by marcoyang1998** [comment]
Thanks for pointing it out, will fix this.

**Comment by marcoyang1998** [comment]
The fix is merged #1229
