### ISSUE TITLE
matrix_ac = torch.matmul(q_with_bias_u, k) 

### ISSUE THREAD

**Issue by cxt520ppgsh** [k2-fsa/icefall#1237]
你好，我在使用docker训练tal_csasr时报了这个Error，可以帮忙看看是什么问题吗

我只有一张3070

root@2bfc66ac4734:/workspace/icefall/egs/tal_csasr/ASR# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0

root@2bfc66ac4734:/workspace/icefall/egs/tal_csasr/ASR# ./pruned_transducer_stateless5/train.py --world-size 1

root@2bfc66ac4734:/workspace/icefall/egs/tal_csasr/ASR# ./ pruned_transducer_stateless5/train.py --world-size 1
bash: ./: Is a directory
root@2bfc66ac4734:/workspace/icefall/egs/tal_csasr/ASR# ./pruned_transducer_stateless5/train.py --world-size 1
2023-09-01 06:12:29,205 INFO [train.py:849] Training started
2023-09-01 06:12:29,207 INFO [train.py:859] Device: cuda:0
2023-09-01 06:12:29,291 INFO [lexicon.py:168] Loading pre-compiled data/lang_char/Linv.pt
2023-09-01 06:12:29,316 INFO [train.py:876] {'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 50, 'reset_interval': 100, 'valid_interval': 2000, 'feature_dim': 80, 'subsampling_factor': 4, 'model_warm_step': 1000, 'env_info': {'k2-version': '1.24.3', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': '4c05309499a08454997adf500b56dcc629e35ae5', 'k2-git-date': 'Tue Jul 25 16:23:36 2023', 'lhotse-version': '1.16.0.dev+git.7640d663.clean', 'torch-version': '1.13.0', 'torch-cuda-available': True, 'torch-cuda-version': '11.6', 'python-version': '3.9', 'icefall-git-branch': 'master', 'icefall-git-sha1': '636a584-clean', 'icefall-git-date': 'Tue Aug 29 12:34:23 2023', 'icefall-path': '/workspace/icefall', 'k2-path': '/opt/conda/lib/python3.9/site-packages/k2/__init__.py', 'lhotse-path': '/opt/conda/lib/python3.9/site-packages/lhotse/__init__.py', 'hostname': '2bfc66ac4734', 'IP address': '172.17.0.2'}, 'world_size': 1, 'master_port': 12354, 'tensorboard': True, 'num_epochs': 30, 'start_epoch': 1, 'start_batch': 0, 'exp_dir': PosixPath('pruned_transducer_stateless5/exp'), 'lang_dir': 'data/lang_char', 'initial_lr': 0.003, 'lr_batches': 5000, 'lr_epochs': 6, 'context_size': 2, 'prune_range': 5, 'lm_scale': 0.25, 'am_scale': 0.0, 'simple_loss_scale': 0.5, 'seed': 42, 'print_diagnostics': False, 'save_every_n': 4000, 'keep_last_k': 30, 'average_period': 100, 'use_fp16': False, 'num_encoder_layers': 24, 'dim_feedforward': 1536, 'nhead': 8, 'encoder_dim': 384, 'decoder_dim': 512, 'joiner_dim': 512, 'manifest_dir': PosixPath('data/fbank'), 'max_duration': 200.0, 'bucketing_sampler': True, 'num_buckets': 300, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'shuffle': True, 'drop_last': True, 'return_cuts': True, 'num_workers': 2, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': True, 'input_strategy': 'PrecomputedFeatures', 'blank_id': 0, 'vocab_size': 4155}
2023-09-01 06:12:29,317 INFO [train.py:878] About to create model
2023-09-01 06:12:29,684 INFO [train.py:882] Number of model parameters: 94829765
2023-09-01 06:12:32,387 INFO [asr_datamodule.py:407] About to get train cuts
2023-09-01 06:12:32,389 INFO [asr_datamodule.py:224] About to get Musan cuts
2023-09-01 06:12:34,312 INFO [asr_datamodule.py:229] Enable MUSAN
2023-09-01 06:12:34,312 INFO [asr_datamodule.py:252] Enable SpecAugment
2023-09-01 06:12:34,313 INFO [asr_datamodule.py:253] Time warp factor: 80
2023-09-01 06:12:34,313 INFO [asr_datamodule.py:263] Num frame mask: 10
2023-09-01 06:12:34,313 INFO [asr_datamodule.py:276] About to create train dataset
2023-09-01 06:12:34,313 INFO [asr_datamodule.py:303] Using DynamicBucketingSampler.
2023-09-01 06:12:39,317 INFO [asr_datamodule.py:320] About to create train dataloader
2023-09-01 06:12:39,318 INFO [asr_datamodule.py:414] About to get dev cuts
2023-09-01 06:12:39,322 INFO [asr_datamodule.py:351] About to create dev dataset
2023-09-01 06:12:39,821 INFO [asr_datamodule.py:370] About to create dev dataloader
Traceback (most recent call last):
  File "/workspace/icefall/egs/tal_csasr/ASR/./pruned_transducer_stateless5/train.py", line 1086, in <module>
    main()
  File "/workspace/icefall/egs/tal_csasr/ASR/./pruned_transducer_stateless5/train.py", line 1079, in main
    run(rank=0, world_size=1, args=args)
  File "/workspace/icefall/egs/tal_csasr/ASR/./pruned_transducer_stateless5/train.py", line 987, in run
    train_one_epoch(
  File "/workspace/icefall/egs/tal_csasr/ASR/./pruned_transducer_stateless5/train.py", line 732, in train_one_epoch
    loss, loss_info = compute_loss(
  File "/workspace/icefall/egs/tal_csasr/ASR/./pruned_transducer_stateless5/train.py", line 611, in compute_loss
    simple_loss, pruned_loss = model(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/icefall/egs/tal_csasr/ASR/pruned_transducer_stateless5/model.py", line 132, in forward
    encoder_out, x_lens = self.encoder(x, x_lens, warmup=warmup)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/icefall/egs/tal_csasr/ASR/pruned_transducer_stateless5/conformer.py", line 191, in forward
    x = self.encoder(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/icefall/egs/tal_csasr/ASR/pruned_transducer_stateless5/conformer.py", line 697, in forward
    output = mod(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/icefall/egs/tal_csasr/ASR/pruned_transducer_stateless5/conformer.py", line 512, in forward
    src_att = self.self_attn(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/icefall/egs/tal_csasr/ASR/pruned_transducer_stateless5/conformer.py", line 975, in forward
    return self.multi_head_attention_forward(
  File "/workspace/icefall/egs/tal_csasr/ASR/pruned_transducer_stateless5/conformer.py", line 1245, in multi_head_attention_forward
    matrix_ac = torch.matmul(q_with_bias_u, k)  # (batch, head, time1, time2)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by wangtiance** [comment]
可能和显存不够有关，你试试max-duration=100

**Comment by wangtiance** [comment]
File "/workspace/icefall/egs/tal_csasr/ASR/pruned_transducer_stateless5/conformer.py", line 1245, in multi_head_attention_forward
matrix_ac = torch.matmul(q_with_bias_u, k) # (batch, head, time1, time2)
