### ISSUE TITLE
mismatch error while decoding

### ISSUE THREAD

**Issue by SSwethaSel0609** [k2-fsa/icefall#1289]
2023-10-03 14:09:50,632 INFO [decode.py:917] Calculating the averaged model over epoch range from 10 (excluded) to 20
Traceback (most recent call last):
  File "./pruned_transducer_stateless7/decode.py", line 1015, in <module>
    main()
  File "/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./pruned_transducer_stateless7/decode.py", line 922, in main
    model.load_state_dict(
  File "/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Transducer:
        size mismatch for decoder.embedding.weight: copying a param with shape torch.Size([500, 512]) from checkpoint, the shape in current model is torch.Size([250, 512]).
        size mismatch for joiner.output_linear.weight: copying a param with shape torch.Size([500, 512]) from checkpoint, the shape in current model is torch.Size([250, 512]).
        size mismatch for joiner.output_linear.bias: copying a param with shape torch.Size([500]) from checkpoint, the shape in current model is torch.Size([250]).
        size mismatch for simple_am_proj.weight: copying a param with shape torch.Size([500, 384]) from checkpoint, the shape in current model is torch.Size([250, 384]).
        size mismatch for simple_am_proj.bias: copying a param with shape torch.Size([500]) from checkpoint, the shape in current model is torch.Size([250]).
        size mismatch for simple_lm_proj.weight: copying a param with shape torch.Size([500, 512]) from checkpoint, the shape in current model is torch.Size([250, 512]).
        size mismatch for simple_lm_proj.bias: copying a param with shape torch.Size([500]) from checkpoint, the shape in current model is torch.Size([250]).

**Comment by csukuangfj** [comment]
This happens because you use a different set of model arguments for train.py and decode.py.

Please compare the first line of the log for train.py and decode.py and you should be able to identify the differences by yourself.
If you cannot, please post the logs of train.py and decode.py here and we can do that for you.

**Comment by SSwethaSel0609** [comment]
below is my decode log 
2023-10-03 15:04:47,884 INFO [decode.py:848] {'frame_shift_ms': 10.0, 'allowed_excess_duration_ratio': 0.1, 'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 50, 'reset_interval': 200, 'valid_interval': 3000, 'feature_dim': 80, 'subsampling_factor': 4, 'warm_step': 2000, 'env_info': {'k2-version': '1.24.3', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': '4c05309499a08454997adf500b56dcc629e35ae5', 'k2-git-date': 'Tue Jul 25 16:23:36 2023', 'lhotse-version': '1.17.0.dev+git.b138bafb.clean', 'torch-version': '1.13.0+cu116', 'torch-cuda-available': True, 'torch-cuda-version': '11.6', 'python-version': '3.8', 'icefall-git-branch': None, 'icefall-git-sha1': None, 'icefall-git-date': None, 'icefall-path': '/mnt/efs/swetha/marathi/ds-icefall-scripts/icefall', 'k2-path': '/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/k2/__init__.py', 'lhotse-path': '/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/lhotse/__init__.py', 'hostname': 'ip-10-40-6-153', 'IP address': '127.0.0.1'}, 'epoch': 40, 'iter': 0, 'avg': 35, 'use_averaged_model': True, 'exp_dir': PosixPath('pruned_transducer_stateless7/exp_1'), 'bpe_model': '/mnt/efs/swetha/marathi/ds-icefall-scripts/data/ma-in/lang_bpe_250/bpe.model', 'lang_dir': PosixPath('/mnt/efs/swetha/marathi/ds-icefall-scripts/data/ma-in/lang_bpe_250'), 'decoding_method': 'fast_beam_search_nbest_oracle', 'beam_size': 4, 'beam': 20.0, 'ngram_lm_scale': 0.01, 'max_contexts': 8, 'max_states': 64, 'context_size': 2, 'max_sym_per_frame': 1, 'num_paths': 200, 'nbest_scale': 0.5, 'simulate_streaming': False, 'decode_chunk_size': 16, 'left_context': 64, 'use_shallow_fusion': False, 'lm_type': 'rnn', 'lm_scale': 0.3, 'tokens_ngram': 3, 'backoff_id': 500, 'num_encoder_layers': '2,4,3,2,4', 'feedforward_dims': '1024,1024,2048,2048,1024', 'nhead': '8,8,8,8,8', 'encoder_dims': '384,384,384,384,384', 'attention_dims': '192,192,192,192,192', 'encoder_unmasked_dims': '256,256,256,256,256', 'zipformer_downsampling_factors': '1,2,4,8,2', 'cnn_module_kernels': '31,31,31,31,31', 'decoder_dim': 512, 'joiner_dim': 512, 'manifest_dir': PosixPath('/mnt/efs/swetha/marathi/ds-icefall-scripts/data/ma-in/manifests'), 'max_duration': 100, 'bucketing_sampler': True, 'num_buckets': 2, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': True, 'shuffle': True, 'drop_last': True, 'return_cuts': True, 'num_workers': 2, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': True, 'input_strategy': 'PrecomputedFeatures', 'lm_vocab_size': 500, 'lm_epoch': 7, 'lm_avg': 1, 'lm_exp_dir': None, 'rnn_lm_embedding_dim': 2048, 'rnn_lm_hidden_dim': 2048, 'rnn_lm_num_layers': 3, 'rnn_lm_tie_weights': True, 'transformer_lm_exp_dir': None, 'transformer_lm_dim_feedforward': 2048, 'transformer_lm_encoder_dim': 768, 'transformer_lm_embedding_dim': 768, 'transformer_lm_nhead': 8, 'transformer_lm_num_layers': 16, 'transformer_lm_tie_weights': True, 'res_dir': PosixPath('pruned_transducer_stateless7/exp_1/fast_beam_search_nbest_oracle'), 'suffix': 'epoch-40-avg-35-beam-20.0-max-contexts-8-max-states-64-nbest-scale-0.5-num-paths-200-use-averaged-model', 'blank_id': 0, 'unk_id': 2, 'vocab_size': 250}
2023-10-03 15:04:47,884 INFO [decode.py:850] About to create model
24
24
24
24
24
2023-10-03 15:04:48,591 INFO [zipformer.py:178] At encoder stack 4, which has downsampling_factor=2, we will combine the outputs of layers 1 and 3, with downsampling_factors=2 and 8.
2023-10-03 15:04:48,601 INFO [decode.py:917] Calculating the averaged model over epoch range from 5 (excluded) to 40
Traceback (most recent call last):
  File "./pruned_transducer_stateless7/decode.py", line 1015, in <module>
    main()
  File "/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./pruned_transducer_stateless7/decode.py", line 922, in main
    model.load_state_dict(
  File "/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Transducer:
        size mismatch for decoder.embedding.weight: copying a param with shape torch.Size([500, 512]) from checkpoint, the shape in current model is torch.Size([250, 512]).
        size mismatch for joiner.output_linear.weight: copying a param with shape torch.Size([500, 512]) from checkpoint, the shape in current model is torch.Size([250, 512]).
        size mismatch for joiner.output_linear.bias: copying a param with shape torch.Size([500]) from checkpoint, the shape in current model is torch.Size([250]).
        size mismatch for simple_am_proj.weight: copying a param with shape torch.Size([500, 384]) from checkpoint, the shape in current model is torch.Size([250, 384]).
        size mismatch for simple_am_proj.bias: copying a param with shape torch.Size([500]) from checkpoint, the shape in current model is torch.Size([250]).
        size mismatch for simple_lm_proj.weight: copying a param with shape torch.Size([500, 512]) from checkpoint, the shape in current model is torch.Size([250, 512]).
        size mismatch for simple_lm_proj.bias: copying a param with shape torch.Size([500]) from checkpoint, the shape in current model is torch.Size([250]).

**Comment by SSwethaSel0609** [comment]
below is my train log
2023-10-01 10:33:19,653 INFO [train.py:1005] (0/2) {'frame_shift_ms': 10.0, 'allowed_excess_duration_ratio': 0.1, 'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 50, 'reset_interval': 200, 'valid_interval': 3000, 'feature_dim': 80, 'subsampling_factor': 4, 'warm_step': 2000, 'env_info': {'k2-version': '1.24.3', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': '4c05309499a08454997adf500b56dcc629e35ae5', 'k2-git-date': 'Tue Jul 25 16:23:36 2023', 'lhotse-version': '1.17.0.dev+git.b138bafb.clean', 'torch-version': '1.13.0+cu116', 'torch-cuda-available': True, 'torch-cuda-version': '11.6', 'python-version': '3.8', 'icefall-git-branch': None, 'icefall-git-sha1': None, 'icefall-git-date': None, 'icefall-path': '/mnt/efs/swetha/marathi/ds-icefall-scripts/icefall', 'k2-path': '/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/k2/__init__.py', 'lhotse-path': '/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/lhotse/__init__.py', 'hostname': 'ip-10-40-6-153', 'IP address': '127.0.0.1'}, 'world_size': 2, 'master_port': 12355, 'tensorboard': True, 'num_epochs': 60, 'start_epoch': 31, 'start_batch': 0, 'exp_dir': PosixPath('pruned_transducer_stateless7/exp_1'), 'bpe_model': '/mnt/efs/swetha/marathi/ds-icefall-scripts/data_1/ma-in/lang_bpe_500/bpe.model', 'base_lr': 0.0001, 'lr_batches': 5000, 'lr_epochs': 3.5, 'context_size': 2, 'prune_range': 5, 'lm_scale': 0.25, 'am_scale': 0.0, 'simple_loss_scale': 0.5, 'seed': 42, 'print_diagnostics': False, 'inf_check': False, 'save_every_n': 2000, 'keep_last_k': 30, 'average_period': 200, 'use_fp16': False, 'num_encoder_layers': '2,4,3,2,4', 'feedforward_dims': '1024,1024,2048,2048,1024', 'nhead': '8,8,8,8,8', 'encoder_dims': '384,384,384,384,384', 'attention_dims': '192,192,192,192,192', 'encoder_unmasked_dims': '256,256,256,256,256', 'zipformer_downsampling_factors': '1,2,4,8,2', 'cnn_module_kernels': '31,31,31,31,31', 'decoder_dim': 512, 'joiner_dim': 512, 'manifest_dir': PosixPath('/mnt/efs/swetha/marathi/ds-icefall-scripts/data_1/ma-in/manifests'), 'max_duration': 100, 'bucketing_sampler': True, 'num_buckets': 8, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': True, 'shuffle': True, 'drop_last': True, 'return_cuts': True, 'num_workers': 10, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': True, 'input_strategy': 'PrecomputedFeatures', 'blank_id': 0, 'vocab_size': 500}
2023-10-01 10:33:19,653 INFO [train.py:1007] (0/2) About to create model

**Comment by SSwethaSel0609** [comment]
Yes thank you it has resolved

**Comment by SSwethaSel0609** [comment]
2023-10-03 16:07:27,418 INFO [train.py:914] Epoch 41, batch 0, loss[loss=1.343, simple_loss=1.688, pruned_loss=0.4987, over 1747.00 frames. ], tot_loss[loss=1.343, simple_loss=1.688, pruned_loss=0.4987, over 1747.00 frames. ], batch size: 8, lr: 1.93e-03,
2023-10-03 16:07:27,419 INFO [train.py:939] Computing validation loss
2023-10-03 16:07:31,246 INFO [train.py:692] Not all losses are finite!
simple_loss: inf
pruned_loss: inf
2023-10-03 16:07:31,247 INFO [train.py:1201] Saving batch to pruned_transducer_stateless7/exp_1/batch-fbc1af89-7d69-e938-c4f7-18fd250c67f3.pt
2023-10-03 16:07:31,333 INFO [train.py:1207] features shape: torch.Size([17, 576, 80])
2023-10-03 16:07:31,335 INFO [train.py:1211] num tokens: 293
Traceback (most recent call last):
  File "./pruned_transducer_stateless7/train.py", line 1275, in <module>
    main()
  File "./pruned_transducer_stateless7/train.py", line 1268, in main
    run(rank=0, world_size=1, args=args)
  File "./pruned_transducer_stateless7/train.py", line 1145, in run
    train_one_epoch(
  File "./pruned_transducer_stateless7/train.py", line 940, in train_one_epoch
    valid_info = compute_validation_loss(
  File "./pruned_transducer_stateless7/train.py", line 753, in compute_validation_loss
    loss, loss_info = compute_loss(
  File "./pruned_transducer_stateless7/train.py", line 704, in compute_loss
    raise ValueError(
ValueError: There are too many utterances in this batch leading to inf or nan losses.

**Comment by SSwethaSel0609** [comment]
Could you tell me the reason for getting this error?
Previously i got this error when was using 2 gpu and after changed 2 gpu to 1 gpu the error was resolved.. but now its not resolving..

**Comment by desh2608** [comment]
> 2023-10-03 16:07:27,418 INFO [train.py:914] Epoch 41, batch 0, loss[loss=1.343, simple_loss=1.688, pruned_loss=0.4987, over 1747.00 frames. ], tot_loss[loss=1.343, simple_loss=1.688, pruned_loss=0.4987, over 1747.00 frames. ], batch size: 8, lr: 1.93e-03, 2023-10-03 16:07:27,419 INFO 

Some observations: it seems that even after 40 epochs, your pruned loss is 0.5, which is quite large. Usually, I see the pruned loss reach < 0.1 in a few epochs of training. This suggests to me that either there is something weird with the data, or the model is not converging --- for the latter, you can try training with a lower learning rate.

**Comment by SSwethaSel0609** [comment]
Do i need to run the training from epoch 1 or should I continue from 40th epoch

**Comment by desh2608** [comment]
Probably from the beginning, since it doesn't look like the model has learned anything anyway.
