### ISSUE TITLE
Zipformer2 bug

### ISSUE THREAD

**Issue by vesis84** [k2-fsa/icefall#1320]
Hi,
i'd like to post a bug report.

When training 100h Librispeech model with Zipformer2 with [train2.py](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/train2.py), the following error message appears:
```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/K2_CONDA_ENVIRONMENT/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/src/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/train2.py", line 1102, in run
    scan_pessimistic_batches_for_oom(
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/src/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/train2.py", line 1211, in scan_pessimistic_batches_for_oom
    loss, _ = compute_loss(
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/src/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/train2.py", line 685, in compute_loss
    simple_loss, pruned_loss = model(
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/K2_CONDA_ENVIRONMENT/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/K2_CONDA_ENVIRONMENT/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/K2_CONDA_ENVIRONMENT/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/K2_CONDA_ENVIRONMENT/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/src/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/model.py", line 120, in forward
    encoder_out, x_lens = self.encoder(x, x_lens)
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/K2_CONDA_ENVIRONMENT/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/src/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer2.py", line 570, in forward
    x = module(
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/K2_CONDA_ENVIRONMENT/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/src/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer2.py", line 1268, in forward
    pos_emb = self.encoder_pos(src)
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/K2_CONDA_ENVIRONMENT/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/matylda5/iveselyk/ASR_TOOLKITS/K2_SHERPA_PYTORCH20/src/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer2.py", line 1884, in forward
    assert self.x_size == x.size(0), (self.x_size, x.size(0))
AssertionError: (16, 964)
```

It seems to be related to the [`RelPositionalEncoding`](https://github.com/k2-fsa/icefall/blob/36c60b0cf6b172e7739f5b177e731faa03737967/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/zipformer2.py#L1794) module. 

By tracing the code i found out that 16 is derived from `--decode-chunk-len` and 964 is very likely the utterance length.
I would be nice if someone can look into it.

I use the latest icefall and lhotse from src.

Running the training in conda on 4 GPU server with:
```
# 100h training
./pruned_transducer_stateless7_streaming/train2.py \
  --world-size 4 \
  --num-epochs 30 \
  --start-epoch 1 \
  --exp-dir pruned_transducer_stateless7_streaming/exp_100h \
  --full-libri 0 \
  --max-duration 300 
```

Best regards,
Karel

**Comment by csukuangfj** [comment]
Please don't use train2.py for training. It is for exporting models to ncnn. It is used only in export-for-ncnn.py

please use train.py instead.

**Comment by csukuangfj** [comment]
By they way, pruned_transducer_stateless7_streaming is zipformer, while `./zipformer` is zipformer2.

Please don't be confused by train.py and train2.py.

train2.py is not for zipformer2.

**Comment by vesis84** [comment]
Aha, i see, thank you for pointing me to the correct place ;-)
K.
