### ISSUE TITLE
Trimmed cut has supervisions with different channels

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1327]
Hello guys,

I am using Tedlium3 recipe example to perform training on my inhouse data.

During filter bank extraction on some utterances I get following error. I am working with mono PCM 16KHz files. I do not have any overlaps in the data. 

Could you please recommend me some try/catch that I can add to your code to skip such problematic utterances?

Traceback (most recent call last):
  File "local/compute_fbank_tedlium.py", line 109, in <module>
    compute_fbank_tedlium()
  File "local/compute_fbank_tedlium.py", line 101, in compute_fbank_tedlium
    cut_set.to_file(output_dir / f"{prefix}_cuts_{partition}.{suffix}")
  File "/opt/conda/lib/python3.8/site-packages/lhotse/serialization.py", line 532, in to_file
    store_manifest(self, path)
  File "/opt/conda/lib/python3.8/site-packages/lhotse/serialization.py", line 517, in store_manifest
    manifest.to_jsonl(path)
  File "/opt/conda/lib/python3.8/site-packages/lhotse/serialization.py", line 300, in to_jsonl
    save_to_jsonl(self.to_dicts(), path)
  File "/opt/conda/lib/python3.8/site-packages/lhotse/serialization.py", line 125, in save_to_jsonl
    for item in data:
  File "/opt/conda/lib/python3.8/site-packages/lhotse/cut/set.py", line 662, in <genexpr>
    return (cut.to_dict() for cut in self)
  File "/opt/conda/lib/python3.8/site-packages/lhotse/lazy.py", line 165, in values
    yield from self
  File "/opt/conda/lib/python3.8/site-packages/lhotse/lazy.py", line 465, in __iter__
    for cuts in self.iterator:
  File "/opt/conda/lib/python3.8/site-packages/lhotse/cut/set.py", line 3263, in _trim_to_supervisions_single
    return cuts.trim_to_supervisions(
  File "/opt/conda/lib/python3.8/site-packages/lhotse/cut/base.py", line 492, in trim_to_supervisions
    assert (
AssertionError: Trimmed cut has supervisions with different channels. Either set `keep_all_channels=True` to keep original channels or `keep_overlapping=False` to retain only 1 supervision per trimmed cut.

**Comment by csukuangfj** [comment]
Could you find out which wave in the cutset caused the assertion error?

**Comment by AlexandderGorodetski** [comment]
You can download wav and stm example from here
https://drive.google.com/drive/folders/1-szgplAmcoqFOR3CHgPnC9TdbTN7LKyE?usp=sharing
Note that stm file contains single utterance. This specific utterance causes this crash.

**Comment by AlexandderGorodetski** [comment]
Following line causes the crash (file compute_fbank_tedlium.py)
cut_set.to_file(output_dir / f"{prefix}_cuts_{partition}.{suffix}")
Maybe I can simply put try/catch to ignore failures of this line?

**Comment by pzelasko** [comment]
Did you try setting the options suggested in the error message?

**Comment by AlexandderGorodetski** [comment]
You are correct. Following line solves the issue

cut_set = cut_set.trim_to_supervisions(keep_overlapping=False,keep_all_channels=True)

Thank you so much. I will close the issue.
