### ISSUE TITLE
Divizsion by zero error 

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#1353]
Hello guys,

I am trying to debug my new database. So I am working with one hour only for training to verify that everyghing is good. 

I got following error. Could you help please

2023-10-30 18:25:20,828 INFO [train.py:1064] Training started
2023-10-30 18:25:20,837 INFO [train.py:1074] Device: cuda:0
2023-10-30 18:25:20,841 INFO [train.py:1083] {'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 50, 'reset_interval': 200, 'valid_interval': 3000, 'feature_dim': 80, 'subsampling_factor': 4, 'warm_step': 2000, 'env_info': {'k2-version': '1.24.3', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': '4c05309499a08454997adf500b56dcc629e35ae5', 'k2-git-date': 'Tue Jul 25 16:23:36 2023', 'lhotse-version': '1.17.0.dev+git.44bc1ab5.clean', 'torch-version': '1.13.0+cu116', 'torch-cuda-available': True, 'torch-cuda-version': '11.6', 'python-version': '3.8', 'icefall-git-branch': 'master', 'icefall-git-sha1': '52c24df-dirty', 'icefall-git-date': 'Wed Oct 18 12:36:14 2023', 'icefall-path': '/workspace/inputs/alexg/asr/src/models/k2/icefall', 'k2-path': '/opt/conda/lib/python3.8/site-packages/k2/__init__.py', 'lhotse-path': '/opt/conda/lib/python3.8/site-packages/lhotse/__init__.py', 'hostname': 'gpu-alex-speech-base-0-0', 'IP address': '10.244.6.250'}, 'world_size': 1, 'master_port': 12354, 'tensorboard': True, 'num_epochs': 10, 'start_epoch': 1, 'start_batch': 0, 'exp_dir': PosixPath('zipformer/exp'), 'bpe_model': 'data/lang_bpe_500/bpe.model', 'base_lr': 0.04, 'lr_batches': 7500, 'lr_epochs': 5, 'ref_duration': 600, 'context_size': 2, 'prune_range': 5, 'rnnt_type': 'regular', 'lm_scale': 0.25, 'am_scale': 0.0, 'simple_loss_scale': 0.5, 'seed': 42, 'print_diagnostics': False, 'inf_check': False, 'save_every_n': 4000, 'keep_last_k': 1, 'average_period': 200, 'use_fp16': True, 'num_encoder_layers': '1,1,1,1,1,1', 'downsampling_factor': '1,2,4,8,4,2', 'feedforward_dim': '512,768,768,768,768,768', 'num_heads': '1,1,1,1,1,1', 'encoder_dim': '192,256,256,256,256,256', 'query_head_dim': '32', 'value_head_dim': '12', 'pos_head_dim': '4', 'pos_dim': 48, 'encoder_unmasked_dim': '192,192,192,192,192,192', 'cnn_module_kernel': '31,31,15,15,15,31', 'decoder_dim': 512, 'joiner_dim': 512, 'causal': False, 'chunk_size': '16,32,64,-1', 'left_context_frames': '64,128,256,-1', 'manifest_dir': PosixPath('data/fbank'), 'max_duration': 1000, 'bucketing_sampler': True, 'num_buckets': 30, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'shuffle': True, 'return_cuts': True, 'num_workers': 2, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': True, 'blank_id': 0, 'vocab_size': 500}
2023-10-30 18:25:20,841 INFO [train.py:1085] About to create model
2023-10-30 18:25:21,058 INFO [train.py:1089] Number of model parameters: 11960065
2023-10-30 18:25:22,529 INFO [asr_datamodule.py:352] About to get train cuts
/opt/conda/lib/python3.8/site-packages/smart_open/smart_open_lib.py:250: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/lhotse/lazy.py:398: UserWarning: A lambda was passed to LazyFilter: it may prevent you from forking this process. If you experience issues with num_workers > 0 in torch.utils.data.DataLoader, try passing a regular function instead.
  warnings.warn(
2023-10-30 18:25:22,718 INFO [asr_datamodule.py:184] Enable SpecAugment
2023-10-30 18:25:22,718 INFO [asr_datamodule.py:185] Time warp factor: 80
2023-10-30 18:25:22,718 INFO [asr_datamodule.py:201] About to get Musan cuts
2023-10-30 18:25:22,719 INFO [asr_datamodule.py:204] Enable MUSAN
2023-10-30 18:25:24,789 INFO [asr_datamodule.py:226] About to create train dataset
2023-10-30 18:25:24,789 INFO [asr_datamodule.py:252] Using DynamicBucketingSampler.
2023-10-30 18:25:25,131 INFO [asr_datamodule.py:272] About to create train dataloader
2023-10-30 18:25:25,131 INFO [asr_datamodule.py:359] About to get dev cuts
2023-10-30 18:25:25,133 INFO [asr_datamodule.py:292] About to create dev dataset
2023-10-30 18:25:25,149 INFO [asr_datamodule.py:311] About to create dev dataloader
2023-10-30 18:25:25,149 INFO [train.py:1257] Sanity check -- see if any of the batches in epoch 1 would cause OOM.
/opt/conda/lib/python3.8/site-packages/lhotse/dataset/sampling/utils.py:71: UserWarning: Empty sampler encountered in find_pessimistic_batches()
  warnings.warn("Empty sampler encountered in find_pessimistic_batches()")
Traceback (most recent call last):
  File "./zipformer/train.py", line 1308, in <module>
    main()
  File "./zipformer/train.py", line 1301, in main
    run(rank=0, world_size=1, args=args)
  File "./zipformer/train.py", line 1179, in run
    train_one_epoch(
  File "./zipformer/train.py", line 1037, in train_one_epoch
    loss_value = tot_loss["loss"] / tot_loss["frames"]
ZeroDivisionError: division by zero

**Comment by AlexandderGorodetski** [comment]
Guys, the error disappeared when I increase the training db from 1hour to 10hours. Hope this is ok with you.

**Comment by csukuangfj** [comment]
please use pdb to debug it.

**Comment by Airgods** [comment]
> Guys, the error disappeared when I increase the training db from 1hour to 10hours. Hope this is ok with you.

请问在哪调训练时长呢？
