### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by weru88097** [k2-fsa/icefall#1363]
I'm running zipformer under aishell dataset with this problem, would like to get an answer thanks!
The specific errors are as follows:
Traceback (most recent call last):
  File "zipformer/train.py", line 1350, in <module>
    main()
  File "zipformer/train.py", line 1343, in main
    run(rank=0, world_size=1, args=args)
  File "zipformer/train.py", line 1219, in run
    train_one_epoch(
  File "zipformer/train.py", line 927, in train_one_epoch
    scaler.step(optimizer)
  File "/home/weiyangjie/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 313, in step
    return optimizer.step(*args, **kwargs)
  File "/home/weiyangjie/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/weiyangjie/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/newdisk0630/wbb/Project/icefall/egs/aishell/ASR/zipformer/optim.py", line 339, in step
    clipping_scale = self._get_clipping_scale(group, batches)
  File "/newdisk0630/wbb/Project/icefall/egs/aishell/ASR/zipformer/optim.py", line 493, in _get_clipping_scale
    self._show_gradient_dominating_parameter(tuples, tot_sumsq)
  File "/newdisk0630/wbb/Project/icefall/egs/aishell/ASR/zipformer/optim.py", line 538, in _show_gradient_dominating_parameter
    assert torch.isclose(
AssertionError

**Comment by JinZr** [comment]
hi, there's a recent update on the `optim.py`, have you tried it yet?

**Comment by weru88097** [comment]
> hi, there's a recent update on the `optim.py`, have you tried it yet?

I haven't tried it yet, I'll give it a try thanks.

**Comment by marcoyang1998** [comment]
Are you having parameters in your model that don't have gradient?

**Comment by weru88097** [comment]
Successful. Thanks for the answer.
