### ISSUE TITLE
Value error while preparing data

### ISSUE THREAD

**Issue by SSwethaSel0609** [k2-fsa/icefall#1367]
Traceback (most recent call last):
  File "./scripts/data_parser_kaldi.py", line 205, in <module>
    parser.parse()
  File "./scripts/data_parser_kaldi.py", line 115, in parse
    rec, sup, fea = load_kaldi_data_dir(
  File "/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/lhotse/kaldi.py", line 190, in load_kaldi_data_dir
    texts = load_kaldi_text_mapping(path / "text")
  File "/mnt/efs/swetha/icefall_env_swe/lib/python3.8/site-packages/lhotse/kaldi.py", line 530, in load_kaldi_text_mapping
    mapping = dict(line.strip().split(maxsplit=1) for line in f)
ValueError: dictionary update sequence element #103775 has length 0; 2 is required

**Comment by csukuangfj** [comment]
Please find which line in your `text` causes the above error.

**Comment by JinZr** [comment]
this error was thrown within lhotse, maybe you want to refer to their documents for reference

https://lhotse.readthedocs.io/en/latest/
