### ISSUE TITLE
Training code giving error 

### ISSUE THREAD

**Issue by sanjuktasr** [k2-fsa/icefall#1392]
AssertionError: (tensor([218, 215, 209, 200, 197, 191, 180, 177, 171, 165, 163, 154, 150, 148,
        144, 139, 130,  90,  87,  78,  77,  50,  50,  10,   2,   0,   0],
       device='cuda:0', dtype=torch.int32), tensor([109, 108, 105, 100,  99,  96,  90,  89,  86,  83,  82,  77,  75,  74,
         72,  70,  65,  45,  44,  39,  39,  25,  25,   5,   1,   0,   0],
       device='cuda:0', dtype=torch.int32))
Cant understand the root cause for this error.

**Comment by csukuangfj** [comment]
Please post the complete error logs.

The information you give is too limited.

**Comment by sanjuktasr** [comment]
2023-11-24 13:58:46,307 INFO [train2.py:1123] {'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 50, 'reset_interval': 200, 'valid_interval': 3000, 'feature_dim': 80, 'subsampling_factor': 4, 'warm_step': 2000, 'env_info': {'k2-version': '1.24.3', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': '7ff6d891905ff482364f2d0015867b00d89dd8c7', 'k2-git-date': 'Fri Jun 16 12:10:37 2023', 'lhotse-version': '1.16.0.dev+git.aa073f6a.clean', 'torch-version': '1.13.1+cu117', 'torch-cuda-available': True, 'torch-cuda-version': '11.7', 'python-version': '3.9', 'icefall-git-branch': 'master', 'icefall-git-sha1': 'fc2df07-dirty', 'icefall-git-date': 'Wed Aug 16 20:02:41 2023', 'icefall-path': '/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall', 'k2-path': '/home/sanjukta/anaconda3/envs/zipf1/lib/python3.9/site-packages/k2/__init__.py', 'lhotse-path': '/NAS1/sanjukta_repo_falcon1/zip_exp_6/lhotse/lhotse/__init__.py', 'hostname': 'asus-System-Product-Name', 'IP address': '127.0.1.1'}, 'world_size': 1, 'master_port': 12354, 'tensorboard': True, 'num_epochs': 40, 'start_epoch': 1, 'start_batch': 0, 'exp_dir': PosixPath('zipformer/exp-tamlish/24_11_2023'), 'bpe_model': 'data/via/tamil/23_11_2023/lang_bpe_500/bpe.model', 'base_lr': 0.04, 'lr_batches': 7500, 'lr_epochs': 3.5, 'ref_duration': 600, 'context_size': 2, 'prune_range': 5, 'lm_scale': 0.25, 'am_scale': 0.0, 'simple_loss_scale': 0.5, 'ctc_loss_scale': 0.2, 'seed': 42, 'print_diagnostics': False, 'inf_check': False, 'save_every_n': 4000, 'keep_last_k': 30, 'average_period': 200, 'use_fp16': True, 'num_encoder_layers': '2,2,2,2,2,2', 'downsampling_factor': '1,2,4,8,4,2', 'feedforward_dim': '512,768,768,768,768,768', 'num_heads': '4,4,4,8,4,4', 'encoder_dim': '192,256,256,256,256,256', 'query_head_dim': '32', 'value_head_dim': '12', 'pos_head_dim': '4', 'pos_dim': 48, 'encoder_unmasked_dim': '192,192,192,192,192,192', 'cnn_module_kernel': '31,31,15,15,15,31', 'decoder_dim': 512, 'joiner_dim': 512, 'causal': False, 'chunk_size': '16,32,64,-1', 'left_context_frames': '64,128,256,-1', 'use_transducer': True, 'use_ctc': False, 'full_libri': True, 'mini_libri': False, 'manifest_dir': PosixPath('data/via/tamil/24_11_2023/fbank'), 'max_duration': 200.0, 'bucketing_sampler': True, 'num_buckets': 30, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'shuffle': True, 'drop_last': True, 'return_cuts': True, 'num_workers': 2, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': False, 'input_strategy': 'PrecomputedFeatures', 'blank_id': 0, 'vocab_size': 500}
2023-11-24 13:58:46,307 INFO [train2.py:1125] About to create model
2023-11-24 13:58:46,582 INFO [train2.py:1129] Number of model parameters: 23285615
2023-11-24 13:58:48,036 INFO [asr_datamodule.py:434] About to get the shuffled train-clean-100,             train-clean-360 and train-other-500 cuts
2023-11-24 13:58:48,039 INFO [asr_datamodule.py:239] Disable MUSAN
2023-11-24 13:58:48,039 INFO [asr_datamodule.py:257] Enable SpecAugment
2023-11-24 13:58:48,039 INFO [asr_datamodule.py:258] Time warp factor: 80
2023-11-24 13:58:48,039 INFO [asr_datamodule.py:268] Num frame mask: 10
2023-11-24 13:58:48,039 INFO [asr_datamodule.py:281] About to create train dataset
2023-11-24 13:58:48,040 INFO [asr_datamodule.py:308] Using DynamicBucketingSampler.
2023-11-24 13:58:50,991 INFO [asr_datamodule.py:323] About to create train dataloader
2023-11-24 13:58:50,991 INFO [asr_datamodule.py:451] About to get dev-clean cuts
2023-11-24 13:58:50,993 INFO [asr_datamodule.py:354] About to create dev dataset
2023-11-24 13:58:50,996 INFO [asr_datamodule.py:371] About to create dev dataloader
2023-11-24 13:58:50,996 INFO [train2.py:1339] Sanity check -- see if any of the batches in epoch 1 would cause OOM.
2023-11-24 13:59:45,760 INFO [train2.py:1367] Maximum memory allocated so far is 2402MB
2023-11-24 13:59:46,008 INFO [train2.py:1367] Maximum memory allocated so far is 2492MB
2023-11-24 13:59:46,312 INFO [train2.py:1367] Maximum memory allocated so far is 2492MB
2023-11-24 13:59:46,606 INFO [train2.py:1367] Maximum memory allocated so far is 2492MB
2023-11-24 13:59:46,859 INFO [scaling.py:979] Whitening: name=None, num_groups=1, num_channels=256, metric=43.89 vs. limit=7.5
2023-11-24 13:59:46,986 INFO [train2.py:1367] Maximum memory allocated so far is 2492MB
2023-11-24 13:59:47,253 INFO [scaling.py:979] Whitening: name=None, num_groups=1, num_channels=256, metric=50.82 vs. limit=7.5
2023-11-24 13:59:47,304 INFO [train2.py:1367] Maximum memory allocated so far is 2492MB
2023-11-24 13:59:50,956 INFO [train2.py:1033] Epoch 1, batch 0, loss[loss=8.912, simple_loss=8.109, pruned_loss=8.013, over 4501.00 frames. ], tot_loss[loss=8.912, simple_loss=8.109, pruned_loss=8.013, over 4501.00 frames. ], batch size: 13, lr: 2.00e-02, grad_scale: 2.0
2023-11-24 13:59:50,957 INFO [train2.py:1056] Computing validation loss
Traceback (most recent call last):
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 1390, in <module>
    main()
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 1383, in main
    run(rank=0, world_size=1, args=args)
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 1261, in run
    train_one_epoch(
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 1057, in train_one_epoch
    valid_info = compute_validation_loss(
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 857, in compute_validation_loss
    loss, loss_info = compute_loss(
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 795, in compute_loss
    simple_loss, pruned_loss, ctc_loss = model(
  File "/home/sanjukta/anaconda3/envs/zipf1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/zipformer/model.py", line 326, in forward
    encoder_out, encoder_out_lens = self.forward_encoder(x, x_lens)
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/zipformer/model.py", line 141, in forward_encoder
    assert torch.all(encoder_out_lens > 0), (x_lens, encoder_out_lens)
AssertionError: (tensor([218, 215, 209, 200, 197, 191, 180, 177, 171, 165, 163, 154, 150, 148,
        144, 139, 130,  90,  87,  78,  77,  50,  50,  10,   2,   0,   0],
       device='cuda:0', dtype=torch.int32), tensor([109, 108, 105, 100,  99,  96,  90,  89,  86,  83,  82,  77,  75,  74,
         72,  70,  65,  45,  44,  39,  39,  25,  25,   5,   1,   0,   0],
       device='cuda:0', dtype=torch.int32))

**Comment by csukuangfj** [comment]
> assert torch.all(encoder_out_lens > 0), (x_lens, encoder_out_lens)

The logs show that some entries of `encoder_out_lens` is 0, which means some of the audio data in your batch is toooo short. Please remove them from the training data.

`x_lens[-1]` and `x_lens[-2]` are 0, which indicates there are some issues with your data.

**Comment by sanjuktasr** [comment]
Hello ,
my dataset contains audios above 0.1s currently.

**Comment by sanjuktasr** [comment]
Hello,
same error appears for dataset containing audios with duration>=1second.
Traceback (most recent call last):
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 1390, in <module>
    main()
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 1383, in main
    run(rank=0, world_size=1, args=args)
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 1261, in run
    train_one_epoch(
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 1057, in train_one_epoch
    valid_info = compute_validation_loss(
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 857, in compute_validation_loss
    loss, loss_info = compute_loss(
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/./zipformer/train2.py", line 795, in compute_loss
    simple_loss, pruned_loss, ctc_loss = model(
  File "/home/sanjukta/anaconda3/envs/zipf1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/zipformer/model.py", line 326, in forward
    encoder_out, encoder_out_lens = self.forward_encoder(x, x_lens)
  File "/NAS1/sanjukta_repo_falcon1/zip_exp_6/icefall/egs/librispeech/ASR/zipformer/model.py", line 141, in forward_encoder
    assert torch.all(encoder_out_lens > 0), (x_lens, encoder_out_lens)
AssertionError: (tensor([218, 215, 209, 200, 197, 191, 180, 177, 171, 165, 163, 154, 150, 148,
        144, 139, 130,  90,  87,  78,  77,  50,  50,  10,   2,   0,   0],
       device='cuda:0', dtype=torch.int32), tensor([109, 108, 105, 100,  99,  96,  90,  89,  86,  83,  82,  77,  75,  74,
         72,  70,  65,  45,  44,  39,  39,  25,  25,   5,   1,   0,   0],
       device='cuda:0', dtype=torch.int32))
