### ISSUE TITLE
Exception when rescoring with attention decoder

### ISSUE THREAD

**Issue by drawfish** [k2-fsa/icefall#144]
After successfully decode test dataset with 1best decoder. I decided to take attention decoder to get better result.
But it seems that something unexpected occured. I have no idea on how to debug the reason that cause this exception. 
Can anyone make suggestions ?
Exception information:
```
Traceback (most recent call last):
  File "conformer/decode_mmi.py", line 485, in <module>
    main()
  File "/cfs/sge/miniconda3/envs/k2-debug/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "conformer/decode_mmi.py", line 469, in main
    results_dict = decode_dataset(
  File "conformer/decode_mmi.py", line 320, in decode_dataset
    hyps_dict, texts = decode_one_batch(
  File "conformer/decode_mmi.py", line 256, in decode_one_batch
    best_path_dict = rescore_with_attention_decoder(
  File "/cfs/sge/k2/icefall/icefall/decode.py", line 828, in rescore_with_attention_decoder
    nbest = nbest.intersect(lattice)
  File "/cfs/sge/k2/icefall/icefall/decode.py", line 333, in intersect
    path_lattice = _intersect_device(
  File "/cfs/sge/k2/icefall/icefall/decode.py", line 64, in _intersect_device
    return k2.cat(ans)
  File "/cfs/sge/k2/k2/k2/python/k2/ops.py", line 219, in cat
    out_fsa = Fsa(ans_ragged_arcs)
  File "/cfs/sge/k2/k2/k2/python/k2/fsa.py", line 229, in __init__
    _ = self.properties
  File "/cfs/sge/k2/k2/k2/python/k2/fsa.py", line 455, in properties
    raise ValueError(
ValueError: Fsa is not valid, properties are: 2 = "Nonempty", arcs are: [ [ [ 0 1 0 -2.23462 0 2 0 -7.25351 ] [ 1 3 0 -2.4075 1 4 0 -7.06948 ] [ 2 5 0 -2.4075 ] [ 3 6 0 -2.97694 3 7 0 -5.45353 ] ...
```

**Comment by csukuangfj** [comment]
It's easier to debug to reduce max duration and number of paths.

**Comment by drawfish** [comment]
Seems that the problem is caused by too large lattice, reducing max duration sloved it.
