### ISSUE TITLE
RuntimeError: grad_scale is too small when training Large scale Zipformer model (streaming)

### ISSUE THREAD

**Issue by sangeet2020** [k2-fsa/icefall#1463]
Hi,
I am trying to train a zipformer model from  https://github.com/k2-fsa/icefall/tree/master/egs/librispeech/ASR/zipformer
The model is causal (streaming model) and training runs fine on the Medium scale model (66M params) 
however, if I try training a large scale model (148 params), I experience 
```
RuntimeError: grad_scale is too small, exiting: 1.2924697071141057e-26
```
Training parameters and hyperaparmets are mostly same as the default ones, except the following ones
```bash
NUM_ENCODER_LAYERS="2,2,4,5,4,2"
DOWNSAMPLING_FACTOR="1,2,4,8,4,2"
FEEDFORWARD_DIM="512,768,1536,2048,1536,768"
NUM_HEADS="4,4,4,8,4,4"
ENCODER_DIM="192,256,512,768,512,256"
ENCODER_UNMASKED_DIM="192,192,256,320,256,192"
```
Here is error log

```unix
2024-01-13 23:48:07,606 INFO [train.py:1423] (0/4) Maximum memory allocated so far is 7150MB
2024-01-13 23:48:09,047 INFO [train.py:1423] (0/4) Maximum memory allocated so far is 7150MB
2024-01-13 23:48:10,560 INFO [train.py:1423] (0/4) Maximum memory allocated so far is 7150MB
2024-01-13 23:48:12,074 INFO [train.py:1423] (0/4) Maximum memory allocated so far is 7150MB
2024-01-13 23:48:13,761 INFO [train.py:1423] (0/4) Maximum memory allocated so far is 7150MB
2024-01-13 23:48:15,369 INFO [train.py:1423] (0/4) Maximum memory allocated so far is 7150MB
2024-01-13 23:48:29,146 INFO [train.py:1068] (0/4) Epoch 1, batch 0, loss[loss=0.6863, simple_loss=6.779, pruned_loss=6.834, over 7036.00 frames. ], tot_los
s[loss=0.6863, simple_loss=6.779, pruned_loss=6.834, over 7036.00 frames. ], batch size: 26, lr: 2.25e-02, grad_scale: 2.0
2024-01-13 23:48:29,147 INFO [train.py:1092] (0/4) Computing validation loss
2024-01-13 23:51:10,464 INFO [train.py:1102] (0/4) Epoch 1, validation: loss=0.6623, simple_loss=6.812, pruned_loss=6.595, over 13323570.00 frames.
2024-01-13 23:51:10,464 INFO [train.py:1103] (0/4) Maximum memory allocated so far is 7150MB
2024-01-13 23:52:28,504 INFO [train.py:1068] (0/4) Epoch 1, batch 50, loss[loss=0.1251, simple_loss=6.641, pruned_loss=1.031, over 7163.00 frames. ], tot_lo
ss[loss=0.1908, simple_loss=6.797, pruned_loss=1.771, over 316374.88 frames. ], batch size: 73, lr: 2.48e-02, grad_scale: 2.0
2024-01-13 23:52:39,334 INFO [scaling.py:1120] (2/4) WithLoss: name=encoder.encoders.0.layers.1.self_attn_weights, loss-sum=0.000e+00
2024-01-13 23:53:48,694 INFO [train.py:1068] (0/4) Epoch 1, batch 100, loss[loss=0.1438, simple_loss=6.506, pruned_loss=1.014, over 7132.00 frames. ], tot_l
oss[loss=0.1652, simple_loss=6.729, pruned_loss=1.394, over 557411.57 frames. ], batch size: 30, lr: 2.70e-02, grad_scale: 4.0
2024-01-13 23:54:24,055 INFO [scaling.py:1120] (0/4) WithLoss: name=encoder.encoders.3.encoder.layers.4.self_attn_weights, loss-sum=2.126e-01
2024-01-13 23:55:08,485 INFO [train.py:1068] (0/4) Epoch 1, batch 150, loss[loss=0.1459, simple_loss=6.146, pruned_loss=0.9026, over 7253.00 frames. ], tot_
loss[loss=0.1612, simple_loss=6.611, pruned_loss=1.238, over 747861.26 frames. ], batch size: 44, lr: 2.93e-02, grad_scale: 4.0
2024-01-13 23:55:08,653 INFO [scaling.py:1120] (1/4) WithLoss: name=encoder.encoders.2.encoder.layers.1.self_attn_weights, loss-sum=1.134e-02
2024-01-13 23:55:43,021 INFO [scaling.py:1120] (1/4) WithLoss: name=encoder.encoders.1.encoder.layers.0.self_attn_weights, loss-sum=4.010e-02
2024-01-13 23:56:28,928 INFO [train.py:1068] (0/4) Epoch 1, batch 200, loss[loss=0.1735, simple_loss=6.042, pruned_loss=0.959, over 7244.00 frames. ], tot_l
oss[loss=0.1623, simple_loss=6.421, pruned_loss=1.14, over 891815.46 frames. ], batch size: 74, lr: 3.15e-02, grad_scale: 8.0
2024-01-13 23:57:48,837 INFO [train.py:1068] (0/4) Epoch 1, batch 250, loss[loss=0.1738, simple_loss=5.88, pruned_loss=0.8708, over 7260.00 frames. ], tot_l
oss[loss=0.1648, simple_loss=6.25, pruned_loss=1.063, over 1008502.99 frames. ], batch size: 44, lr: 3.38e-02, grad_scale: 8.0
2024-01-13 23:58:19,202 INFO [scaling.py:1120] (1/4) WithLoss: name=encoder.encoders.4.encoder.layers.1.self_attn_weights, loss-sum=2.325e-01
2024-01-13 23:59:08,809 INFO [train.py:1068] (0/4) Epoch 1, batch 300, loss[loss=0.1937, simple_loss=5.689, pruned_loss=0.8897, over 7236.00 frames. ], tot_
loss[loss=0.1686, simple_loss=6.093, pruned_loss=1.002, over 1101668.31 frames. ], batch size: 62, lr: 3.60e-02, grad_scale: 8.0
2024-01-13 23:59:30,873 INFO [scaling.py:1120] (2/4) WithLoss: name=encoder.encoders.2.encoder.layers.2.self_attn_weights, loss-sum=5.175e+00
2024-01-14 00:00:27,678 INFO [train.py:1068] (0/4) Epoch 1, batch 350, loss[loss=0.1787, simple_loss=5.082, pruned_loss=0.7595, over 7273.00 frames. ], tot_
loss[loss=0.1746, simple_loss=5.922, pruned_loss=0.9592, over 1169454.38 frames. ], batch size: 38, lr: 3.83e-02, grad_scale: 8.0
2024-01-14 00:01:47,689 INFO [train.py:1068] (0/4) Epoch 1, batch 400, loss[loss=0.2324, simple_loss=5.529, pruned_loss=0.9209, over 5484.00 frames. ], tot_
loss[loss=0.1799, simple_loss=5.708, pruned_loss=0.9186, over 1221018.98 frames. ], batch size: 130, lr: 4.05e-02, grad_scale: 16.0
2024-01-14 00:03:05,605 INFO [train.py:1068] (0/4) Epoch 1, batch 450, loss[loss=0.21, simple_loss=4.778, pruned_loss=0.7814, over 7190.00 frames. ], tot_lo
ss[loss=0.1871, simple_loss=5.541, pruned_loss=0.8892, over 1262781.09 frames. ], batch size: 39, lr: 4.28e-02, grad_scale: 16.0
2024-01-14 00:03:25,780 WARNING [optim.py:500] (2/4) Scaling gradients by 0.04990599676966667, model_norm_threshold=53.983238220214844
2024-01-14 00:03:25,781 WARNING [optim.py:500] (1/4) Scaling gradients by 0.04990599676966667, model_norm_threshold=53.983238220214844
2024-01-14 00:03:25,781 WARNING [optim.py:500] (0/4) Scaling gradients by 0.04990599676966667, model_norm_threshold=53.983238220214844
2024-01-14 00:03:25,782 WARNING [optim.py:500] (3/4) Scaling gradients by 0.04990599676966667, model_norm_threshold=53.983238220214844
2024-01-14 00:03:25,985 WARNING [optim.py:572] (2/4) Parameter dominating tot_sumsq module.encoder_embed.conv.0.weight with proportion 0.68, where dominant_
sumsq=(grad_sumsq*orig_rms_sq)=7.941e+05, grad_sumsq=2.178e+07, orig_rms_sq=3.647e-02
2024-01-14 00:03:25,994 WARNING [optim.py:572] (1/4) Parameter dominating tot_sumsq module.encoder_embed.conv.0.weight with proportion 0.68, where dominant_
sumsq=(grad_sumsq*orig_rms_sq)=7.941e+05, grad_sumsq=2.178e+07, orig_rms_sq=3.647e-02
2024-01-14 00:03:25,997 WARNING [optim.py:572] (0/4) Parameter dominating tot_sumsq module.encoder_embed.conv.0.weight with proportion 0.68, where dominant_
sumsq=(grad_sumsq*orig_rms_sq)=7.941e+05, grad_sumsq=2.178e+07, orig_rms_sq=3.647e-02
2024-01-14 00:03:26,004 WARNING [optim.py:572] (3/4) Parameter dominating tot_sumsq module.encoder_embed.conv.0.weight with proportion 0.68, where dominant_
sumsq=(grad_sumsq*orig_rms_sq)=7.941e+05, grad_sumsq=2.178e+07, orig_rms_sq=3.647e-02
2024-01-14 00:03:35,116 WARNING [optim.py:500] (2/4) Scaling gradients by 0.07831460982561111, model_norm_threshold=53.983238220214844
2024-01-14 00:03:35,117 WARNING [optim.py:500] (1/4) Scaling gradients by 0.07831460982561111, model_norm_threshold=53.983238220214844
2024-01-14 00:03:35,117 WARNING [optim.py:500] (0/4) Scaling gradients by 0.07831460982561111, model_norm_threshold=53.983238220214844
2024-01-14 00:03:35,119 WARNING [optim.py:500] (3/4) Scaling gradients by 0.07831460982561111, model_norm_threshold=53.983238220214844
2024-01-14 00:03:35,319 WARNING [optim.py:572] (2/4) Parameter dominating tot_sumsq module.encoder_embed.conv.0.weight with proportion 0.77, where dominant_
sumsq=(grad_sumsq*orig_rms_sq)=3.645e+05, grad_sumsq=1.009e+07, orig_rms_sq=3.613e-02
2024-01-14 00:03:35,328 WARNING [optim.py:572] (0/4) Parameter dominating tot_sumsq module.encoder_embed.conv.0.weight with proportion 0.77, where dominant_
sumsq=(grad_sumsq*orig_rms_sq)=3.645e+05, grad_sumsq=1.009e+07, orig_rms_sq=3.613e-02
2024-01-14 00:03:35,344 WARNING [optim.py:572] (3/4) Parameter dominating tot_sumsq module.encoder_embed.conv.0.weight with proportion 0.77, where dominant_
sumsq=(grad_sumsq*orig_rms_sq)=3.645e+05, grad_sumsq=1.009e+07, orig_rms_sq=3.613e-02

.
.
.
.
2024-01-14 00:56:12,602 INFO [scaling.py:1120] (2/4) WithLoss: name=encoder.encoders.4.encoder.layers.3.self_attn_weights, loss-sum=0.000e+00
2024-01-14 00:56:40,816 INFO [scaling.py:1120] (2/4) WithLoss: name=encoder.encoders.1.encoder.layers.0.self_attn_weights, loss-sum=6.621e+01
2024-01-14 00:56:47,963 INFO [train.py:1068] (0/4) Epoch 1, batch 2550, loss[loss=0.3702, simple_loss=6.42, pruned_loss=0.7405, over 7278.00 frames. ], tot_loss[loss=0.3662, simple_loss=6.353, pruned_loss=0.7328, over 1412971.78 frames. ], batch size: 44, lr: 4.38e-02, grad_scale: 0.0625
2024-01-14 00:57:03,583 INFO [scaling.py:1120] (0/4) WithLoss: name=encoder.encoders.2.encoder.layers.3.self_attn_weights, loss-sum=3.410e-02
2024-01-14 00:58:03,509 INFO [train.py:1068] (0/4) Epoch 1, batch 2600, loss[loss=0.3837, simple_loss=6.468, pruned_loss=0.7675, over 7294.00 frames. ], tot_loss[loss=0.3663, simple_loss=6.354, pruned_loss=0.733, over 1413622.02 frames. ], batch size: 48, lr: 4.37e-02, grad_scale: 0.125
2024-01-14 00:58:22,176 INFO [scaling.py:1120] (0/4) WithLoss: name=encoder.encoders.5.encoder.layers.0.self_attn_weights, loss-sum=2.299e-02
2024-01-14 00:59:18,817 INFO [train.py:1068] (0/4) Epoch 1, batch 2650, loss[loss=0.3791, simple_loss=6.61, pruned_loss=0.7582, over 7292.00 frames. ], tot_loss[loss=0.3666, simple_loss=6.36, pruned_loss=0.7335, over 1410418.96 frames. ], batch size: 52, lr: 4.37e-02, grad_scale: 0.0625
2024-01-14 01:00:33,681 INFO [train.py:1068] (0/4) Epoch 1, batch 2700, loss[loss=0.3546, simple_loss=6.423, pruned_loss=0.7092, over 7050.00 frames. ], tot_loss[loss=0.3676, simple_loss=6.371, pruned_loss=0.7353, over 1413348.55 frames. ], batch size: 93, lr: 4.36e-02, grad_scale: 0.03125
2024-01-14 01:01:40,856 INFO [scaling.py:1120] (1/4) WithLoss: name=encoder.encoders.3.encoder.layers.1.self_attn_weights, loss-sum=0.000e+00
2024-01-14 01:01:46,648 INFO [train.py:1068] (0/4) Epoch 1, batch 2750, loss[loss=inf, simple_loss=inf, pruned_loss=inf, over 7161.00 frames. ], tot_loss[loss=inf, simple_loss=inf, pruned_loss=inf, over 1408521.40 frames. ], batch size: 69, lr: 4.36e-02, grad_scale: 1.4551915228366852e-11
2024-01-14 01:01:48,172 INFO [scaling.py:1120] (1/4) WithLoss: name=encoder.encoders.1.encoder.layers.1.self_attn_weights, loss-sum=1.363e+00
2024-01-14 01:01:55,285 INFO [scaling.py:1120] (0/4) WithLoss: name=encoder.encoders.4.encoder.layers.3.self_attn_weights, loss-sum=0.000e+00
2024-01-14 01:02:58,097 INFO [checkpoint.py:75] (1/4) Saving checkpoint to zipformer/exp-causal/2500/bad-model-first-warning-1.pt
2024-01-14 01:02:58,098 INFO [checkpoint.py:75] (0/4) Saving checkpoint to zipformer/exp-causal/2500/bad-model-first-warning-0.pt
2024-01-14 01:02:58,099 INFO [checkpoint.py:75] (3/4) Saving checkpoint to zipformer/exp-causal/2500/bad-model-first-warning-3.pt
2024-01-14 01:02:58,100 INFO [checkpoint.py:75] (2/4) Saving checkpoint to zipformer/exp-causal/2500/bad-model-first-warning-2.pt
2024-01-14 01:03:00,598 WARNING [train.py:1057] (3/4) Grad scale is small: 1.2924697071141057e-26
2024-01-14 01:03:00,598 INFO [checkpoint.py:75] (3/4) Saving checkpoint to zipformer/exp-causal/2500/bad-model-3.pt
2024-01-14 01:03:00,659 WARNING [train.py:1057] (1/4) Grad scale is small: 1.2924697071141057e-26
2024-01-14 01:03:00,660 INFO [checkpoint.py:75] (1/4) Saving checkpoint to zipformer/exp-causal/2500/bad-model-1.pt
2024-01-14 01:03:00,826 WARNING [train.py:1057] (2/4) Grad scale is small: 1.2924697071141057e-26
2024-01-14 01:03:00,826 INFO [checkpoint.py:75] (2/4) Saving checkpoint to zipformer/exp-causal/2500/bad-model-2.pt
2024-01-14 01:03:01,769 WARNING [train.py:1057] (0/4) Grad scale is small: 1.2924697071141057e-26
2024-01-14 01:03:01,769 INFO [checkpoint.py:75] (0/4) Saving checkpoint to zipformer/exp-causal/2500/bad-model-0.pt
Traceback (most recent call last):
  File "/mnt/local/sangeet/workncode/k2-fsa/icefall/egs/Deu16/ASR/./zipformer/train.py", line 1446, in <module>
    main()
  File "/mnt/local/sangeet/workncode/k2-fsa/icefall/egs/Deu16/ASR/./zipformer/train.py", line 1437, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/mnt/users/sagarst/envs/k2-gpu/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/users/sagarst/envs/k2-gpu/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
              ^^^^^^^^^^^^^^
  File "/mnt/users/sagarst/envs/k2-gpu/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/mnt/users/sagarst/envs/k2-gpu/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/mnt/local/sangeet/workncode/k2-fsa/icefall/egs/Deu16/ASR/zipformer/train.py", line 1309, in run
    train_one_epoch(
  File "/mnt/local/sangeet/workncode/k2-fsa/icefall/egs/Deu16/ASR/zipformer/train.py", line 1060, in train_one_epoch
    raise RuntimeError(
RuntimeError: grad_scale is too small, exiting: 1.2924697071141057e-26

```

Any hints or suggestions what could be wrong, or any parameter that needs to be adjusted?

thank you

**Comment by sangeet2020** [comment]
I see that
```
```

**Comment by marcoyang1998** [comment]
What max_duration and how may GPUs are you using? This type of error may happen if your batch size is small.

**Comment by sangeet2020** [comment]
MAX_DURATION=300, and I am using 4 GPUs with fp-16 training enabled.

**Comment by marcoyang1998** [comment]
You could either try increasing max_duration (if it fits your GPU memory) or reducing `--base-lr` to a smaller value, e.g. 0.03

**Comment by sangeet2020** [comment]
Sure, will do. By the way, if MAX_DURATION=300, does this mean, the combined duration of all samples in one batch is 300 sec?
Also, Does icefall allows to directly control the batch size ? Like instead of setting MAX_DURATION to some value, I just use batch size to 2 or 4. 

thank you

**Comment by marcoyang1998** [comment]
> does this mean, the combined duration of all samples in one batch is 300 sec?

Yes, and if you are using 4 GPUs, the total duration of audio used for computing one update is equivalent to 4 * 300 secs.

> Does icefall allows to directly control the batch size ?

We normally use the total duration to control the batch size, which is commonly used for ASR. But you can control the batch size if you really want (see https://lhotse.readthedocs.io/en/latest/datasets.html?highlight=SimpleCutSampler#lhotse.dataset.sampling.SimpleCutSampler for an example usage), but this is usually not recommended.

**Comment by sangeet2020** [comment]
oh thanks a lot for clarifying.

**Comment by sangeet2020** [comment]
Hi @marcoyang1998 , 

I reduced the `--base-lr` to 0.03 and training seems progressing fine as expected.

Thank You.

**Comment by sangeet2020** [comment]
Hi @marcoyang1998 ,

I am investigating the tensorboard logs, and the current_simple_loss does not look alright.
![image](https://github.com/k2-fsa/icefall/assets/33633418/0a4c6b14-2581-412a-9670-a5294a53217a)

Its only 1 epoch as of now.

Is this expected?

Thank You

**Comment by marcoyang1998** [comment]
Yes, the simple_loss looks a bit strange. It seems to me that the grad_scale is still too small in your experiments. Could you please try `--base-lr 0.025` and see if the loss curve looks better?

**Comment by sangeet2020** [comment]
Hi @marcoyang1998 ,

thanks for your advice. here I attach a snippet of the training logs, and things are looking fine.

![image](https://github.com/k2-fsa/icefall/assets/33633418/1054a2c6-3c97-4070-9d94-24af0c1a2bbd)

thank you
