### ISSUE TITLE
error when prepare data for libricss

### ISSUE THREAD

**Issue by shanguanma** [k2-fsa/icefall#1488]
I follow the steps install icefall:
step0: install cuda and cudnn follow https://k2-fsa.github.io/k2/installation/cuda-cudnn.html

step1
```
conda create -n icefall python=3.8 -y
conda activate icefall
pip install torch==2.1.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118
wget https://huggingface.co/csukuangfj/k2/resolve/main/ubuntu-cuda/k2-1.24.4.dev20231221+cuda11.8.torch2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
 pip install k2-1.24.4.dev20231221+cuda11.8.torch2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

 pip install git+https://github.com/lhotse-speech/lhotse
cd icefall/
pip install -r ./requirements.txt
```

when   I run prepare.sh., the error is as follows:
```
2024-02-04 14:39:57 (slurm_script:45:main) dl_dir: /home/maduo/codebase/icefall/egs/libricss/SURT/download
2024-02-04 14:39:57 (slurm_script:88:main) Stage 1: Prepare LibriSpeech manifests
2024-02-04 14:39:57 (slurm_script:94:main) This recipe uses mfa alignment for trimming
^MDataset parts:   0%|          | 0/4 [00:00<?, ?it/s]2024-02-04 14:40:00,787 INFO [librispeech.py:168] Processing LibriSpeech subset: train-clean-100

^MDistributing tasks: 0it [00:00, ?it/s]^[[A
^MDistributing tasks: 10it [00:00, 98.65it/s]^[[A
^MDistributing tasks: 20it [00:00, 78.09it/s]^[[A2024-02-04 14:40:01,121 ERROR [utils.py:130] Failed to load FFmpeg 6 extension.
Traceback (most recent call last):
  File "/home/maduo/.conda/envs/icefall/lib/python3.8/site-packages/torchaudio/_extension/utils.py", line 128, in _find_ffmpeg_extension
    return _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "/home/maduo/.conda/envs/icefall/lib/python3.8/site-packages/torchaudio/_extension/utils.py", line 113, in _find_versionsed_ffmpeg_extension
    _try_access_avutil(ffmpeg_ver)
  File "/home/maduo/.conda/envs/icefall/lib/python3.8/site-packages/torchaudio/_extension/utils.py", line 89, in _try_access_avutil
    torchaudio.lib._torchaudio.find_avutil(libavutil)
RuntimeError: Error in dlopen: libavutil.so.58: cannot open shared object file: No such file or directory
Exception raised from DynamicLibrary at ../aten/src/ATen/DynamicLibrary.cpp:38 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7ff0f45a5617 in /home/maduo/.conda/envs/icefall/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x109413c (0x7ff09b6a813c in /home/maduo/.conda/envs/icefall/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #2: torchaudio::find_avutil(char const*) + 0x1a (0x7ff0335834ca in /home/maduo/.conda/envs/icefall/lib/python3.8/site-packages/torchaudio/lib/libtorchaudio.so)
frame #3: <unknown function> + 0x6f1a (0x7ff040008f1a in /home/maduo/.conda/envs/icefall/lib/python3.8/site-packages/torchaudio/lib/_torchaudio.so)
frame #4: <unknown function> + 0x1112e (0x7ff04001312e in /home/maduo/.conda/envs/icefall/lib/python3.8/site-packages/torchaudio/lib/_torchaudio.so)
frame #5: PyCFunction_Call + 0x52 (0x4f5572 in /home/maduo/.conda/envs/icefall/bin/python)
frame #6: _PyObject_MakeTpCall + 0x3bb (0x4e0e1b in /home/maduo/.conda/envs/icefall/bin/python)
frame #7: _PyEval_EvalFrameDefault + 0x4dfc (0x4dcf0c in /home/maduo/.conda/envs/icefall/bin/python)
frame #8: _PyFunction_Vectorcall + 0x106 (0x4e81a6 in /home/maduo/.conda/envs/icefall/bin/python)
frame #9: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /home/maduo/.conda/envs/icefall/bin/python)
frame #10: _PyFunction_Vectorcall + 0x106 (0x4e81a6 in /home/maduo/.conda/envs/icefall/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /home/maduo/.conda/envs/icefall/bin/python)
frame #12: _PyFunction_Vectorcall + 0x106 (0x4e81a6 in /home/maduo/.conda/envs/icefall/bin/python)
frame #13: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /home/maduo/.conda/envs/icefall/bin/python)
frame #14: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /home/maduo/.conda/envs/icefall/bin/python)
frame #15: _PyFunction_Vectorcall + 0x19c (0x4e823c in /home/maduo/.conda/envs/icefall/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x1153 (0x4d9263 in /home/maduo/.conda/envs/icefall/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /home/maduo/.conda/envs/icefall/bin/python)
frame #18: _PyFunction_Vectorcall + 0x19c (0x4e823c in /home/maduo/.conda/envs/icefall/bin/python)
frame #19: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /home/maduo/.conda/envs/icefall/bin/python)
frame #20: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /home/maduo/.conda/envs/icefall/bin/python)
frame #21: _PyFunction_Vectorcall + 0x19c (0x4e823c in /home/maduo/.conda/envs/icefall/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x399 (0x4d84a9 in /home/maduo/.conda/envs/icefall/bin/python)
frame #23: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /home/maduo/.conda/envs/icefall/bin/python)
frame #24: _PyFunction_Vectorcall + 0x19c (0x4e823c in /home/maduo/.conda/envs/icefall/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x1153 (0x4d9263 in /home/maduo/.conda/envs/icefall/bin/python)
frame #26: _PyEval_EvalCodeWithName + 0x2f1 (0x4d70d1 in /home/maduo/.conda/envs/icefall/bin/python)
frame #27: _PyFunction_Vectorcall + 0x19c (0x4e823c in /home/maduo/.conda/envs/icefall/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x1153 (0x4d9263 in /home/maduo/.conda/envs/icefall/bin/python)
frame #29: _PyFunction_Vectorcall + 0x106 (0x4e81a6 in /home/maduo/.conda/envs/icefall/bin/python)
frame #30: PyObject_Call + 0x24a (0x4f75ca in /home/maduo/.conda/envs/icefall/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x2073 (0x4da183 in /home/maduo/.conda/envs/icefall/bin/python)
frame #32: _PyFunction_Vectorcall + 0x106 (0x4e81a6 in /home/maduo/.conda/envs/icefall/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x6b2 (0x4d87c2 in /home/maduo/.conda/envs/icefall/bin/python)
```
install ffmpeg via `conda install -c conda-forge 'ffmpeg<7'`

I don't know how to process this error ?

**Comment by csukuangfj** [comment]
Are you using the latest lhotse?

Looks like the error is caused by torchaudio, which is invoking ffmpeg 5.

I think there is a way in lhotse to disable torchaudio.

**Comment by shanguanma** [comment]
> Are you using the latest lhotse?
> 
> Looks like the error is caused by torchaudio, which is invoking ffmpeg 5.
> 
> I think there is a way in lhotse to disable torchaudio.

Yes, I agree with you and I install latest lhotse via 
`pip install git+https://github.com/lhotse-speech/lhotse`

Now I am compiling ffmpeg5  to try to solve it via
 ```wget https://ffmpeg.org/releases/ffmpeg-5.1.4.tar.xz
tar xvf ffmpeg-5.1.4.tar.xz
cd ffmpeg-5.1.4
./configure --disable-x86asm  --prefix=$HOME/installed/ffmpeg5.1.4 && make && make install
```

**Comment by shanguanma** [comment]
> > Are you using the latest lhotse?
> > Looks like the error is caused by torchaudio, which is invoking ffmpeg 5.
> > I think there is a way in lhotse to disable torchaudio.
> 
> Yes, I agree with you and I install latest lhotse via `pip install git+https://github.com/lhotse-speech/lhotse`
> 
> Now I am compiling ffmpeg5 to try to solve it via
> 
> ```
> tar xvf ffmpeg-5.1.4.tar.xz
> cd ffmpeg-5.1.4
> ./configure --disable-x86asm  --prefix=$HOME/installed/ffmpeg5.1.4 && make && make install
> ```
@csukuangfj , thanks for your reply.
[UPDATA]
we should complile ffmpeg5 into into dynamic library, torchaudio search ffmpeg dynamic libray, however if we use the command 
```./configure --disable-x86asm  --prefix=$HOME/installed/ffmpeg5.1.4 && make && make install```,
 It  will compile ffmpeg into  static library default. We should use the below comand 
```./configure --enable-shared  --disable-x86asm  --prefix=$HOME/installed/ffmpeg5.1.4 && make && make install``` ,
 Finally I should be add ffmpeg to we environment (i.e. ~/.bashrc)follows the two command 
```
export PATH=/home/maduo/installed/ffmpeg5.1.4/bin:$PATH
export LD_LIBRARY_PATH=/home/maduo/installed/ffmpeg5.1.4/lib:$LD_LIBRARY_PATH
```
This way is working and can solve the above error.
