### ISSUE TITLE
Error in training conformer_ctc2 for librispeech WSASR

### ISSUE THREAD

**Issue by Rezakh20** [k2-fsa/icefall#1506]
Hello.
I want to train a ASR model for Librispeech dataset. I use recipes for training conformer_ctc2 in this link:

https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/WSASR/README.md

After preparation and making error making synthetic errors to the transcript, I use this command for training:
```
otc_lang_dir=data/lang_bpe_200
otc_token="<star>"
manifest_dir="data/manifests"
sub_er=0.17
ins_er=0.17
del_er=0.17
synthetic_train_manifest="librispeech_cuts_train-clean-100_${sub_er}_${ins_er}_${del_er}.jsonl.gz"
train_manifest="librispeech_cuts_train-clean-100.jsonl.gz"
exp_dir="conformer_ctc2/librispeech_training/exp"
allow_bypass_arc=true
allow_self_loop_arc=true
initial_bypass_weight=-19
initial_self_loop_weight=3.75
bypass_weight_decay=0.975
self_loop_weight_decay=0.999

show_alignment=true

export CUDA_VISIBLE_DEVICES="0"
./conformer_ctc2/train.py \
  --world-size 1 \
  --manifest-dir "${manifest_dir}" \
  --train-manifest "${synthetic_train_manifest}" \
  --exp-dir "${exp_dir}" \
  --lang-dir "${otc_lang_dir}" \
  --otc-token "${otc_token}" \
  --allow-bypass-arc "${allow_bypass_arc}" \
  --allow-self-loop-arc "${allow_self_loop_arc}" \
  --initial-bypass-weight "${initial_bypass_weight}" \
  --initial-self-loop-weight "${initial_self_loop_weight}" \
  --bypass-weight-decay "${bypass_weight_decay}" \
  --self-loop-weight-decay "${self_loop_weight_decay}" \
  --show-alignment "${show_alignment}"
```
**output log:**

```
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2024-02-19 18:04:42,665 INFO [train.py:881] Training started
2024-02-19 18:04:42,665 INFO [train.py:882] {'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 1, 'reset_interval': 200, 'valid_interval': 1600, 'alignment_interval': 25, 'feature_dim': 768, 'subsampling_factor': 2, 'encoder_dim': 512, 'nhead': 8, 'dim_feedforward': 2048, 'num_encoder_layers': 12, 'beam_size': 10, 'reduction': 'sum', 'use_double_scores': True, 'model_warm_step': 3000, 'env_info': {'k2-version': '1.24.4', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': 'f6919c0ddb311bea7b53a50f3afdcb3c18b8ccc8', 'k2-git-date': 'Sat Feb 10 09:23:09 2024', 'lhotse-version': '1.21.0', 'torch-version': '2.1.0+cu121', 'torch-cuda-available': True, 'torch-cuda-version': '12.1', 'python-version': '3.8', 'icefall-git-branch': None, 'icefall-git-sha1': None, 'icefall-git-date': None, 'icefall-path': '/home/reza.khodadadi/icefall', 'k2-path': '/usr/local/lib/python3.8/dist-packages/k2/__init__.py', 'lhotse-path': '/usr/local/lib/python3.8/dist-packages/lhotse/__init__.py', 'hostname': '038a368561ec', 'IP address': '172.17.0.3'}, 'world_size': 1, 'master_port': 12354, 'tensorboard': True, 'num_epochs': 20, 'start_epoch': 1, 'start_batch': 0, 'exp_dir': PosixPath('conformer_ctc2/librispeech_training/exp'), 'lang_dir': 'data/lang_bpe_200', 'initial_lr': 0.003, 'lr_batches': 5000, 'lr_epochs': 6, 'att_rate': 0.0, 'num_decoder_layers': 0, 'seed': 42, 'print_diagnostics': False, 'save_every_n': 8000, 'keep_last_k': 10, 'average_period': 100, 'use_fp16': False, 'otc_token': '▁<star>', 'allow_bypass_arc': True, 'allow_self_loop_arc': True, 'initial_bypass_weight': -19.0, 'initial_self_loop_weight': 3.75, 'bypass_weight_decay': 0.975, 'self_loop_weight_decay': 0.999, 'show_alignment': True, 'full_libri': False, 'mini_libri': False, 'manifest_dir': PosixPath('data/manifests'), 'max_duration': 200.0, 'bucketing_sampler': True, 'num_buckets': 30, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'shuffle': True, 'drop_last': True, 'return_cuts': True, 'num_workers': 2, 'input_strategy': 'PrecomputedFeatures', 'train_manifest': 'librispeech_cuts_train-clean-100_0.17_0.17_0.17.jsonl.gz'}
2024-02-19 18:04:42,825 INFO [train.py:908] About to create model
Conformer(
  (encoder_embed): Conv2dSubsampling2(
    (conv): Sequential(
      (0): ScaledConv2d(1, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ActivationBalancer()
      (2): DoubleSwish()
      (3): ScaledConv2d(8, 32, kernel_size=(3, 3), stride=(2, 2))
      (4): ActivationBalancer()
      (5): DoubleSwish()
      (6): ScaledConv2d(32, 128, kernel_size=(3, 3), stride=(1, 1))
      (7): ActivationBalancer()
      (8): DoubleSwish()
    )
    (out): ScaledLinear(in_features=48768, out_features=512, bias=True)
    (out_norm): BasicNorm()
    (out_balancer): ActivationBalancer()
  )
  (encoder_pos): RelPositionalEncoding(
    (dropout): Dropout(p=0.2, inplace=False)
  )
  (encoder): ConformerEncoder(
    (layers): ModuleList(
      (0-11): 12 x ConformerEncoderLayer(
        (self_attn): RelPositionMultiheadAttention(
          (in_proj): ScaledLinear(in_features=512, out_features=1536, bias=True)
          (out_proj): ScaledLinear(in_features=512, out_features=512, bias=True)
          (linear_pos): ScaledLinear(in_features=512, out_features=512, bias=False)
        )
        (feed_forward): Sequential(
          (0): ScaledLinear(in_features=512, out_features=2048, bias=True)
          (1): ActivationBalancer()
          (2): DoubleSwish()
          (3): Dropout(p=0.2, inplace=False)
          (4): ScaledLinear(in_features=2048, out_features=512, bias=True)
        )
        (feed_forward_macaron): Sequential(
          (0): ScaledLinear(in_features=512, out_features=2048, bias=True)
          (1): ActivationBalancer()
          (2): DoubleSwish()
          (3): Dropout(p=0.2, inplace=False)
          (4): ScaledLinear(in_features=2048, out_features=512, bias=True)
        )
        (conv_module): ConvolutionModule(
          (pointwise_conv1): ScaledConv1d(512, 1024, kernel_size=(1,), stride=(1,))
          (deriv_balancer1): ActivationBalancer()
          (depthwise_conv): ScaledConv1d(512, 512, kernel_size=(31,), stride=(1,), padding=(15,), groups=512)
          (deriv_balancer2): ActivationBalancer()
          (activation): DoubleSwish()
          (pointwise_conv2): ScaledConv1d(512, 512, kernel_size=(1,), stride=(1,))
        )
        (norm_final): BasicNorm()
        (balancer): ActivationBalancer()
        (dropout): Dropout(p=0.2, inplace=False)
      )
    )
  )
  (encoder_output_layer): Sequential(
    (0): Dropout(p=0.2, inplace=False)
    (1): ScaledLinear(in_features=512, out_features=200, bias=True)
  )
)
2024-02-19 18:04:43,798 INFO [train.py:922] Number of model parameters: 100922826
2024-02-19 18:04:44,793 INFO [asr_datamodule.py:323] About to get train-clean-100 cuts
2024-02-19 18:04:44,801 INFO [asr_datamodule.py:216] About to create train dataset
2024-02-19 18:04:44,801 INFO [asr_datamodule.py:224] Using DynamicBucketingSampler.
2024-02-19 18:04:45,264 INFO [asr_datamodule.py:239] About to create train dataloader
2024-02-19 18:04:45,265 INFO [asr_datamodule.py:345] About to get dev-clean cuts
2024-02-19 18:04:45,266 INFO [asr_datamodule.py:270] About to create dev dataset
2024-02-19 18:04:45,369 INFO [asr_datamodule.py:283] About to create dev dataloader
Traceback (most recent call last):
  File "./conformer_ctc2/train.py", line 1115, in <module>
    main()
  File "./conformer_ctc2/train.py", line 1108, in main
    run(rank=0, world_size=1, args=args)
  File "./conformer_ctc2/train.py", line 1015, in run
    train_one_epoch(
  File "./conformer_ctc2/train.py", line 753, in train_one_epoch
    loss, loss_info = compute_loss(
  File "./conformer_ctc2/train.py", line 563, in compute_loss
    nnet_output, encoder_memory, memory_mask = model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/reza.khodadadi/icefall/egs/librispeech/WSASR/conformer_ctc2/transformer.py", line 174, in forward
    encoder_memory, memory_key_padding_mask = self.run_encoder(
  File "/home/reza.khodadadi/icefall/egs/librispeech/WSASR/conformer_ctc2/conformer.py", line 135, in run_encoder
    x = self.encoder_embed(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/reza.khodadadi/icefall/egs/librispeech/WSASR/conformer_ctc2/subsampling.py", line 181, in forward
    x = self.out(x.transpose(1, 2).contiguous().view(b, t, c * f))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/reza.khodadadi/icefall/egs/librispeech/WSASR/conformer_ctc2/scaling.py", line 301, in forward
    return torch.nn.functional.linear(input, self.get_weight(), self.get_bias())
RuntimeError: mat1 and mat2 shapes cannot be multiplied (9612x4736 and 48768x512)
```
**My container specifications:**
```
python 3.8
torch==2.1.0+cu121
torchaudio==2.1.0+cu121
k2 version: 1.24.4
lhotse==1.21.0
icefall: clone from git(master branch) and install requierments
```
Thanks.

**Comment by csukuangfj** [comment]
@DongjiGao 

Could you have a look at this issue?

**Comment by Rezakh20** [comment]
@csukuangfj
@DongjiGao 

I appreciate your attention, could you please consider my issue?

**Comment by Rezakh20** [comment]
Problem solved by this [pull request](https://github.com/k2-fsa/icefall/pull/1528)

**Comment by DongjiGao** [comment]
Sorry for the slow response. The notification email was incorrectly tagged as trash and stored away. 
Yes, the problem is due to the different dimensions of acoustic features (I just set it to be 768). Thanks for the PR!
