### ISSUE TITLE
Getting error in prepare (compute fbank) stage.

### ISSUE THREAD

**Issue by sanjuktasr** [k2-fsa/icefall#1519]
RuntimeError: setStorage: sizes [1, 1, 400], strides [366, 160, 1], storage offset 0, and itemsize 4 requiring a storage size of 1600 are out of bounds for storage of size 1464
![Screenshot from 2024-02-27 10-48-34](https://github.com/k2-fsa/icefall/assets/124784140/f0ef9c0b-e2f0-4e55-8210-2905f1db1c17)

**Comment by danpovey** [comment]
You should figure out how to paste as text, and include more output, including any backtrace.

**Comment by sanjuktasr** [comment]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/workspace/lhotse/lhotse/cut/set.py", line 2057, in compute_and_store_features
    return CutSet.from_cuts(
  File "/workspace/lhotse/lhotse/cut/set.py", line 305, in from_cuts
    return CutSet(cuts=index_by_id_and_check(cuts))
  File "/workspace/lhotse/lhotse/utils.py", line 681, in index_by_id_and_check
    for m in manifests:
  File "/workspace/lhotse/lhotse/cut/set.py", line 2057, in <genexpr>
    return CutSet.from_cuts(
  File "/workspace/lhotse/lhotse/cut/set.py", line 2060, in <genexpr>
    null_result_on_audio_loading_error(
  File "/workspace/lhotse/lhotse/audio.py", line 2524, in wrapper
    return func(*args, **kwargs)
  File "/workspace/lhotse/lhotse/cut/data.py", line 467, in compute_and_store_features
    features_info = extractor.extract_from_samples_and_store(
  File "/workspace/lhotse/lhotse/features/base.py", line 245, in extract_from_samples_and_store
    feats = self.extract(samples=samples, sampling_rate=sampling_rate)
  File "/workspace/lhotse/lhotse/features/kaldi/extractors.py", line 109, in extract
    feats = self.extractor(samples.to(self.device))[0]
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/lhotse/lhotse/features/kaldi/layers.py", line 323, in forward
    x_strided, log_e = self.wav2win(x)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/lhotse/lhotse/features/kaldi/layers.py", line 195, in forward
    x_strided = _get_strided_batch(x, self._length, self._shift, self.snip_edges)
  File "/workspace/lhotse/lhotse/features/kaldi/layers.py", line 788, in _get_strided_batch
    return waveform.as_strided(sizes, strides)
RuntimeError: setStorage: sizes [1, 1, 400], strides [366, 160, 1], storage offset 0, and itemsize 4 requiring a storage size of 1600 are out of bounds for storage of size 1464
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/mihup/asr/zipformer/icefall/egs/librispeech/ASR/./local/compute_fbank_mihup.py", line 174, in <module>
    compute_fbank_mihup(
  File "/builds/mihup/asr/zipformer/icefall/egs/librispeech/ASR/./local/compute_fbank_mihup.py", line 157, in compute_fbank_mihup
    cut_set = cut_set.compute_and_store_features(
  File "/workspace/lhotse/lhotse/cut/set.py", line 2125, in compute_and_store_features
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/workspace/lhotse/lhotse/manipulation.py", line 30, in combine
    return reduce(add, manifests)
  File "/usr/local/lib/python3.9/dist-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/workspace/lhotse/lhotse/cut/set.py", line 2125, in <genexpr>
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/pytho
n3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
RuntimeError: setStorage: sizes [1, 1, 400], strides [366, 160, 1], storage offset 0, and itemsize 4 requiring a storage size of 1600 are out of bounds for storage of size 1464

**Comment by csukuangfj** [comment]
Which feature extractor are you using?
Do you think it fixes the issue when switching to another extractor?

```bash
File "/workspace/lhotse/lhotse/features/kaldi/layers.py", line 788, in _get_strided_batch
return waveform.as_strided(sizes, strides)
```

Could you place a breakpoint at line `788` and show the following output:
```
print(waveform.shape)
print(waveform.is_contiguous())
print(sizes)
print(strides)
```

**Comment by sanjuktasr** [comment]
@csukuangfj thanks for the solution.
