### ISSUE TITLE
Error happens with egs/librispeech/ASR/prepare_mmi.sh

### ISSUE THREAD

**Issue by kamo-naoyuki** [k2-fsa/icefall#1624]
I got following error when just running `./prepare_mmi.sh `

```
./prepare_mmi.sh --stage 6
2024-05-16 11:27:09 (prepare.sh:81:source) Running prepare.sh
2024-05-16 11:27:09 (prepare.sh:83:source) dl_dir: /data/store3/kamo/icefall/egs/librispeech/ASR/download
2024-05-16 11:27:09 (prepare.sh:86:source) Stage -1: Download LM
2024-05-16 11:27:09 (prepare.sh:95:source) Stage 0: Download data
2024-05-16 11:27:09 (prepare.sh:117:source) Stage 1: Prepare LibriSpeech manifest
2024-05-16 11:27:09 (prepare.sh:128:source) Stage 2: Prepare musan manifest
2024-05-16 11:27:09 (prepare.sh:139:source) Stage 3: Compute fbank for librispeech
2024-05-16 11:27:09 (prepare.sh:173:source) Stage 4: Compute fbank for musan
2024-05-16 11:27:09 (prepare.sh:182:source) Stage 5: Prepare BPE based lang
2024-05-16 11:27:09 (prepare.sh:210:source) Stage 6: Prepare phone based lang
2024-05-16 11:27:09 (prepare_mmi.sh:11:main) Running prepare_mmi.sh
2024-05-16 11:27:09 (prepare_mmi.sh:17:main) Stage 0: Prepare bigram token-level P for MMI training
Traceback (most recent call last):
  File "/data/store3/kamo/icefall/egs/librispeech/ASR/./local/convert_transcript_words_to_tokens.py", line 103, in <module>
    main()
  File "/data/store3/kamo/icefall/egs/librispeech/ASR/./local/convert_transcript_words_to_tokens.py", line 84, in main
    assert Path(args.lexicon).is_file()
AssertionError
./prepare_mmi.sh --stage 6
2024-05-16 11:27:09 (prepare.sh:81:source) Running prepare.sh
2024-05-16 11:27:09 (prepare.sh:83:source) dl_dir: /data/store3/kamo/icefall/egs/librispeech/ASR/download
2024-05-16 11:27:09 (prepare.sh:86:source) Stage -1: Download LM
2024-05-16 11:27:09 (prepare.sh:95:source) Stage 0: Download data
2024-05-16 11:27:09 (prepare.sh:117:source) Stage 1: Prepare LibriSpeech manifest
2024-05-16 11:27:09 (prepare.sh:128:source) Stage 2: Prepare musan manifest
2024-05-16 11:27:09 (prepare.sh:139:source) Stage 3: Compute fbank for librispeech
2024-05-16 11:27:09 (prepare.sh:173:source) Stage 4: Compute fbank for musan
2024-05-16 11:27:09 (prepare.sh:182:source) Stage 5: Prepare BPE based lang
2024-05-16 11:27:09 (prepare.sh:210:source) Stage 6: Prepare phone based lang
2024-05-16 11:27:09 (prepare_mmi.sh:11:main) Running prepare_mmi.sh
2024-05-16 11:27:09 (prepare_mmi.sh:17:main) Stage 0: Prepare bigram token-level P for MMI training
Traceback (most recent call last):
  File "/data/store3/kamo/icefall/egs/librispeech/ASR/./local/convert_transcript_words_to_tokens.py", line 103, in <module>
    main()
  File "/data/store3/kamo/icefall/egs/librispeech/ASR/./local/convert_transcript_words_to_tokens.py", line 84, in main
    assert Path(args.lexicon).is_file()
AssertionError
```

`data/lang_bpe_500/lexicon.txt` doesn't exist, but I have `data/lang_phone/lexicon.txt` instead.

Could you help me?

**Comment by csukuangfj** [comment]
@pkufool  Could you have a look? I think prepare_mmi.sh is refactored from the original prepare.sh.

**Comment by JinZr** [comment]
hi, i'm looking into it, will return to you by tomorrow

**Comment by JinZr** [comment]
dear naoyuki,

I ran the preparation script end to end and this PR should fix the issue.

The problem was introduced when we was trying to strip some unnecessary parts from the main prepare.sh script, the part for generating lexicon.txt was also stripped and moved to prepare_lm.sh. 

This PR should fix the problem, please check, thanks. 

https://github.com/k2-fsa/icefall/pull/1626￼
Fix an error occured during mmi preparation by JinZr · Pull Request #1626 · k2-fsa/icefall
github.com

best
jin
