### ISSUE TITLE
error in librispeech SSL pretrain.py

### ISSUE THREAD

**Issue by sanjuktasr** [k2-fsa/icefall#1703]
File "/NAS1/sanjukta_repo_falcon2/zip_exp_7/icefall/egs/librispeech/SSL/./zipformer/pretrain.py", line 1380, in <module>
    main()
  File "/NAS1/sanjukta_repo_falcon2/zip_exp_7/icefall/egs/librispeech/SSL/./zipformer/pretrain.py", line 1373, in main
    run(rank=0, world_size=1, args=args)
  File "/NAS1/sanjukta_repo_falcon2/zip_exp_7/icefall/egs/librispeech/SSL/./zipformer/pretrain.py", line 1261, in run
    train_one_epoch(
  File "/NAS1/sanjukta_repo_falcon2/zip_exp_7/icefall/egs/librispeech/SSL/./zipformer/pretrain.py", line 937, in train_one_epoch
    for sub_batch_idx, batch in enumerate(train_dl):
  File "/home/sanjukta/anaconda3/envs/ssl2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/sanjukta/anaconda3/envs/ssl2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/sanjukta/anaconda3/envs/ssl2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/sanjukta/anaconda3/envs/ssl2/lib/python3.9/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sanjukta/anaconda3/envs/ssl2/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/sanjukta/anaconda3/envs/ssl2/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 53, in fetch
    data = self.dataset[possibly_batched_index]
  File "/NAS1/sanjukta_repo_falcon2/zip_exp_7/icefall/egs/librispeech/SSL/zipformer/dataset.py", line 80, in __getitem__
    kmeans = [cut.custom["kmeans"] for cut in cuts]
  File "/NAS1/sanjukta_repo_falcon2/zip_exp_7/icefall/egs/librispeech/SSL/zipformer/dataset.py", line 80, in <listcomp>
    kmeans = [cut.custom["kmeans"] for cut in cuts]
KeyError: 'kmeans'

**Comment by yfyeung** [comment]
See https://github.com/k2-fsa/icefall/pull/1500
