### ISSUE TITLE
gigaspeech数据集下载成功，但解压缩失败

### ISSUE THREAD

**Issue by lmee** [k2-fsa/icefall#1723]
数据集已经下载了，但是解压缩老是失败，重试了三次，都是一样的结果，日志如下：请专家帮忙看看
Successfully verified md5 for /Users/lijieer/projects/github/icefall/egs/gigaspeech/ASR/download/GigaSpeech/GigaSpeech.json.gz.aes
Traceback (most recent call last):
  File "/opt/anaconda3/bin/lhotse", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/lhotse/bin/modes/recipes/gigaspeech.py", line 63, in gigaspeech
    download_gigaspeech(password, target_dir, dataset_parts=subset, host=host)
  File "/opt/anaconda3/lib/python3.11/site-packages/lhotse/recipes/gigaspeech.py", line 53, in download_gigaspeech
    gigaspeech.download(password, "{" + part + "}", host=host)
  File "/opt/anaconda3/lib/python3.11/site-packages/speechcolab/datasets/gigaspeech.py", line 91, in download
    prepare_objects_from_release('metadata')
  File "/opt/anaconda3/lib/python3.11/site-packages/speechcolab/datasets/gigaspeech.py", line 87, in prepare_objects_from_release
    self.download_and_process_object_from_release(aes_list[category][path], path)
  File "/opt/anaconda3/lib/python3.11/site-packages/speechcolab/datasets/gigaspeech.py", line 167, in download_and_process_object_from_release
    f_out.write(z.decompress(chunk))
                ^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: incorrect header check

**Comment by JinZr** [comment]
出现这个问题一般说明你的下载没有成功

**Comment by ai4in** [comment]
解决方案：https://github.com/SpeechColab/GigaSpeech/issues/93
