### ISSUE TITLE
Issue with LODR for RNN Transducer.

### ISSUE THREAD

**Issue by sangeet2020** [k2-fsa/icefall#1771]
Hi,

I am struggling with using LODR for decoding using the librispeech zipformer recipe. When I follow the tutorial here, and use the pre-trained models from [Zengwei/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29](https://huggingface.co/Zengwei/icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/tree/main/data/lang_bpe_500) and [marcoyang/librispeech_bigram](https://huggingface.co/marcoyang/librispeech_bigram/tree/main) everything works fine.

However, when I train my own bigram model basically `2gram.arpa` and `2gram.fst.txt`, and then perform the LODR decoding I run into following error:
```
Could not load symbol cublasGetSmCountTarget from libcublas.so.11. Error: /usr/local/cuda-11.2/lib64/libcublas.so.11: undefined symbol: cublasGetSmCountTarget
Traceback (most recent call last):
  File "/mnt/local/sangeet/workncode/k2-fsa/icefall/egs/Eng/ASR/./zipformer/decode.py", line 1104, in <module>
    main()
  File "/mnt/users/sagarst/envs/k2-gpu/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/local/sangeet/workncode/k2-fsa/icefall/egs/Eng/ASR/./zipformer/decode.py", line 1081, in main
    results_dict = decode_dataset(
                   ^^^^^^^^^^^^^^^
  File "/mnt/local/sangeet/workncode/k2-fsa/icefall/egs/Eng/ASR/./zipformer/decode.py", line 682, in decode_dataset
    hyps_dict = decode_one_batch(
                ^^^^^^^^^^^^^^^^^
  File "/mnt/local/sangeet/workncode/k2-fsa/icefall/egs/Eng/ASR/./zipformer/decode.py", line 537, in decode_one_batch
    hyp_tokens = modified_beam_search_LODR(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/local/sangeet/workncode/k2-fsa/icefall/egs/Eng/ASR/zipformer/beam_search.py", line 2623, in modified_beam_search_LODR
    assert current_ngram_score <= 0.0, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: (-inf, -inf)
```

The fun part is, when I replace the `2gram.arpa` and `2gram.fst.txt` model trained by me to the one available here [marcoyang/librispeech_bigram](https://huggingface.co/marcoyang/librispeech_bigram/tree/main) (AM, bpe, etc remains same) it just works like a charm, and I even see slight improvement in the WER.

I believe it there is some error in the way I am training these bigram models.

 I read @nshmyrev  's comment here https://github.com/k2-fsa/icefall/issues/749#issuecomment-1636792938 , but somehow my in my arpa file, the unigram size is always 499.
any guidance towards this would be helpful. thanks

**Comment by sangeet2020** [comment]
Okay, so I finally figured out.  I had two mistakes (1) While training bigram model, 
```bash
python3 -m kaldilm \
          --read-symbol-table="$lang_dir/tokens.txt" \
          --disambig-symbol='#0' \
          --max-order=${ngram} \
          $lang_dir/${ngram}gram.arpa > $lang_dir/${ngram}gram.fst.txt
```
I was using the `words.txt` in ` --read-symbol-table` instead of `tokens.txt`

(2) In my text transcript, I had inserted a custom token `<UNK>` token that basically represents all sorts of music, breathing, hesitation noises. However, this created conflict with the unk-id of SPM `<unk>`. So replaced my custom token with `<NOISE>`.
@nshmyrev advice indeed help, many thanks to him. It should be made sure that there are exactly 500 unigrams in 2gram.arpa and that it also includes `<unk>` token.
