### ISSUE TITLE
checkpoint.py:113: FutureWarning: You are using `torch.load` with `weights_only=False`

### ISSUE THREAD

**Issue by mablue** [k2-fsa/icefall#1822]
after making my pt with this coomand:
` ./vits/train.py --num-epochs 1 --model-type low --max-duration 40 `
I try to run this command: 
` ./vits/infer.py     --epoch 1     --exp-dir vits/exp     --tokens data/tokens.txt     --max-duration 40 `

and got this error message
```
(.env) mab@mab:~/dev/pashtoo/icefall/egs/ljspeech/TTS$ export CUDA_VISIBLE_DEVICES="0"
(.env) mab@mab:~/dev/pashtoo/icefall/egs/ljspeech/TTS$ ./vits/infer.py \
    --epoch 1 \
    --exp-dir vits/exp \
    --tokens data/tokens.txt \
    --max-duration 40
2024-11-30 21:28:48,220 INFO [infer.py:210] Infer started
2024-11-30 21:28:48,221 INFO [infer.py:220] Device: cuda:0
2024-11-30 21:28:48,221 INFO [infer.py:221] {
  "batch_idx_train": -1,
  "best_train_epoch": -1,
  "best_train_loss": Infinity,
  "best_valid_epoch": -1,
  "best_valid_loss": Infinity,
  "blank_id": 0,
  "bucketing_sampler": true,
  "drop_last": true,
  "env_info": {
    "IP address": "127.0.1.1",
    "hostname": "mab",
    "icefall-git-branch": "master",
    "icefall-git-date": "Fri Nov 29 12:06:02 2024",
    "icefall-git-sha1": "a1ade8ec-dirty",
    "icefall-path": "/home/mab/dev/pashtoo/icefall",
    "k2-build-type": "Release",
    "k2-git-date": "Wed Nov 27 10:34:15 2024",
    "k2-git-sha1": "65713bc93140d63cfec3ffeec17d7f603fb74a71",
    "k2-path": "/home/mab/dev/pashtoo/.env/lib/python3.11/site-packages/k2/__init__.py",
    "k2-version": "1.24.4",
    "k2-with-cuda": true,
    "lhotse-path": "/home/mab/dev/pashtoo/.env/lib/python3.11/site-packages/lhotse/__init__.py",
    "lhotse-version": "1.28.0.dev+git.b8fcd3a.clean",
    "python-version": "3.11",
    "torch-cuda-available": true,
    "torch-cuda-version": "11.8",
    "torch-version": "2.5.1+cu118"
  },
  "epoch": 1,
  "exp_dir": "vits/exp",
  "feature_dim": 513,
  "frame_length": 1024,
  "frame_shift": 256,
  "input_strategy": "PrecomputedFeatures",
  "lambda_adv": 1.0,
  "lambda_dur": 1.0,
  "lambda_feat_match": 2.0,
  "lambda_kl": 1.0,
  "lambda_mel": 45.0,
  "log_interval": 50,
  "manifest_dir": "data/spectrogram",
  "max_duration": 40,
  "model_type": "high",
  "n_mels": 80,
  "num_buckets": 30,
  "num_workers": 2,
  "on_the_fly_feats": false,
  "res_dir": "vits/exp/infer/epoch-1",
  "return_cuts": false,
  "sampling_rate": 22050,
  "save_wav_dir": "vits/exp/infer/epoch-1/wav",
  "shuffle": true,
  "suffix": "epoch-1",
  "tokens": "data/tokens.txt",
  "valid_interval": 200,
  "vocab_size": 157
}
2024-11-30 21:28:48,221 INFO [infer.py:223] About to create model
/home/mab/dev/pashtoo/.env/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
2024-11-30 21:28:49,169 INFO [checkpoint.py:112] Loading checkpoint from vits/exp/epoch-1.pt
/home/mab/dev/pashtoo/icefall/icefall/checkpoint.py:113: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, map_location="cpu")
Traceback (most recent call last):
  File "/home/mab/dev/pashtoo/icefall/egs/ljspeech/TTS/./vits/infer.py", line 256, in <module>
    main()
  File "/home/mab/dev/pashtoo/.env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mab/dev/pashtoo/icefall/egs/ljspeech/TTS/./vits/infer.py", line 226, in main
    load_checkpoint(f"{params.exp_dir}/epoch-{params.epoch}.pt", model)
  File "/home/mab/dev/pashtoo/icefall/icefall/checkpoint.py", line 126, in load_checkpoint
    model.load_state_dict(checkpoint["model"], strict=strict)
  File "/home/mab/dev/pashtoo/.env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for VITS:
	size mismatch for generator.text_encoder.emb.weight: copying a param with shape torch.Size([157, 96]) from checkpoint, the shape in current model is torch.Size([157, 192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.feed_forward_macaron.0.weight: copying a param with shape torch.Size([384, 96]) from checkpoint, the shape in current model is torch.Size([768, 192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.feed_forward_macaron.0.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.feed_forward_macaron.3.weight: copying a param with shape torch.Size([96, 384]) from checkpoint, the shape in current model is torch.Size([192, 768]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.feed_forward_macaron.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.self_attn.pos_bias_u: copying a param with shape torch.Size([2, 48]) from checkpoint, the shape in current model is torch.Size([2, 96]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.self_attn.pos_bias_v: copying a param with shape torch.Size([2, 48]) from checkpoint, the shape in current model is torch.Size([2, 96]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.self_attn.in_proj.weight: copying a param with shape torch.Size([288, 96]) from checkpoint, the shape in current model is torch.Size([576, 192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.self_attn.in_proj.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([576]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.self_attn.out_proj.weight: copying a param with shape torch.Size([96, 96]) from checkpoint, the shape in current model is torch.Size([192, 192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.self_attn.out_proj.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.self_attn.linear_pos.weight: copying a param with shape torch.Size([96, 96]) from checkpoint, the shape in current model is torch.Size([192, 192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.conv_module.pointwise_conv1.weight: copying a param with shape torch.Size([192, 96, 1]) from checkpoint, the shape in current model is torch.Size([384, 192, 1]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.conv_module.pointwise_conv1.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.conv_module.depthwise_conv.weight: copying a param with shape torch.Size([96, 1, 3]) from checkpoint, the shape in current model is torch.Size([192, 1, 5]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.conv_module.depthwise_conv.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.conv_module.norm.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.conv_module.norm.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.conv_module.pointwise_conv2.weight: copying a param with shape torch.Size([96, 96, 1]) from checkpoint, the shape in current model is torch.Size([192, 192, 1]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.conv_module.pointwise_conv2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.feed_forward.0.weight: copying a param with shape torch.Size([384, 96]) from checkpoint, the shape in current model is torch.Size([768, 192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.feed_forward.0.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.feed_forward.3.weight: copying a param with shape torch.Size([96, 384]) from checkpoint, the shape in current model is torch.Size([192, 768]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.feed_forward.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_ff_macaron.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_ff_macaron.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_mha.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_mha.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_conv.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_conv.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_final.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_final.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_ff.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.0.norm_ff.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.1.feed_forward_macaron.0.weight: copying a param with shape torch.Size([384, 96]) from checkpoint, the shape in current model is torch.Size([768, 192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.1.feed_forward_macaron.0.bias: copying a param with shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.1.feed_forward_macaron.3.weight: copying a param with shape torch.Size([96, 384]) from checkpoint, the shape in current model is torch.Size([192, 768]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.1.feed_forward_macaron.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.1.self_attn.pos_bias_u: copying a param with shape torch.Size([2, 48]) from checkpoint, the shape in current model is torch.Size([2, 96]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.1.self_attn.pos_bias_v: copying a param with shape torch.Size([2, 48]) from checkpoint, the shape in current model is torch.Size([2, 96]).
	size mismatch for generator.text_encoder.encoder.encoder.layers.1.self_attn.in_proj.weight: copying a param with shape torch.Size([288, 96]) from checkpoint, the shape in current model is torch.Size([576, 192]).
.
.
.
	size mismatch for generator.duration_predictor.post_flows.7.dds_conv.convs.2.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.duration_predictor.post_flows.7.dds_conv.convs.2.7.weight: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.duration_predictor.post_flows.7.dds_conv.convs.2.7.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for generator.duration_predictor.post_flows.7.proj.weight: copying a param with shape torch.Size([29, 96, 1]) from checkpoint, the shape in current model is torch.Size([29, 192, 1]).
(.env) mab@mab:~/dev/pashtoo/icefall/egs/ljspeech/TTS$ 


```

**Comment by JinZr** [comment]
hi, you used the "low" model config during training, so you'll have to also explicitly specify that during inference. 

hope this would help.
