### ISSUE TITLE
Error when Return None as the resulting lattice is too large

### ISSUE THREAD

**Issue by wgb14** [k2-fsa/icefall#212]
posted decoding log here:
```
2022-02-10 22:12:52,350 INFO [decode.py:734] num_arcs before pruning: 465314
2022-02-10 22:12:52,350 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:52,465 INFO [decode.py:747] num_arcs after pruning: 67064
2022-02-10 22:12:52,763 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:52,763 INFO [decode.py:734] num_arcs before pruning: 67064
2022-02-10 22:12:52,764 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:52,896 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:53,247 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:53,247 INFO [decode.py:734] num_arcs before pruning: 67030
2022-02-10 22:12:53,247 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:53,399 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:53,724 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:53,724 INFO [decode.py:734] num_arcs before pruning: 67030
2022-02-10 22:12:53,724 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:53,857 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:54,210 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:54,210 INFO [decode.py:734] num_arcs before pruning: 67030
2022-02-10 22:12:54,210 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:54,362 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:54,684 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:54,684 INFO [decode.py:734] num_arcs before pruning: 67030
2022-02-10 22:12:54,684 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:54,817 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:55,171 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:55,171 INFO [decode.py:734] num_arcs before pruning: 67030
2022-02-10 22:12:55,171 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:55,323 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:55,650 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:55,650 INFO [decode.py:734] num_arcs before pruning: 67030
2022-02-10 22:12:55,650 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:55,783 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:56,136 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:56,136 INFO [decode.py:734] num_arcs before pruning: 67030
2022-02-10 22:12:56,136 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:56,288 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:56,613 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:56,613 INFO [decode.py:734] num_arcs before pruning: 67030
2022-02-10 22:12:56,613 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:56,745 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:57,092 INFO [decode.py:733] Caught exception:
CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

2022-02-10 22:12:57,092 INFO [decode.py:734] num_arcs before pruning: 67030
2022-02-10 22:12:57,092 INFO [decode.py:737] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
2022-02-10 22:12:57,245 INFO [decode.py:747] num_arcs after pruning: 67030
2022-02-10 22:12:57,264 INFO [decode.py:751] Return None as the resulting lattice is too large
Traceback (most recent call last):
  File "conformer_ctc/decode.py", line 701, in <module>
    main()
  File "/home-2/gwang50/miniconda3/envs/k2/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "conformer_ctc/decode.py", line 677, in main
    results_dict = decode_dataset(
  File "conformer_ctc/decode.py", line 442, in decode_dataset
    hyps_dict = decode_one_batch(
  File "conformer_ctc/decode.py", line 363, in decode_one_batch
    best_path_dict = rescore_with_attention_decoder(
  File "/home-net/home-2/gwang50/code/icefall/icefall/decode.py", line 820, in rescore_with_attention_decoder
    nbest = Nbest.from_lattice(
  File "/home-net/home-2/gwang50/code/icefall/icefall/decode.py", line 209, in from_lattice
    saved_scores = lattice.scores.clone()
AttributeError: 'NoneType' object has no attribute 'scores'
```
Seems that the pruning here:
https://github.com/k2-fsa/icefall/blob/70a3c56a18d726d0a04c2774247e132e4464f54f/icefall/decode.py#L746
for 10 times does not always work, although it works for most of other utterances.
How about gradually increasing threshold (like `[1e-10, 1e-9, 1e-8...]`)?

**Comment by csukuangfj** [comment]
> How about gradually increasing threshold (like [1e-10, 1e-9, 1e-8...])?

The threshold `1e-9` is chosen without tuning. 

Yes, you can do that and a PR is welcome.

**Comment by danpovey** [comment]
My feeling is 1e-9 may be unnecessarily small and could lead to problems with roundoff... perhaps something like 0.1 would be sufficient to prevent OOM, or even 1, and then we try successively smaller ones if we get OOM again.

**Comment by wgb14** [comment]
I tested `prune_th_list = [1e-10, 1e-9, 1e-8, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1.0]` (max_loop_count is 10), and this works well.
> My feeling is 1e-9 may be unnecessarily small and could lead to problems with roundoff... perhaps something like 0.1 would be sufficient to prevent OOM, or even 1, and then we try successively smaller ones if we get OOM again.

Yes, you are right. When I tested a more conservative list `prune_th_list = [1e-10, 5e-10, 1e-9, 5e-9, 1e-8, 5e-8, 1e-7, 5e-7, 1e-6, 5e-6, 1e-5]`, I got the same error. So maybe in the case where 1e-9 doesn't work, then other small ones wouldn't work either. Although 1e-9 works in most cases.

**Comment by danpovey** [comment]
I just think it makes more sense to start from larger and go smaller, since the larger numbers are less-aggressive pruning, and presumably less harmful to downstream tasks.

**Comment by wgb14** [comment]
> I just think it makes more sense to start from larger and go smaller, since the larger numbers are less-aggressive pruning, and presumably less harmful to downstream tasks.

Sorry, I would have thought this was probability-based pruning, and a smaller threshold would prune fewer arcs.

**Comment by danpovey** [comment]
No, it's an absolute threshold on scores.

**Comment by wgb14** [comment]
I just did a test on this function `inv_lattice = k2.prune_on_arc_post(inv_lattice, th, True)`
`th=1e-10`
```
INFO [decode.py:739] num_arcs before pruning: 291121
INFO [decode.py:742] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
INFO [decode.py:753] num_arcs after pruning: 1642
```
`th=1e-5`
```
INFO [decode.py:739] num_arcs before pruning: 291121
INFO [decode.py:742] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
INFO [decode.py:753] num_arcs after pruning: 928
```
and `th=1e-1`
```
INFO [decode.py:739] num_arcs before pruning: 291121
INFO [decode.py:742] This OOM is not an error. You can ignore it. If your model does not converge well, or --max-duration is too large, or the input sound file is difficult to decode, you will meet this exception.
INFO [decode.py:753] num_arcs after pruning: 445
```
Seems that more arcs were kept when I set a smaller threshold. Do you have any insight on this? Is this the expected behavior?

**Comment by csukuangfj** [comment]
Yes, a larger threshold leads to more arcs being removed.

https://github.com/k2-fsa/k2/blob/f4fefe4882bc0ae59af951da3f47335d5495ef71/k2/csrc/fsa_utils.cu#L2688
```cpp
  FloatType threshold_log_prob = std::log(threshold_prob);
```

https://github.com/k2-fsa/k2/blob/f4fefe4882bc0ae59af951da3f47335d5495ef71/k2/csrc/fsa_utils.cu#L2698-L2705
```cpp
        if (arc_post_data[i] < threshold_log_prob) {
          // The posterior of this arc is below the threshold,
          // so remove it.
          keep = 0;
        } else {
          keep = 1;
        }
```

**Comment by csukuangfj** [comment]
Closing via #214
