### ISSUE TITLE
Long audio feature extraction

### ISSUE THREAD

**Issue by mesut92** [k2-fsa/icefall#249]
Hi 
I am trying to train with my own dataset. ıt consists of 4-5 hours sessions. During feature extraction it gives errors as below. I assume it is caused by long duration. Do you have any suggestion about that?

I have 32 GB memory.

```
Extracting and storing features (chunks progress):   0%|                                                                                                                      | 0/8 [01:38<?, ?it/s]
Traceback (most recent call last):
  File "./local/compute_fbank_tbmm.py", line 95, in <module>
    compute_fbank_librispeech()
  File "./local/compute_fbank_tbmm.py", line 77, in compute_fbank_librispeech
    cut_set = cut_set.compute_and_store_features(
  File "/opt/conda/lib/python3.8/site-packages/lhotse/cut.py", line 4462, in compute_and_store_features
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/opt/conda/lib/python3.8/site-packages/lhotse/manipulation.py", line 30, in combine
    return reduce(add, manifests)
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.8/site-packages/lhotse/cut.py", line 4462, in <genexpr>
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

Thanks
Mesut

**Comment by pzelasko** [comment]
Try using KaldifeatFbank instead of Fbank in this script -- it supports arbitrarily long recordings without memory issues.

**Comment by mesut92** [comment]
thanks
