### ISSUE TITLE
failed to train conformer ctc for aishell

### ISSUE THREAD

**Issue by ahban** [k2-fsa/icefall#297]
hi. 
I am trying to reproduce the result of conformed CTC for Aishell. 
However, after several versions try, I still cannot start the train.py correctly.
For now, I get the following errors
```
Traceback (most recent call last):
  File "conformer_ctc/train.py", line 687, in <module>
    main()
  File "conformer_ctc/train.py", line 678, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/home/banzhihua/soft/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/banzhihua/soft/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/banzhihua/soft/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/banzhihua/soft/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/mnt/diskdata/banzhihua/devel/icefall/egs/aishell/ASR/conformer_ctc/train.py", line 643, in run
    train_one_epoch(
  File "/mnt/diskdata/banzhihua/devel/icefall/egs/aishell/ASR/conformer_ctc/train.py", line 491, in train_one_epoch
    loss, loss_info = compute_loss(
  File "/mnt/diskdata/banzhihua/devel/icefall/egs/aishell/ASR/conformer_ctc/train.py", line 388, in compute_loss
    att_loss = mmodel.decoder_forward(
  File "/mnt/diskdata/banzhihua/devel/icefall/egs/aishell/ASR/conformer_ctc/transformer.py", line 306, in decoder_forward
    decoder_loss = self.decoder_criterion(pred_pad, ys_out_pad)
  File "/home/banzhihua/soft/anaconda3/envs/k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/diskdata/banzhihua/devel/icefall/egs/aishell/ASR/conformer_ctc/label_smoothing.py", line 81, in forward
    true_dist = torch.nn.functional.one_hot(
RuntimeError: Class values must be non-negative.

```

I am not very familiar with Python and PyTorch. Hope you guys could help me a bit.

I list the packages I am using.
```
$ python3 -m k2.version 
Collecting environment information...

k2 version: 1.14
Build type: Release
Git SHA1: 6833270cb228aba7bf9681fccd41e2b52f7d984c
Git date: Wed Mar 16 03:16:05 2022
Cuda used to build k2: 11.1
cuDNN used to build k2: 8.0.4
Python version used to build k2: 3.8
OS used to build k2: Ubuntu 18.04.6 LTS
CMake version: 3.18.4
GCC version: 7.5.0
CMAKE_CUDA_FLAGS:  --expt-extended-lambda -gencode arch=compute_35,code=sm_35 --expt-extended-lambda -gencode arch=compute_50,code=sm_50 --expt-extended-lambda -gencode arch=compute_60,code=sm_60 --expt-extended-lambda -gencode arch=compute_61,code=sm_61 --expt-extended-lambda -gencode arch=compute_70,code=sm_70 --expt-extended-lambda -gencode arch=compute_75,code=sm_75 --expt-extended-lambda -gencode arch=compute_80,code=sm_80 --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall --compiler-options -Wno-unknown-pragmas --compiler-options -Wno-strict-overflow
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-strict-overflow
PyTorch version used to build k2: 1.8.1
PyTorch is using Cuda: 11.1
NVTX enabled: True
With CUDA: True
Disable debug: True
Sync kernels : False
Disable checks: False

```

lhotse = 1.0.0

```
git commit for icefall : ceeb95bcb8c12e5047be7f12440296bd9532c0e3

```

thanks in advance.

**Comment by danpovey** [comment]
You can run the python command with pdb, by adding "-m pdb" after python3.
Type "r" (for run) when you see the prompt.
You may have to "c" when it first fails.. eventually you may be able to print out local variables and write "list" to list the source.
Looks to me like it could be an error in your version of torch.

**Comment by ahban** [comment]
> You can run the python command with pdb, by adding "-m pdb" after python3. Type "r" (for run) when you see the prompt. You may have to "c" when it first fails.. eventually you may be able to print out local variables and write "list" to list the source. Looks to me like it could be an error in your version of torch.

I will try this after finish k2 1.13 done trainning.

**Comment by csukuangfj** [comment]
I think this issue is the same as the one posted in https://github.com/k2-fsa/icefall/issues/240

Using the suggestions from https://github.com/k2-fsa/icefall/issues/240#issuecomment-1065402350
should fix it.

**Comment by csukuangfj** [comment]
> @csukuangfj do we check that the PyTorch version matches the one used to build k2? I notice it prints out the Torch version used to build k2 but not the one that is being used.

No, there are no such checks. If they are not the same, the process should abort on start saying that some symbols cannot be found. 

I am wondering if it is possible to check that. If I remember correctly, it aborts when you run `import k2` for mis-matched PyTorch versions.

**Comment by csukuangfj** [comment]
Fixed by https://github.com/k2-fsa/icefall/pull/300

Feel free to re-open it if the issue still exists.
