### ISSUE TITLE
An error of training transducer_stateless_modified in aishell

### ISSUE THREAD

**Issue by shanguanma** [k2-fsa/icefall#374]
I use newest k2-fsa , lhoste and icefall, I run transducer_stateless_modified in aishell. I find an error when it is the training stage.
The log is as follows:
```
$ gdb --args python3 ./transducer_stateless_modified/train.py  --world-size 4 --exp-dir exp/transducer_stateless_modified --num-epochs 90  --start-epoch 0 --max-duration 100 --lr-factor 2.0 --context-size 2   --modified-transducer-prob 0.25

Traceback (most recent call last):
  File "./transducer_stateless_modified/train.py", line 751, in <module>
    main()
  File "./transducer_stateless_modified/train.py", line 742, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/mnt/4T_b/md/k2_recipe/icefall/egs/aishell/ASR/transducer_stateless_modified/train.py", line 645, in run
    scan_pessimistic_batches_for_oom(
  File "/mnt/4T_b/md/k2_recipe/icefall/egs/aishell/ASR/transducer_stateless_modified/train.py", line 710, in scan_pessimistic_batches_for_oom
    loss, _ = compute_loss(
  File "/mnt/4T_b/md/k2_recipe/icefall/egs/aishell/ASR/transducer_stateless_modified/train.py", line 404, in compute_loss
    loss = model(
  File "/opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/4T_b/md/k2_recipe/icefall/egs/aishell/ASR/transducer_stateless_modified/model.py", line 132, in forward
    loss = optimized_transducer.transducer_loss(
  File "/opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/optimized_transducer/transducer_loss.py", line 433, in transducer_loss
    return TransducerLossFunction.apply(
  File "/opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/optimized_transducer/transducer_loss.py", line 135, in forward
    scores, grad = _optimized_transducer.compute_transducer_loss(
RuntimeError: CUDA error: invalid device ordinal
Exception raised from scan_cub at /opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/ScanKernels.cu:498 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f4d47bac2f2 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f4d47ba967b in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: void at::native::scan_cub<int, std::plus<int> >(at::Tensor const&, at::Tensor&, int, std::plus<int>) + 0x930 (0x7f4d52795ce0 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #3: void at::native::scan_dim<int, std::plus<int> >(at::Tensor const&, at::Tensor&, long, int, std::plus<int>) + 0x1b4 (0x7f4d52796304 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #4: at::native::_cumsum_out_cuda(at::Tensor&, at::Tensor const&, long) + 0x2f7 (0x7f4d52757e97 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #5: at::native::_cumsum_cuda(at::Tensor const&, long) + 0x3c (0x7f4d5275811c in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #6: <unknown function> + 0x95ccc8 (0x7f4d51116cc8 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #7: <unknown function> + 0x95cd0f (0x7f4d51116d0f in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #8: at::Tensor c10::Dispatcher::call<at::Tensor, at::Tensor const&, long>(c10::TypedOperatorHandle<at::Tensor (at::Tensor const&, long)> const&, at::Tensor const&, long) const + 0xda (0x7f4d4939f56a in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: at::_cumsum(at::Tensor const&, long) + 0x5a (0x7f4d4920d9aa in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #10: at::native::cumsum(at::Tensor const&, long, c10::optional<c10::ScalarType>) + 0x72 (0x7f4d48e6a462 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x14d18c0 (0x7f4d494ec8c0 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x14d1912 (0x7f4d494ec912 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x138eee4 (0x7f4d493a9ee4 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #14: at::cumsum(at::Tensor const&, long, c10::optional<c10::ScalarType>) + 0x65 (0x7f4d492433f5 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x29d0d95 (0x7f4d4a9ebd95 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x29d1042 (0x7f4d4a9ec042 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x138eee4 (0x7f4d493a9ee4 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #18: at::cumsum(at::Tensor const&, long, c10::optional<c10::ScalarType>) + 0x65 (0x7f4d492433f5 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #19: ot::ComputeTransducerLossCuda(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, int, bool, bool) + 0x1ac (0x7f4c2566b10c in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/liboptimized_transducer_core_cuda.so)
frame #20: ot::ComputeTransducerLoss(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, int, bool, bool) + 0xf00 (0x7f4cab5bf0d0 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/liboptimized_transducer_core.so)
frame #21: <unknown function> + 0x963f (0x7f4cab5d763f in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/_optimized_transducer.cpython-38-x86_64-linux-gnu.so)
frame #22: <unknown function> + 0xcb60 (0x7f4cab5dab60 in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/_optimized_transducer.cpython-38-x86_64-linux-gnu.so)
frame #23: <unknown function> + 0x13c7ae (0x56342a2497ae in /opt/conda/envs/k2-fsa1/bin/python3)
frame #24: _PyObject_MakeTpCall + 0x3bf (0x56342a23e25f in /opt/conda/envs/k2-fsa1/bin/python3)
frame #25: _PyEval_EvalFrameDefault + 0x540a (0x56342a2e7e5a in /opt/conda/envs/k2-fsa1/bin/python3)
frame #26: _PyEval_EvalCodeWithName + 0x260 (0x56342a2d91f0 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #27: _PyFunction_Vectorcall + 0x534 (0x56342a2da754 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #28: PyObject_Call + 0x7d (0x56342a24457d in /opt/conda/envs/k2-fsa1/bin/python3)
frame #29: THPFunction_apply(_object*, _object*) + 0x8fd (0x7f4d9eb0341d in /opt/conda/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #30: <unknown function> + 0x13c83d (0x56342a24983d in /opt/conda/envs/k2-fsa1/bin/python3)
frame #31: _PyObject_MakeTpCall + 0x3bf (0x56342a23e25f in /opt/conda/envs/k2-fsa1/bin/python3)
frame #32: _PyEval_EvalFrameDefault + 0x5437 (0x56342a2e7e87 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #33: _PyEval_EvalCodeWithName + 0x260 (0x56342a2d91f0 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #34: _PyFunction_Vectorcall + 0x594 (0x56342a2da7b4 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #35: _PyEval_EvalFrameDefault + 0x1517 (0x56342a2e3f67 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #36: _PyEval_EvalCodeWithName + 0x260 (0x56342a2d91f0 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #37: _PyFunction_Vectorcall + 0x594 (0x56342a2da7b4 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #38: <unknown function> + 0x166ca8 (0x56342a273ca8 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #39: PyObject_Call + 0x319 (0x56342a244819 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #40: _PyEval_EvalFrameDefault + 0x1dd3 (0x56342a2e4823 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #41: _PyEval_EvalCodeWithName + 0x260 (0x56342a2d91f0 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #42: _PyFunction_Vectorcall + 0x594 (0x56342a2da7b4 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #43: _PyObject_FastCallDict + 0xe7 (0x56342a26b797 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #44: <unknown function> + 0x194bbb (0x56342a2a1bbb in /opt/conda/envs/k2-fsa1/bin/python3)
frame #45: PyObject_Call + 0x45d (0x56342a24495d in /opt/conda/envs/k2-fsa1/bin/python3)
frame #46: _PyEval_EvalFrameDefault + 0x1dd3 (0x56342a2e4823 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #47: _PyEval_EvalCodeWithName + 0x260 (0x56342a2d91f0 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #48: _PyFunction_Vectorcall + 0x594 (0x56342a2da7b4 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #49: <unknown function> + 0x166ca8 (0x56342a273ca8 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #50: PyObject_Call + 0x319 (0x56342a244819 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #51: _PyEval_EvalFrameDefault + 0x1dd3 (0x56342a2e4823 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #52: _PyEval_EvalCodeWithName + 0x260 (0x56342a2d91f0 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #53: _PyFunction_Vectorcall + 0x594 (0x56342a2da7b4 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #54: _PyObject_FastCallDict + 0xe7 (0x56342a26b797 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #55: <unknown function> + 0x194bbb (0x56342a2a1bbb in /opt/conda/envs/k2-fsa1/bin/python3)
frame #56: _PyObject_MakeTpCall + 0x3bf (0x56342a23e25f in /opt/conda/envs/k2-fsa1/bin/python3)
frame #57: _PyEval_EvalFrameDefault + 0x540a (0x56342a2e7e5a in /opt/conda/envs/k2-fsa1/bin/python3)
frame #58: _PyEval_EvalCodeWithName + 0x260 (0x56342a2d91f0 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #59: _PyFunction_Vectorcall + 0x594 (0x56342a2da7b4 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #60: _PyEval_EvalFrameDefault + 0x1517 (0x56342a2e3f67 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #61: _PyEval_EvalCodeWithName + 0x260 (0x56342a2d91f0 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #62: _PyFunction_Vectorcall + 0x594 (0x56342a2da7b4 in /opt/conda/envs/k2-fsa1/bin/python3)
frame #63: _PyEval_EvalFrameDefault + 0x1517 (0x56342a2e3f67 in /opt/conda/envs/k2-fsa1/bin/python3)
```

**Comment by csukuangfj** [comment]
You are using --word-size=4. Do you have 4 GPUs on the machine? And also is the environment variable `CUDA_VISIBLE_DEVICES` set or not?

**Comment by shanguanma** [comment]
Yes, I have four GPUs . I have also set `CUDA_VISIBLE_DEVICES="0,1,2,3"`

**Comment by danpovey** [comment]
This is only happening when it reaches the _optimized_transducer extension code, so I assume it must have something to do with how that code was compiled, possibly some kind of Torch version mismatch?
We are mostly recommending the pruned transducer code now, which is faster, so fixing this may not be the absolute highest prority.

**Comment by shanguanma** [comment]
Ok, I follow your suggestion, I move pruned transducer code(e.g. pruned_transducer_stateless2, pruned_transducer_stateless5), however I found the result of these experiments were worse than transducer stateless and comformer ctc, (e.g. 6.59 vs [5.4](https://github.com/k2-fsa/icefall/blob/master/egs/aishell/ASR/RESULTS.md) in greedy search method.) , I don't know the case is noraml. training stage and inference code  are as follows:
```
if [ ${stage} -le 55 ] && [ ${stop_stage} -ge 55 ];then
   [ -f path2.sh ] && . path2.sh
   mkdir -p  exp/pruned_transducer_stateless2_1
   export CUDA_VISIBLE_DEVICES="0,1,2,3"
  ./pruned_transducer_stateless2/train.py \
        --world-size 4 \
        --num-epochs 30 \
        --start-epoch 0 \
        --initial-lr 0.003\
        --lr-batches 5000\
        --lr-epochs 6\
        --prune-range 5\
        --lm-scale 0.25\
        --am-scale 0.0\
        --simple-loss-scale 0.5\
        --seed 42\
        --print-diagnostics False\
        --save-every-n 8000\
        --keep-last-k 20\
        --use-fp16  False\
        --exp-dir exp/pruned_transducer_stateless2_1/ \
        --max-duration 100 \
        --context-size 2 \
        --enable-spec-aug True\
        --spec-aug-time-warp-factor 80\
        --enable-musan True    2>&1 | tee exp/pruned_transducer_stateless2_1/train.log
fi


if [ ${stage} -le 56 ] && [ ${stop_stage} -ge 56 ];then
   [ -f path2.sh ] && . path2.sh
   # greedy search
   lang_dir=data/lang_char
   for avg in 2 3 4 5 6 7 8 9 10;do
      ./pruned_transducer_stateless2/decode.py \
       --epoch 29 \
       --avg $avg \
       --exp-dir exp/pruned_transducer_stateless2_1/ \
       --lang-dir $lang_dir\
       --max-duration 100 \
       --decoding-method greedy_search \
       --max-sym-per-frame 1
  done
  # best_cer: avg=7 6.59% 
fi



if [ ${stage} -le 80 ] && [ ${stop_stage} -ge 80 ];then
   [ -f path2.sh ] && . path2.sh
   mkdir -p  exp/pruned_transducer_stateless5
   export CUDA_VISIBLE_DEVICES="0,1,2,3"
  ./pruned_transducer_stateless5/train.py \
        --world-size 4 \
        --num-epochs 90 \
        --start-epoch 0 \
        --initial-lr 0.003\
        --lr-batches 5000\
        --lr-epochs 6\
        --prune-range 5\
        --lm-scale 0.25\
        --am-scale 0.0\
        --simple-loss-scale 0.5\
        --seed 42\
        --print-diagnostics False\
        --save-every-n 8000\
        --keep-last-k 20\
        --use-fp16  False\
        --exp-dir exp/pruned_transducer_stateless5/ \
        --max-duration 100 \
        --context-size 2 \
        --enable-spec-aug True\
        --spec-aug-time-warp-factor 80\
        --enable-musan True   \
        --use-fp16 0 \
        --num-encoder-layers 18 \
        --dim-feedforward 2048 \
        --nhead 8 \
        --encoder-dim 512 \
        --decoder-dim 512 \
        --joiner-dim 512 2>&1 | tee exp/pruned_transducer_stateless5/train.log
fi



if [ ${stage} -le 81 ] && [ ${stop_stage} -ge 81 ];then
   [ -f path2.sh ] && . path2.sh
   # greedy search
   lang_dir=data/lang_char
   for avg in 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20;do
      ./pruned_transducer_stateless5/decode.py \
        --epoch 33 \
        --avg $avg \
        --exp-dir exp/pruned_transducer_stateless5/ \
        --lang-dir $lang_dir\
        --max-duration 100 \
        --decoding-method greedy_search \
        --max-sym-per-frame 1\
        --num-encoder-layers 18 \
        --dim-feedforward 2048 \
        --nhead 8 \
        --encoder-dim 512 \
        --decoder-dim 512 \
        --joiner-dim 512
  done
  # best_cer: avg=4,5 6.49%
fi

```

**Comment by csukuangfj** [comment]
Could you provide a link to the tensorboard log?
Also, could you attach a copy of the decoding result? I would like to see what kind of errors there are.

**Comment by danpovey** [comment]
Yes, it's hard to diagnose this with such limited information.  If you could create a table showing the differences,
e.g. in model configuration, model size, train and valid loss (pruned and simple) towards the end of training,
WERs, and maybe links to Tensorboard logs, that would be helpful.

**Comment by shanguanma** [comment]
@csukuangfj ，Ok, this is tensorboard log path(it corresponds  to the pruned_transducer_stateless2 experiment )https://tensorboard.dev/experiment/1prGpLf2T0OFn26o5EYA9A/#scalars, its decode results are stored the file
[errs-test-greedy_search-epoch-29-avg-7-context-2-max-sym-per-frame-1.txt](https://github.com/k2-fsa/icefall/files/8795054/errs-test-greedy_search-epoch-29-avg-7-context-2-max-sym-per-frame-1.txt)

**Comment by shanguanma** [comment]
@danpovey， OK, I will paste related information for the two models. 
experiment name  | tensorbaord log  | training log  | Number of model parameters| WER % in gready search mode|
| --- | --- | --- | --- |--- |
tranducer_stateless | https://tensorboard.dev/experiment/62Dj8ujpTGKdaDa1KALlzw/#scalars | [log-train-2022-02-15-12-46-42-0.txt](https://github.com/k2-fsa/icefall/files/8795304/log-train-2022-02-15-12-46-42-0.txt)| 87939824|5.05|
pruned_tranducer_statelss2|https://tensorboard.dev/experiment/1prGpLf2T0OFn26o5EYA9A/#scalars|[train.log](https://github.com/k2-fsa/icefall/files/8795306/train.log)|86515676|6.59|

**Comment by danpovey** [comment]
It looks like the newer setup is overfitting much more.  But you are not supposed to run the newer setup for too many epochs: 20 or 30 should be enough, you are training for 88.  Have you tried testing earlier epochs?

**Comment by shanguanma** [comment]
@danpovey , however, I used earlier epochs(e.g. 29 and before) to decode, its command and its best result is as follows:
```
if [ ${stage} -le 56 ] && [ ${stop_stage} -ge 56 ];then
   [ -f path2.sh ] && . path2.sh
   # greedy search
   lang_dir=data/lang_char
   for avg in 2 3 4 5 6 7 8 9 10;do
      ./pruned_transducer_stateless2/decode.py \
       --epoch 29 \
       --avg $avg \
       --exp-dir exp/pruned_transducer_stateless2_1/ \
       --lang-dir $lang_dir\
       --max-duration 100 \
       --decoding-method greedy_search \
       --max-sym-per-frame 1
  done
  # best_cer: avg=7 6.59% 
fi
```

**Comment by danpovey** [comment]
Anyway it looks like it is overfitting so likely the remedy would be narrower layers, like encoder_dim reduced to 384 or 256, and more augmentation if you are not doing much augmentation.   I don't know how much data this aishell has, I assume it must be less than Librispeech.

**Comment by shanguanma** [comment]
aishell dataset is less than Libirspeech. its train set has 150 hours, the development set has 10 hours, and test set has 5 hours. I will follow your suggestion to do the experiment.

**Comment by csukuangfj** [comment]
@shanguanma 
Changing `--context-size 2` to  `--context-size 1` is helpful for dataset like Chinese that uses Chinese characters as modelling units. I can get a WER around 5.36 for greedy search on aishell at `epoch 29, avg 6`.
