### ISSUE TITLE
modified_beam_search error

### ISSUE THREAD

**Issue by pingfengluo** [k2-fsa/icefall#408]
@csukuangfj 
1. I tried to use beam-search with latest code  then came up with  bellow error. My Torch version is 1.11.0+cu113. 
2. Then i tried to use CPU for decoding and the beam-search worked fine. Maybe the row_ids() function is not compatible with Torch version is 1.11.0+cu113?

```
python3 ./pruned_transducer_stateless2/pretrained.py       --decoding-method modified_beam_search       --beam-size 4       --lang-dir ./tmp/icefall_asr_wenetspeech_pruned_transducer_stateless2/data/lang_char      --sample-rate 16000       --checkpoint ./tmp/icefall_asr_wenetspeech_pruned_transducer_stateless2/exp/pretrained_epoch_10_avg_2.pt  /data/my_speech_asr/public_data/11152336/data/my_heard_test/wavs/0-1650251582229-0-8687404.wav
2022-06-08 19:25:45,615 INFO [lexicon.py:176] Loading pre-compiled tmp/icefall_asr_wenetspeech_pruned_transducer_stateless2/data/lang_char/Linv.pt
2022-06-08 19:25:45,696 INFO [pretrained.py:213] {'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 10, 'log_interval': 1, 'reset_interval': 200, 'feature_dim': 80, 'subsampling_factor': 4, 'encoder_dim': 512, 'nhead': 8, 'dim_feedforward': 2048, 'num_encoder_layers': 12, 'decoder_dim': 512, 'joiner_dim': 512, 'env_info': {'k2-version': '1.15.1', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': 'c11c0b70e91d24935514b73d6bffddc8f5a07932', 'k2-git-date': 'Sat Jun 4 14:06:20 2022', 'lhotse-version': '1.3.0.dev+git.4198446.clean', 'torch-version': '1.11.0+cu113', 'torch-cuda-available': True, 'torch-cuda-version': '11.3', 'python-version': '3.7', 'icefall-git-branch': 'master', 'icefall-git-sha1': '5079d99-dirty', 'icefall-git-date': 'Wed Jun 8 12:06:57 2022', 'icefall-path': '/opt/conda/lib/python3.7/site-packages', 'k2-path': '/opt/conda/lib/python3.7/site-packages/k2/__init__.py', 'lhotse-path': '/opt/conda/lib/python3.7/site-packages/lhotse/__init__.py', 'hostname': 'single-machine-20220608141143324-worker-0', 'IP address': '127.0.0.1'}, 'checkpoint': './tmp/icefall_asr_wenetspeech_pruned_transducer_stateless2/exp/pretrained_epoch_10_avg_2.pt', 'lang_dir': './tmp/icefall_asr_wenetspeech_pruned_transducer_stateless2/data/lang_char', 'decoding_method': 'modified_beam_search', 'sound_files': ['/data/my_speech_asr/public_data/11152336/data/my_heard_test/wavs/0-1650251582229-0-8687404.wav'], 'sample_rate': 16000, 'beam_size': 4, 'beam': 4, 'max_contexts': 4, 'max_states': 8, 'context_size': 2, 'max_sym_per_frame': 1, 'blank_id': 0, 'vocab_size': 5537}
2022-06-08 19:25:45,697 INFO [pretrained.py:219] device: cuda:6
2022-06-08 19:25:45,697 INFO [pretrained.py:221] Creating model
2022-06-08 19:25:51,276 INFO [pretrained.py:235] Constructing Fbank computer
2022-06-08 19:25:51,277 INFO [pretrained.py:245] Reading sound files: ['/data/my_speech_asr/public_data/11152336/data/my_heard_test/wavs/0-1650251582229-0-8687404.wav']
2022-06-08 19:25:51,326 INFO [pretrained.py:251] Decoding started
2022-06-08 19:25:52,135 INFO [pretrained.py:268] Using modified_beam_search
Traceback (most recent call last):
  File "./pruned_transducer_stateless2/pretrained.py", line 342, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./pruned_transducer_stateless2/pretrained.py", line 298, in main
    beam=params.beam_size,
  File "/data/my_speech_asr/11152336/code/icefall/egs/wenetspeech/ASR/pruned_transducer_stateless2/beam_search.py", line 675, in modified_beam_search
    index=hyps_shape.row_ids(1).to(torch.int64),
RuntimeError: invalid device function
```

**Comment by csukuangfj** [comment]
>   File "/data/my_speech_asr/11152336/code/icefall/egs/wenetspeech/ASR/pruned_transducer_stateless2/beam_search.py", line 675, in modified_beam_search

Can you put a breakpoint at line 667
https://github.com/k2-fsa/icefall/blob/8512aaf585a33dcb424b8a045192e87cdce3cf0c/egs/librispeech/ASR/pruned_transducer_stateless2/beam_search.py#L667

and print out the value of `hyps_shape `, `hyps_shape.device`, `hyps_shape.row_ids(1)`?

---

By the way, how did you install k2? Did you install k2 on the same machine that you use for decoding?

**Comment by pingfengluo** [comment]
oh, i see. the problem is the building and running machine of K2 is different. tks.

**Comment by csukuangfj** [comment]
> oh, i see. the problem is the building and running machine of K2 is different. tks.

To reduce the compilation time, k2 is by default only compiled against a specific GPU architecture.

If you want to use k2  on a machine with a different GPU architecture from the machine you used to compile k2, you can change
https://github.com/k2-fsa/k2/blob/c11c0b70e91d24935514b73d6bffddc8f5a07932/CMakeLists.txt#L238-L240
```cmake
  if(NOT K2_COMPUTE_ARCHS)
    set(K2_COMPUTE_ARCHS ${K2_COMPUTE_ARCH_CANDIDATES})
  endif()
```
to
```cmake
    set(K2_COMPUTE_ARCHS ${K2_COMPUTE_ARCH_CANDIDATES})
```
