### ISSUE TITLE
AssertionError (assert x.size(0) == x_lens.size(0) == y.dim0)

### ISSUE THREAD

**Issue by jwvl** [k2-fsa/icefall#424]
I have been able to successfully train a model using the (mini) Librispeech Icefall recipe (pruned_transducer_stateless2)
I am now trying to adapt the recipe to use a custom dataset, using **lhotse kaldi import** to re-use a Kaldi-style training dataset. The adapted data preparation stages all run OK.
However, soon after training starts the script crashes because of an assertion error in pruned_transducer_stateless2/model.py :

### Stack trace
```
python3 ./pruned_transducer_stateless2/train.py --exp-dir=pruned_transducer_stateless2/exp_nl --world-size 1 --num-epochs 20 --max-duration 100
2022-06-13 14:12:08,979 INFO [train.py:792] Training started
2022-06-13 14:12:08,981 INFO [train.py:802] Device: cuda:0
2022-06-13 14:12:09,000 INFO [train.py:811] {'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 50, 'reset_interval': 200, 'valid_interval': 3000, 'feature_dim': 80, 'subsampling_factor': 4, 'encoder_dim': 512, 'nhead': 8, 'dim_feedforward': 2048, 'num_encoder_layers': 12, 'decoder_dim': 512, 'joiner_dim': 512, 'model_warm_step': 3000, 'env_info': {'k2-version': '1.15.1', 'k2-build-type': 'Release', 'k2-with-cuda': True, 'k2-git-sha1': 'b173c11ba379e2da0056281fe6b2d56f081419be', 'k2-git-date': 'Mon Apr 18 16:10:45 2022', 'lhotse-version': '1.3.0.dev+git.4198446.dirty', 'torch-version': '1.11.0', 'torch-cuda-available': True, 'torch-cuda-version': '11.3', 'python-version': '3.8', 'icefall-git-branch': 'master', 'icefall-git-sha1': 'fbfc98f-dirty', 'icefall-git-date': 'Wed Jun 1 06:31:47 2022', 'icefall-path': '/home/janwillem/icefall', 'k2-path': '/anaconda/envs/icefall_cuda_11_3/lib/python3.8/site-packages/k2/__init__.py', 'lhotse-path': '/home/janwillem/lhotse/lhotse/__init__.py', 'hostname': 'dsvm-stt-icefall', 'IP address': '10.0.17.8'}, 'world_size': 1, 'master_port': 12354, 'tensorboard': True, 'num_epochs': 20, 'start_epoch': 0, 'start_batch': 0, 'exp_dir': PosixPath('pruned_transducer_stateless2/exp_nl'), 'bpe_model': 'data/lang_bpe_500/bpe.model', 'initial_lr': 0.003, 'lr_batches': 5000, 'lr_epochs': 6, 'context_size': 2, 'prune_range': 5, 'lm_scale': 0.25, 'am_scale': 0.0, 'simple_loss_scale': 0.5, 'seed': 42, 'print_diagnostics': False, 'save_every_n': 8000, 'keep_last_k': 20, 'use_fp16': False, 'manifest_dir': PosixPath('data/fbank'), 'max_duration': 100, 'bucketing_sampler': True, 'num_buckets': 30, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'shuffle': True, 'drop_last': True, 'return_cuts': True, 'num_workers': 2, 'enable_spec_aug': True, 'spec_aug_time_warp_factor': 80, 'enable_musan': True, 'input_strategy': 'PrecomputedFeatures', 'blank_id': 0, 'vocab_size': 500}
2022-06-13 14:12:09,000 INFO [train.py:813] About to create model
2022-06-13 14:12:09,419 INFO [train.py:817] Number of model parameters: 78648040
2022-06-13 14:12:31,743 INFO [asr_datamodule.py:386] About to get train cuts
2022-06-13 14:14:33,943 INFO [asr_datamodule.py:202] Enable MUSAN
2022-06-13 14:14:33,943 INFO [asr_datamodule.py:203] About to get Musan cuts
2022-06-13 14:14:50,382 INFO [asr_datamodule.py:231] Enable SpecAugment
2022-06-13 14:14:50,382 INFO [asr_datamodule.py:232] Time warp factor: 80
2022-06-13 14:14:50,382 INFO [asr_datamodule.py:244] Num frame mask: 10
2022-06-13 14:14:50,382 INFO [asr_datamodule.py:257] About to create train dataset
2022-06-13 14:14:50,383 INFO [asr_datamodule.py:286] Using DynamicBucketingSampler.
/home/janwillem/lhotse/lhotse/dataset/sampling/dynamic_bucketing.py:121: UserWarning: You are using DynamicBucketingSampler with an eagerly read CutSet. You won't see any memory/speed benefits with that setup. Either use 'CutSet.from_jsonl_lazy' to read the CutSet lazily, or use a BucketingSampler instead.
  warnings.warn(
2022-06-13 14:14:50,455 INFO [asr_datamodule.py:301] About to create train dataloader
2022-06-13 14:14:50,457 INFO [asr_datamodule.py:393] About to get dev cuts
2022-06-13 14:14:50,501 INFO [asr_datamodule.py:332] About to create dev dataset
2022-06-13 14:14:50,502 INFO [asr_datamodule.py:351] About to create dev dataloader
2022-06-13 14:14:50,502 INFO [train.py:977] Sanity check -- see if any of the batches in epoch 0 would cause OOM.
2022-06-13 14:16:23,088 INFO [train.py:728] Epoch 0, batch 0, loss[loss=0.9901, simple_loss=1.98, pruned_loss=6.328, over 2294.00 frames.], tot_loss[loss=0.9901, simple_loss=1.98, pruned_loss=6.328, over 2294.00 frames.], batch size: 8, lr: 3.00e-03
2022-06-13 14:17:46,187 INFO [train.py:728] Epoch 0, batch 50, loss[loss=0.6353, simple_loss=1.271, pruned_loss=7.017, over 2391.00 frames.], tot_loss[loss=0.7682, simple_loss=1.536, pruned_loss=7.194, over 108600.07 frames.], batch size: 17, lr: 3.00e-03
2022-06-13 14:19:09,258 INFO [train.py:728] Epoch 0, batch 100, loss[loss=0.5037, simple_loss=1.007, pruned_loss=7.13, over 2333.00 frames.], tot_loss[loss=0.6926, simple_loss=1.385, pruned_loss=7.22, over 191237.10 frames.], batch size: 7, lr: 3.00e-03
2022-06-13 14:20:07,727 INFO [train.py:955] Saving batch to pruned_transducer_stateless2/exp_nl/batch-bdd640fb-0667-1ad1-1c80-317fa3b1799d.pt
2022-06-13 14:20:07,735 INFO [train.py:961] features shape: torch.Size([15, 663, 80])
2022-06-13 14:20:07,736 INFO [train.py:965] num tokens: 561
Traceback (most recent call last):
  File "./pruned_transducer_stateless2/train.py", line 1030, in <module>
    main()
  File "./pruned_transducer_stateless2/train.py", line 1023, in main
    run(rank=0, world_size=1, args=args)
  File "./pruned_transducer_stateless2/train.py", line 901, in run
    train_one_epoch(
  File "./pruned_transducer_stateless2/train.py", line 678, in train_one_epoch
    loss, loss_info = compute_loss(
  File "./pruned_transducer_stateless2/train.py", line 546, in compute_loss
    simple_loss, pruned_loss = model(
  File "/anaconda/envs/icefall_cuda_11_3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/janwillem/icefall/egs/librispeech/ASR/pruned_transducer_stateless2/model.py", line 123, in forward
    assert x.size(0) == x_lens.size(0) == y.dim0
AssertionError
```

These are the values causing the assertion to fail:

```
x.size(0):  15
x_lens.size(0):  14
y.dim0:  14
```

I assume it must be due to some mistake I made in data preparation, or because of some property of the data themselves, since I did not make any changes to the training code. However, I'm not sure what to look for / what would cause this assertion to fail.
Any ideas? Thanks in advance.

**Comment by csukuangfj** [comment]
You can add something to
https://github.com/k2-fsa/icefall/blob/5c3ee8bfcd0e38fe4950b65a87fcefd955909b5f/egs/librispeech/ASR/pruned_transducer_stateless2/train.py#L537

e.g.

```python
feature_lens = supervisions["num_frames"].to(device) 

print(feature_lens.shape)
print(feature.shape)
```

and please post the output.

**Comment by csukuangfj** [comment]
By the way, I would recommend trying `pruned_transducer_stateless4` or `pruned_transducer_stateless5`. They change the `train.py` to save averaged models periodically during training and you can use `--use-averaged-model=true` during decoding. 

It is helpful to reduce the WER.

**Comment by jwvl** [comment]
Hi,
Sorry for the belated reply.

Here is the  output after adding the lines you suggested:

```
2022-06-19 21:02:21,809 INFO [train_nl.py:719] Epoch 0, batch 0, loss[loss=0.9931, simple_loss=1.986, pruned_loss=7.112, over 2240.00 frames.], tot_loss[loss=0.9931, simple_loss=1.986, pruned_loss=7.112, over 2240.00 frames.], batch size: 8, lr: 3.00e-03
torch.Size([26])
torch.Size([26, 385, 80])
torch.Size([12])
torch.Size([12, 867, 80])
torch.Size([7])
torch.Size([7, 1430, 80])
torch.Size([25])
torch.Size([25, 413, 80])
torch.Size([78])
torch.Size([78, 138, 80])
torch.Size([36])
torch.Size([36, 284, 80])
torch.Size([20])
torch.Size([20, 502, 80])
torch.Size([21])
torch.Size([21, 470, 80])
torch.Size([26])
torch.Size([26, 384, 80])
torch.Size([5])
torch.Size([5, 1809, 80])
torch.Size([10])
torch.Size([10, 958, 80])
torch.Size([10])
torch.Size([10, 1034, 80])
torch.Size([33])
torch.Size([33, 308, 80])
torch.Size([22])
torch.Size([22, 466, 80])
torch.Size([28])
torch.Size([28, 361, 80])
torch.Size([18])
torch.Size([18, 569, 80])
torch.Size([7])
torch.Size([7, 1461, 80])
torch.Size([5])
torch.Size([5, 1824, 80])
torch.Size([43])
torch.Size([43, 239, 80])
torch.Size([20])
torch.Size([20, 500, 80])
torch.Size([53])
torch.Size([53, 196, 80])
torch.Size([33])
torch.Size([33, 308, 80])
torch.Size([53])
torch.Size([53, 197, 80])
torch.Size([12])
torch.Size([12, 871, 80])
torch.Size([60])
torch.Size([60, 176, 80])
torch.Size([16])
torch.Size([16, 604, 80])
torch.Size([10])
torch.Size([10, 953, 80])
torch.Size([36])
torch.Size([36, 284, 80])
torch.Size([5])
torch.Size([5, 1903, 80])
torch.Size([19])
torch.Size([19, 532, 80])
torch.Size([13])
torch.Size([13, 738, 80])
torch.Size([11])
torch.Size([11, 946, 80])
torch.Size([16])
torch.Size([16, 608, 80])
torch.Size([7])
torch.Size([7, 1394, 80])
torch.Size([53])
torch.Size([53, 197, 80])
torch.Size([33])
torch.Size([33, 309, 80])
torch.Size([60])
torch.Size([60, 176, 80])
torch.Size([12])
torch.Size([12, 797, 80])
torch.Size([67])
torch.Size([67, 156, 80])
torch.Size([7])
torch.Size([7, 1442, 80])
torch.Size([8])
torch.Size([8, 1218, 80])
torch.Size([14])
torch.Size([14, 690, 80])
torch.Size([30])
torch.Size([30, 334, 80])
torch.Size([21])
torch.Size([21, 471, 80])
torch.Size([19])
torch.Size([19, 534, 80])
torch.Size([59])
torch.Size([59, 176, 80])
torch.Size([27])
torch.Size([28, 362, 80])
2022-06-19 21:03:36,787 INFO [train_nl.py:944] Saving batch to pruned_transducer_stateless5/exp_nl/batch-bdd640fb-0667-1ad1-1c80-317fa3b1799d.pt
2022-06-19 21:03:36,796 INFO [train_nl.py:950] features shape: torch.Size([28, 362, 80])
2022-06-19 21:03:36,797 INFO [train_nl.py:954] num tokens: 638
Traceback (most recent call last):
   File "./pruned_transducer_stateless5/train_nl.py", line 1019, in <module>
     if __name__ == "__main__":
   File "./pruned_transducer_stateless5/train_nl.py", line 1012, in main
     else:
   File "./pruned_transducer_stateless5/train_nl.py", line 892, in run
    
   File "./pruned_transducer_stateless5/train_nl.py", line 671, in train_one_epoch
     with torch.cuda.amp.autocast(enabled=params.use_fp16):
   File "./pruned_transducer_stateless5/train_nl.py", line 543, in compute_loss
     with torch.set_grad_enabled(is_training):
   File "/anaconda/envs/icefall/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
     return forward_call(*input, **kwargs)
   File "/datadrive/icefall/egs/librispeech/ASR/pruned_transducer_stateless5/model.py", line 117, in forward
     assert x.size(0) == x_lens.size(0) == y.dim0
 AssertionError
```

It seems the mismatch is between 27 (feature_lens.shape) and 28 (feature.shape[0]).

**Comment by csukuangfj** [comment]
> 2022-06-19 21:03:36,787 INFO [train_nl.py:944] Saving batch to pruned_transducer_stateless5/exp_nl/batch-bdd640fb-0667-1ad1-1c80-317fa3b1799d.pt

You can use
```python3
batch = torch.load("pruned_transducer_stateless5/exp_nl/batch-bdd640fb-0667-1ad1-1c80-317fa3b1799d.pt")
```
to view the problematic batch and check why there is a mismatch.

**Comment by Aurora-6** [comment]
@jwvl Hello！How do you use Kaldi-style dataset (including feats.scp) to generate `*.jsonl.gz` for icefall training scripts? If convenient, could you please give me a specific script for reference？Thanks a lot!
I do it in this way (https://github.com/k2-fsa/icefall/issues/510#issuecomment-1208003550). But it seems wrong when I use official pre-trained model to decode test_cuts generated as described.
