### ISSUE TITLE
RuntimeError: DataLoader worker is killed by signal

### ISSUE THREAD

**Issue by shushanxingzhe** [k2-fsa/icefall#463]
@luomingshuang @csukuangfj Please give me some advice. I have tried several times. This error pops up every time when compute_fbank_wenetspeech_dev_test script goes to 42%.

```
Computing features in batches:  42%|████▏     | 54856/130992 [35:57:55<49:55:01,  2.36s/it] 
Traceback (most recent call last):
  File "./local/compute_fbank_wenetspeech_dev_test.py", line 93, in <module>
    main()
  File "./local/compute_fbank_wenetspeech_dev_test.py", line 89, in main
    compute_fbank_wenetspeech_dev_test()
  File "./local/compute_fbank_wenetspeech_dev_test.py", line 68, in compute_fbank_wenetspeech_dev_test
    cut_set = cut_set.compute_and_store_features_batch(
  File "/home/liujiafu/miniconda3/envs/k2/lib/python3.8/site-packages/lhotse/cut.py", line 4752, in compute_and_store_features_batch
    features = extractor.extract_batch(
  File "/home/liujiafu/miniconda3/envs/k2/lib/python3.8/site-packages/lhotse/features/kaldifeat.py", line 84, in extract_batch
    return self.extract(samples=samples, sampling_rate=sampling_rate)
  File "/home/liujiafu/miniconda3/envs/k2/lib/python3.8/site-packages/lhotse/features/kaldifeat.py", line 125, in extract
    result = self.extractor(samples, chunk_size=self.config.chunk_size)
  File "/home/liujiafu/miniconda3/envs/k2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/liujiafu/miniconda3/envs/k2/lib/python3.8/site-packages/kaldifeat-1.16-py3.8-linux-x86_64.egg/kaldifeat/offline_feature.py", line 76, in forward
    strided = [self.convert_samples_to_frames(w) for w in waves]
  File "/home/liujiafu/miniconda3/envs/k2/lib/python3.8/site-packages/kaldifeat-1.16-py3.8-linux-x86_64.egg/kaldifeat/offline_feature.py", line 76, in <listcomp>
    strided = [self.convert_samples_to_frames(w) for w in waves]
  File "/home/liujiafu/miniconda3/envs/k2/lib/python3.8/site-packages/kaldifeat-1.16-py3.8-linux-x86_64.egg/kaldifeat/offline_feature.py", line 155, in convert_samples_to_frames
    return _kaldifeat.get_strided(wave, self.opts.frame_opts)
  File "/home/liujiafu/miniconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 101649) is killed by signal: Killed.
```

**Comment by luomingshuang** [comment]
As shown in your issue, it seems that you are using the old codes not the newest codes. In the newest codes, I have moved the cut_set.trim_to_supervisions before cut_set.compute_and_store_features_batch. Maybe it will cause some cases as https://github.com/lhotse-speech/lhotse/issues/761 if you use the old codes. So I would like to suggest you use the newest codes.

**Comment by shushanxingzhe** [comment]
I solve it by reducing num_workers to 8. Very thanks for your great work.
