### ISSUE TITLE
CUDA error  of device

### ISSUE THREAD

**Issue by cdxie** [k2-fsa/icefall#47]
Hi, I run the TDNN-LSTM-CTC training of librispeech, command line: ./tdnn_lstm_ctc/train.py --world-size 4，but I did not use:  export CUDA_VISIBLE_DEVICES="0,1,2,3", because our computing cluster can not set the CUDA_VISIBLE_DEVICES, so I got some errors :

Traceback (most recent call last):
  File "./tdnn_lstm_ctc/train.py", line 616, in <module>
    main()
  File "./tdnn_lstm_ctc/train.py", line 610, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data/nfs13/nfs/aisearch/asr/cdxie/icefall/egs/librispeech/ASR/tdnn_lstm_ctc/train.py", line 512, in run
    setup_dist(rank, world_size, params.master_port)
  File "/workspace/icefall/icefall/dist.py", line 30, in setup_dist
    torch.cuda.set_device(rank)
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal

1）how to solve the error ?
2）whether the icefall do not support the Multi-GPU multi-machine DDP training cause the above error？If it is，when added？

**Comment by csukuangfj** [comment]
> 1）how to solve the error ?

You are using `--world-size 4`, so you have to ensure that there are at least 4 GPUs on you cluster and the code will use
GPU 0, GPU 1, GPU 2 and GPU 3 for training since you don't set `CUDA_VISIBLE_DEVICES`. If you specify more GPUs than there actually are, you will get the above error.

Can you check how many GPUs are there before you launching `train.py`? The following code may be helpful.

```python
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
3
```

> 2）whether the icefall do not support the Multi-GPU multi-machine DDP training cause the above error？If it is，when added？

`icefall` supports only single-machine multi-GPU training at present. We will add multi-machine multi-GPU support in the future.
