### ISSUE TITLE
RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by JaheimLee** [k2-fsa/icefall#515]
When using prepare.sh file in wenetspeech from stage 1, a runtime error raised during computer features of `data/fbank/cuts_TEST_NET_raw.jsonl.gz`. Here is the logs:
```
2022-08-02 22:39:27,066 INFO [compute_fbank_wenetspeech_dev_test.py:63] Loading data/fbank/cuts_TEST_NET_raw.jsonl.gz
2022-08-02 22:39:27,096 INFO [compute_fbank_wenetspeech_dev_test.py:66] Splitting cuts into smaller chunks
2022-08-02 22:39:27,097 INFO [compute_fbank_wenetspeech_dev_test.py:71] Computing features
```
And when `Computing features in batches: 16024it`, it will raise:
```
Traceback (most recent call last):  File "/data/lijinghui/icefall/egs/wenetspeech/ASR/./local/compute_fbank_wenetspeech_dev_test.py", line 95, in <module>
    main()  
File "/data/lijinghui/icefall/egs/wenetspeech/ASR/./local/compute_fbank_wenetspeech_dev_test.py", line 91, in main
    compute_fbank_wenetspeech_dev_test()  
File "/data/lijinghui/icefall/egs/wenetspeech/ASR/./local/compute_fbank_wenetspeech_dev_test.py", line 72, in compute_fbank_wenetspeech_dev_test
    cut_set = cut_set.compute_and_store_features_batch(  
File "/data/miniconda3/envs/k2/lib/python3.9/site-packages/lhotse/cut.py", line 4855, in compute_and_store_features_batch
    for batch in dloader:  
File "/data/miniconda3/envs/k2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()  
File "/data/miniconda3/envs/k2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1207, in _next_data
    idx, data = self._get_data()
File "/data/miniconda3/envs/k2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1173, in _get_data
    success, data = self._try_get_data()  
File "/data/miniconda3/envs/k2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1011, in _try_get_data
    data = self._data_queue.get(timeout=timeout)  
File "/data/miniconda3/envs/k2/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)  
File "/data/miniconda3/envs/k2/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 295, in rebuild_storage_fd
    fd = df.detach()  
File "/data/miniconda3/envs/k2/lib/python3.9/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)  
File "/data/miniconda3/envs/k2/lib/python3.9/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]  
File "/data/miniconda3/envs/k2/lib/python3.9/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata 
```

**Comment by wgb14** [comment]
I got the same error, and resolved by suggestions in https://discuss.pytorch.org/t/runtimeerror-received-0-items-of-ancdata/4999
