### ISSUE TITLE
icefall

### ISSUE THREAD

**Issue by yuyhee** [k2-fsa/icefall#556]
Downloading waves_yesno.tar.gz: 4.49MB [02:10, 36.1kB/s]                                                                                                       
2022-08-28 15:00:03 (prepare.sh:36:main) Stage 1: Prepare yesno manifest
/root/anaconda3/envs/foo/lib/python3.8/site-packages/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
2022-08-28 15:00:04 (prepare.sh:42:main) Stage 2: Compute fbank for yesno
Traceback (most recent call last):
  File "./local/compute_fbank_yesno.py", line 18, in <module>
    from icefall.utils import get_executor
ModuleNotFoundError: No module named 'icefall'

**Comment by csukuangfj** [comment]
Have you tried the following `export`?
https://k2-fsa.github.io/icefall/installation/index.html#test-your-installation
![Screen Shot 2022-08-28 at 15 21 38](https://user-images.githubusercontent.com/5284924/187062703-142e1e1c-fe63-4c7f-9e6a-0e40ebb86cbb.png)

```bash
$ export PYTHONPATH=/tmp/icefall:$PYTHONPATH
$ cd /tmp/icefall
$ cd egs/yesno/ASR
$ ./prepare.sh
```

**Comment by yuyhee** [comment]
Building wheel for kaldilm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-72g5z5w0
       cwd: /tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/
  Complete output (62 lines):
  /root/anaconda3/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/kaldilm
  copying kaldilm/python/kaldilm/arpa2fst.py -> build/lib.linux-x86_64-3.9/kaldilm
  copying kaldilm/python/kaldilm/__init__.py -> build/lib.linux-x86_64-3.9/kaldilm
  copying kaldilm/python/kaldilm/__main__.py -> build/lib.linux-x86_64-3.9/kaldilm
  running build_ext
  For fast compilation, run:
  export KALDILM_MAKE_ARGS="-j"; python setup.py install
  Setting PYTHON_EXECUTABLE to /root/anaconda3/bin/python
  sh: 1: cmake: not found
  make: *** No rule to make target '_kaldilm'.  Stop.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py", line 120, in <module>
      setuptools.setup(
    File "/root/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/root/anaconda3/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/root/anaconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/root/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/root/anaconda3/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/root/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/root/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/root/anaconda3/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/root/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/root/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/root/anaconda3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/root/anaconda3/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/root/anaconda3/lib/python3.9/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/root/anaconda3/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
      _build_ext.build_ext.build_extensions(self)
    File "/root/anaconda3/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/root/anaconda3/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py", line 56, in build_extension
      raise Exception(
  Exception:
  Build kaldilm failed. Please check the error message.
  You can ask for help by creating an issue on GitHub.
  
  Click:
      https://github.com/csukuangfj/kaldilm/issues/new
  
  ----------------------------------------
  ERROR: Failed building wheel for kaldilm
  Running setup.py clean for kaldilm
  Building wheel for kaldialign (setup.py) ... done
  Created wheel for kaldialign: filename=kaldialign-0.2-cp39-cp39-linux_x86_64.whl size=28476 sha256=e43a04426802d31e540303d6195751eb3a764883141c5bf30b56c8344dde5c44
  Stored in directory: /root/.cache/pip/wheels/64/e7/6f/29103a06367eb889b7c4e3df8a661677d2d03094aaf2d3a229
Successfully built kaldialign
Failed to build kaldilm
Installing collected packages: pyasn1, rsa, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, protobuf, numpy, humanfriendly, google-auth, tensorboard-plugin-wit, tensorboard-data-server, onnx, markdown, grpcio, google-auth-oauthlib, flatbuffers, coloredlogs, absl-py, typeguard, tensorboard, sentencepiece, onnxruntime, onnx-graphsurgeon, multi-quantization, kaldilm, kaldialign
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
    Running setup.py install for kaldilm ... error
    ERROR: Command errored out with exit status 1:
     command: /root/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-48qy9xgc/install-record.txt --single-version-externally-managed --compile --install-headers /root/anaconda3/include/python3.9/kaldilm
         cwd: /tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/
    Complete output (64 lines):
    /root/anaconda3/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/kaldilm
    copying kaldilm/python/kaldilm/arpa2fst.py -> build/lib.linux-x86_64-3.9/kaldilm
    copying kaldilm/python/kaldilm/__init__.py -> build/lib.linux-x86_64-3.9/kaldilm
    copying kaldilm/python/kaldilm/__main__.py -> build/lib.linux-x86_64-3.9/kaldilm
    running build_ext
    For fast compilation, run:
    export KALDILM_MAKE_ARGS="-j"; python setup.py install
    Setting PYTHON_EXECUTABLE to /root/anaconda3/bin/python
    sh: 1: cmake: not found
    make: *** No rule to make target '_kaldilm'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py", line 120, in <module>
        setuptools.setup(
      File "/root/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/root/anaconda3/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/root/anaconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/root/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/root/anaconda3/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/root/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/root/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/root/anaconda3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/root/anaconda3/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/root/anaconda3/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/root/anaconda3/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/root/anaconda3/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/root/anaconda3/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py", line 56, in build_extension
        raise Exception(
    Exception:
    Build kaldilm failed. Please check the error message.
    You can ask for help by creating an issue on GitHub.
    
    Click:
        https://github.com/csukuangfj/kaldilm/issues/new
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zbi39t96/kaldilm_0794f1168a1849b6bbd9b3cd84a889b3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-48qy9xgc/install-record.txt --single-version-externally-managed --compile --install-headers /root/anaconda3/include/python3.9/kaldilm Check the logs for full command output.
