### ISSUE TITLE
ha

### ISSUE THREAD

**Issue by yuyhee** [k2-fsa/icefall#557]
foo) root@iZ2zeh94phzrw5upket4jsZ:~# export PYTHONPATH=/tmp/icefall:$PYTHONPATH
(foo) root@iZ2zeh94phzrw5upket4jsZ:~# cd /tmp/icefall
(foo) root@iZ2zeh94phzrw5upket4jsZ:/tmp/icefall# cd egs/yesno/ASR
(foo) root@iZ2zeh94phzrw5upket4jsZ:/tmp/icefall/egs/yesno/ASR# ./prepare.sh
2022-08-28 15:42:25 (prepare.sh:24:main) dl_dir: /tmp/icefall/egs/yesno/ASR/download
2022-08-28 15:42:25 (prepare.sh:27:main) Stage 0: Download data
Downloading waves_yesno.tar.gz: 4.49MB [00:45, 104kB/s]                                                                                                       
2022-08-28 15:43:11 (prepare.sh:36:main) Stage 1: Prepare yesno manifest
/root/anaconda3/envs/foo/lib/python3.8/site-packages/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
2022-08-28 15:43:12 (prepare.sh:42:main) Stage 2: Compute fbank for yesno
Traceback (most recent call last):
  File "./local/compute_fbank_yesno.py", line 18, in <module>
    from icefall.utils import get_executor
  File "/tmp/icefall/icefall/__init__.py", line 3, in <module>
    from . import (
  File "/tmp/icefall/icefall/decode.py", line 20, in <module>
    import k2
  File "/root/anaconda3/envs/foo/lib/python3.8/site-packages/k2/__init__.py", line 8, in <module>
    raise ImportError(
ImportError: k2 was built using PyTorch 1.12.0
But you are using PyTorch 1.12.1+cu102 to run it
(foo) root@iZ2zeh94phzrw5upket4jsZ:/tmp/icefall/egs/yesno/ASR#

**Comment by csukuangfj** [comment]
From the error log:
> ImportError: k2 was built using PyTorch 1.12.0

> But you are using PyTorch 1.12.1+cu102 to run it

Please make sure you did not change the PyTorch version after you installed k2.

**Comment by wwfcnu** [comment]
![image](https://user-images.githubusercontent.com/109075309/206362586-95cb6be8-1279-47a5-8523-f54522649901.png)

**Comment by wwfcnu** [comment]
/usr/local/python3.7.10/lib/python3.7/site-packages/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
tools/k2/make_hlg.sh: line 26:  1258 Segmentation fault      (core dumped) python tools/k2/prepare_char.py $lexion_dir/units.txt $lm_dir/wordlist $tgt_dir
Compile lexicon L.pt L_disambig.pt succeeded
/tmp/pip-install-w9q6xu_b/kaldilm_80542c8aeb934a60b2460688478f9031/kaldilm/python/csrc/kaldilm.cc:std::__cxx11::string kaldilm::Arpa2Fst(const string&, const string&, std::__cxx11::string, const string&, const string&, bool, bool, int32_t, const string&, const string&, int32_t):80
[E] Symbol table /home/wangweifei/data/local/hlg/words.txt has no symbol for #0
tools/k2/make_hlg.sh: line 35:  1330 Aborted                 (core dumped) python -m kaldilm --read-symbol-table="$tgt_dir/words.txt" --disambig-symbol='#0' --max-order=3 $lm_dir/lm.arpa > data/lm/G_3_gram.fst.txt
/usr/local/python3.7.10/lib/python3.7/site-packages/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
tools/k2/make_hlg.sh: line 38:  1331 Segmentation fault      (core dumped) python tools/k2/icefall/egs/aishell/ASR/local/compile_hlg.py --lang-dir $tgt_dir
Compile decoding graph HLG.pt succeeded

**Comment by csukuangfj** [comment]
> tools/k2/make_hlg.sh: line 38: 1331 Segmentation fault (core dumped) python


Could you run
```
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
```

Please have a look at https://github.com/k2-fsa/icefall/issues/674

**Comment by wwfcnu** [comment]
> > tools/k2/make_hlg.sh: line 38: 1331 Segmentation fault (core dumped) python
> 
> Could you run
> 
> ```
> export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
> ```
> 
> Please have a look at #674

![image](https://user-images.githubusercontent.com/109075309/206364534-a03ba35c-ffb1-4770-a8fc-bd7d49363563.png)

**Comment by wwfcnu** [comment]
> > > tools/k2/make_hlg.sh: line 38: 1331 Segmentation fault (core dumped) python
> > 
> > 
> > Could you run
> > ```
> > export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please have a look at #674
> 
> ![image](https://user-images.githubusercontent.com/109075309/206364534-a03ba35c-ffb1-4770-a8fc-bd7d49363563.png)

export之后，没有Segmentation fault，但是还是有UserWarning: Failed to import soundfile. 'soundfile' backend is not available.

**Comment by wwfcnu** [comment]
> You can ignore that warning.

ok
