### ISSUE TITLE
tedlium3 train.py error

### ISSUE THREAD

**Issue by shcxlee** [k2-fsa/icefall#579]
I've tried both pruned transducer and transducer models to train, but none of them works.

This is the error report that I got when I ran `./pruned_transducer_stateless/train.py`
````
Traceback (most recent call last):
  File "/icefall/egs/tedlium3/ASR/./pruned_transducer_stateless/train.py", line 783, in <module>
    main()
  File "/icefall/egs/tedlium3/ASR/./pruned_transducer_stateless/train.py", line 774, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/icefall/egs/tedlium3/ASR/pruned_transducer_stateless/train.py", line 665, in run
    num_left = len(train_cuts)
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/lhotse/cut.py", line 5265, in __len__
    return len(self.cuts)
TypeError: object of type 'LazyFilter' has no len()
````

And this is the error report of `./transducer_stateless/train.py`
````

Traceback (most recent call last):
  File "/icefall/egs/tedlium3/ASR/./transducer_stateless/train.py", line 752, in <module>
    main()
  File "/icefall/egs/tedlium3/ASR/./transducer_stateless/train.py", line 743, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/icefall/egs/tedlium3/ASR/transducer_stateless/train.py", line 634, in run
    num_left = len(train_cuts)
  File "/anaconda3/envs/icefall/lib/python3.9/site-packages/lhotse/cut.py", line 5265, in __len__
    return len(self.cuts)
TypeError: object of type 'LazyFilter' has no len()
````

I guess both of them are indicating the same...(`TypeError: object of type 'LazyFilter' has no len()`)

**Comment by pzelasko** [comment]
It looks like the code in the recipe is fairly old and not updated, there are two possible fixes:
1. (preferred) modify `train.py` to not query for `len(train_cuts)`
2. when creating `train_cuts` add `train_cuts = train_cuts.to_eager()` to load everything into memory (and then we can know its `len()`)

**Comment by shcxlee** [comment]
How can I modify `train.py` to not query for `len(train_cuts)`?

**Comment by csukuangfj** [comment]
> How can I modify `train.py` to not query for `len(train_cuts)`?

All you need is to remove the following statements:
https://github.com/k2-fsa/icefall/blob/9ae2f3a3c5a3c2336ca236c984843c0e133ee307/egs/tedlium3/ASR/pruned_transducer_stateless/train.py#L665-L671

**Comment by pzelasko** [comment]
Good point, could you add this?

**Comment by desh2608** [comment]
Added in https://github.com/lhotse-speech/lhotse/pull/817

**Comment by shcxlee** [comment]
> All you need is to remove the following statements:

Now it works! Thanks a lot!

**Comment by csukuangfj** [comment]
@shcxlee 

Would you mind creating a PR with your fixes?

**Comment by shcxlee** [comment]
Sure. Since `train.py` is currently running, I will create a PR as soon as the training is done.

**Comment by shcxlee** [comment]
@csukuangfj I am trying to create a PR but I can't because the latest commit(`f3ad327`) of the synced fork keeps failing. 
````
 ! [remote rejected] tedlium3_pruned -> tedlium3_pruned (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/run-aishell-2022-06-20.yml` without `workflow` scope)
````
![image](https://user-images.githubusercontent.com/113081290/193420503-134e1a35-a891-43f7-8aca-7e5e610054b1.png)

**Comment by csukuangfj** [comment]
Could you describe what you have done before you see the above log?

I looked at your forked icefall repo and found that there is only a master branch and there are no new commits.

**Comment by shcxlee** [comment]
I synced my previous fork and started to get those reports that some checks failed. Nevertheless, I tried to upload my local branch and create PR, but I was not able to push my local branch and got the error message (`[remote rejected]`).

**Comment by csukuangfj** [comment]
Could you show all of the terminal logs?

Note that you have no permission to push to 

https://github.com/k2-fsa/icefall

You can only push to your own fork.

**Comment by shcxlee** [comment]
Yes, I pushed to my fork.
````
git push shcxlee-icefall tedlium3_pruned
Counting objects: 7, done.
Delta compression using up to 32 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 545 bytes | 545.00 KiB/s, done.
Total 7 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/shcxlee/icefall.git
 ! [remote rejected] tedlium3_pruned -> tedlium3_pruned (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/run-aishell-2022-06-20.yml` without `workflow` scope)
error: failed to push some refs to 'https://-@github.com/shcxlee/icefall.git'
````

**Comment by csukuangfj** [comment]
Please use the git protocol, not the https protocol.


That is,

cd /path/to/icefall 
vim .git/config

Then change 

https://github.com/shcxlee/icefall.git

to

git@github.com:shcxlee/icefall.git


Note that you need to configure a ssh key for your GitHub account. Please google it for how to do that.

**Comment by shcxlee** [comment]
I've done it and successfully pushed my branch. I will create PR right now. Thanks a lot!
