### ISSUE TITLE
Calculating WER for male and female with LibriSpeech dataset

### ISSUE THREAD

**Issue by shcxlee** [k2-fsa/icefall#600]
Is there a way to get WERs for male and female speakers separately with the trained (or pretrained) model on LibriSpeech?
I have trained Conformer CTC and pretrained Conformer CTC model. I can also download other pretrained models if necessary.

Thanks to `SPEAKERS.TXT` in LibriSpeech dataset. I was able to get the male/female information on every ID in `test-clean` and `test-other` sets. I've also read the post https://github.com/k2-fsa/icefall/issues/596#issue. However, I am still wondering about ways to figure this out.

**Comment by shcxlee** [comment]
>You split the test set cuts into more test sets, e.g.:

Applying this to actual code,
https://github.com/k2-fsa/icefall/blob/f3ad32777a598de6169274198e418ee95fbf6ddc/egs/librispeech/ASR/pruned_transducer_stateless2/decode.py#L782-L793
https://github.com/k2-fsa/icefall/blob/bf2c4a488e155e1b4947a39a01154fb7e97197f6/egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py#L443-L454
will it be like the following?
```python
 def test_clean_cuts(self) -> CutSet: 
     logging.info("About to get test-clean-male cuts") 
     return load_manifest_lazy( 
         self.args.supervisions[0].gender == "M" / "librispeech_cuts_test-clean-male.jsonl.gz" 
     ) 
```

**Comment by shcxlee** [comment]
I deleted all male speakers' datasets in both `test-other` and `test-clean` folders, but I can still find the ids of male speakers in the error log.

**Comment by csukuangfj** [comment]
> >You split the test set cuts into more test sets, e.g.:
> 
> 
> 
> Applying this to actual code,
> 
> https://github.com/k2-fsa/icefall/blob/bf2c4a488e155e1b4947a39a01154fb7e97197f6/egs/librispeech/ASR/conformer_ctc/decode.py#L785-L795
> 
> https://github.com/k2-fsa/icefall/blob/bf2c4a488e155e1b4947a39a01154fb7e97197f6/egs/librispeech/ASR/tdnn_lstm_ctc/asr_datamodule.py#L443-L454
> 
> will it be like the following?
> 
> ```python
> 
>  def test_clean_cuts(self) -> CutSet: 
> 
>      logging.info("About to get test-clean-male cuts") 
> 
>      return load_manifest_lazy( 
> 
>          self.args.supervisions[0].gender == "M" / "librispeech_cuts_test-clean-male.jsonl.gz" 
> 
>      ) 
> 
> ```

I suggest that you add that to decode.py.

You can follow what we are doing with "filter" in train.py

**Comment by shcxlee** [comment]
I've changed the code like the following:
```python
    test_clean_cuts = librispeech.test_clean_cuts()
    test_other_cuts = librispeech.test_other_cuts()

    def is_male(c: Cut):
        # Keep only male
        return c.supervisions[0].gender == "M"

    def is_female(c: Cut):
        # Keep only female
        return c.supervisions[0].gender == "F"

    test_clean_cuts_male = test_clean_cuts.filter(is_male)
    test_clean_cuts_female = test_clean_cuts.filter(is_female)

    test_clean_dl = librispeech.test_dataloaders(test_clean_cuts_male)
    test_other_dl = librispeech.test_dataloaders(test_other_cuts)
```

and got this error message when I ran `decode.py`
````
INFO [asr_datamodule.py:451] About to get test-other cuts
Traceback (most recent call last):
  File "./conformer_ctc/decode.py", line 832, in <module>
    main()
  File "/anaconda3/envs/icefall/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./conformer_ctc/decode.py", line 800, in main
    test_clean_dl = librispeech.test_dataloaders(test_clean_cuts_male)
  File "/icefall/egs/librispeech/ASR/conformer_ctc/asr_datamodule.py", line 393, in test_dataloaders
    sampler = DynamicBucketingSampler(
  File "/anaconda3/envs/icefall/lib/python3.8/site-packages/lhotse/dataset/sampling/dynamic_bucketing.py", line 146, in __init__
    self.duration_bins = estimate_duration_buckets(
  File "/anaconda3/envs/icefall/lib/python3.8/site-packages/lhotse/dataset/sampling/dynamic_bucketing.py", line 274, in estimate_duration_buckets
    assert num_buckets <= durs.shape[0], (
AssertionError: The number of buckets (10) must be smaller than or equal to the number of cuts (0).
````

**Comment by csukuangfj** [comment]
Could you print out one of the cutset to see what is contained in the supervisions?
