### ISSUE TITLE
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by kobenaxie** [k2-fsa/icefall#641]
Try to train conv_emformer2 to fix #616 , but get cudaErrorIllegalAddress. Trianing conformer is normal.

Env:
cuda-11.2
A100
torch=1.10.2+cu111
torchaudio=0.10.2+cu111
```
Traceback (most recent call last):
  File "./conv_emformer_transducer_stateless2/train.py", line 1145, in <module>
    main()
  File "./conv_emformer_transducer_stateless2/train.py", line 1138, in main
    run(rank=0, world_size=1, args=args)
  File "./conv_emformer_transducer_stateless2/train.py", line 1024, in run
    scan_pessimistic_batches_for_oom(
  File "./conv_emformer_transducer_stateless2/train.py", line 1112, in scan_pessimistic_batches_for_oom
    loss.backward()
  File "/home/disk1/xjl/anaconda3/envs/k2/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/disk1/xjl/anaconda3/envs/k2/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by csukuangfj** [comment]
Could you switch to another CUDA version instead of CUDA 11.1? E.g., you can use cuda 10.2.

**Comment by kobenaxie** [comment]
Cuda-10.2 support A100 ? I did not test before, trying to higher cuda version like 11.4 or 11.6

**Comment by csukuangfj** [comment]
> Cuda-10.2 support A100 ? I did not test before, trying to higher cuda version like 11.4 or 11.6 

Yes, as long as it's not CUDA 11.1
