### ISSUE TITLE
SPGISpeech:  AttributeError: 'NoneType' object has no attribute 'recording_id'

### ISSUE THREAD

**Issue by jtrmal** [k2-fsa/icefall#643]
Any suggestions what is wrong, @desh2608 ? I didn't do any modifications and I think I'm reasonable up to date with lhotse
```
lhotse cut simple -r data/manifests/recordings_musan.jsonl.gz data/manifests/cuts_musan_raw.jsonl.gz
Traceback (most recent call last):
  File "/home/jtrmal/.conda/envs/k2/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "/home/jtrmal/.conda/envs/k2/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jtrmal/.conda/envs/k2/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jtrmal/.conda/envs/k2/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jtrmal/.conda/envs/k2/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jtrmal/.conda/envs/k2/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jtrmal/.conda/envs/k2/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jtrmal/projects/lhotse/lhotse/bin/modes/cut.py", line 71, in simple
    CutSet.from_manifests(
  File "/home/jtrmal/projects/lhotse/lhotse/cut/set.py", line 309, in from_manifests
    return create_cut_set_lazy(
  File "/home/jtrmal/projects/lhotse/lhotse/cut/set.py", line 2618, in create_cut_set_lazy
    sups, supervisions = _takewhile(
  File "/home/jtrmal/projects/lhotse/lhotse/cut/set.py", line 2660, in _takewhile
    if predicate(item):
  File "/home/jtrmal/projects/lhotse/lhotse/cut/set.py", line 2619, in <lambda>
    supervisions, lambda s: s.recording_id == recording.id
AttributeError: 'NoneType' object has no attribute 'recording_id'
````

**Comment by desh2608** [comment]
Can you share the path to your `recordings_musan.jsonl.gz`. I can check locally.

**Comment by desh2608** [comment]
I think it might be a Lhotse bug. The lambda should be `lambda s: s is not None and s.recording_id == recording.id`. This was not caught when I prepared the recipe because at that time, the default behaviour for `lhotse cut simple` was to use eager mode, which works fine. But the behaviour is now changed to lazy mode, which has the bug. You can verify that it works well in eager mode by changing your command to: `lhotse cut simple --force-eager -r data/manifests/recordings_musan.jsonl.gz data/manifests/cuts_musan_raw.jsonl.gz`.

Would you mind trying with the modified lambda and opening a PR in Lhotse if it works?

**Comment by jtrmal** [comment]
thanks for figuring this out. I will try
y.

**Comment by jtrmal** [comment]
I can confirm it runs as expected (?) with the fix
