### ISSUE TITLE
Fixes for segfault

### ISSUE THREAD

**Issue by csukuangfj** [k2-fsa/icefall#674]
In the last few days, a few people (>3) have encountered the following error after updating their lhotse to the latest version:
```
Segmentation fault (core dump)
```
when they try to run one of the python scripts from icefall.

After using
```bash
gdb --args python xxx.py

(gdb) run
(gdb) backtrace
```

They get
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fff75d00dd1 in google::protobuf::internal::ReflectionOps::FindInitializationErrors(google::protobuf::Message const&, std::string const&, std::vector<std::string, std::allocator<std::string> >*) ()
   from /xxxxxx/lib/python3.8/site-packages/google/protobuf/pyext/_message.cpython-38-x86_64-linux-gnu.so

(gdb) backtrace
#0  0x00007fff75d00dd1 in google::protobuf::internal::ReflectionOps::FindInitializationErrors(google::protobuf::Message const&, std::string const&, std::vector<std::string, std::allocator<std::string> >*) ()
   from /xxxxxx/lib/python3.8/site-packages/google/protobuf/pyext/_message.cpython-38-x86_64-linux-gnu.so
#1  0x00007fff75cf8d05 in google::protobuf::Message::FindInitializationErrors(std::vector<std::string, std::allocator<std::string> >*) const ()
   from /xxxxxx/lib/python3.8/site-packages/google/protobuf/pyext/_message.cpython-38-x86_64-linux-gnu.so
```

The `tensorboard` python package introduces the dependency on `protobuf` and the error is caused by
https://github.com/timpalpant/pypprof/issues/2#issuecomment-873607072

---

The fix is to set the following environment variable before running any python scripts:
```bash
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
```

**Comment by csukuangfj** [comment]
I suggest that we add
```
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
```
to `prepare.sh` of each recipe.

**Comment by zhuangweiji** [comment]
> I suggest that we add
> 
> ```shell
> export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
> ```
> 
> to `prepare.sh` of each recipe.

cool! thanks!

**Comment by naxingyu** [comment]
It works for `Aborted (core dumped)` too.
