### ISSUE TITLE
distillation 

### ISSUE THREAD

**Issue by BuaaAlban** [k2-fsa/icefall#779]
`
sh distillation_with_hubert.sh

2022-12-20 17:34:00,032 WARNING [train.py:988] Exclude cut with ID 7859-102521-0017-21930-0_sp0.9 from training. Duration: 27.25
Traceback (most recent call last):
  File "./pruned_transducer_stateless6/train.py", line 1153, in <module>
    main()
  File "./pruned_transducer_stateless6/train.py", line 1146, in main
    run(rank=0, world_size=1, args=args)
  File "./pruned_transducer_stateless6/train.py", line 1033, in run
    scan_pessimistic_batches_for_oom(
  File "./pruned_transducer_stateless6/train.py", line 1112, in scan_pessimistic_batches_for_oom
    loss, _ = compute_loss(
  File "./pruned_transducer_stateless6/train.py", line 616, in compute_loss
    codebook_indexes, _ = extract_codebook_indexes(batch)
  File "./pruned_transducer_stateless6/train.py", line 569, in extract_codebook_indexes
    codebook_indexes, codebook_indexes_lens = collate_custom_field(
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/dataset/collation.py", line 239, in collate_custom_field
    first_manifest = getattr(cuts[0], field)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/cut.py", line 910, in __getattr__
    raise AttributeError(f"No such attribute: {name}")
AttributeError: No such attribute: codebook_indexes
`

I have downloaded the index manually and do the stage 2 manually,  though I met report that "fairseq not installed". I think it's okay if I use extracted indexes.
In stage 3, I meet the above AttributeError, does this mean that my downloaded data has problem or I should reinstall lhost?

**Comment by marcoyang1998** [comment]
Could you please show the full training command?

**Comment by BuaaAlban** [comment]
This is my recording，and the scripts is uploaded here, thanks~
[distillation_with_hubert.txt](https://github.com/k2-fsa/icefall/files/10267302/distillation_with_hubert.txt)

`#手动下载code index和模型，实际略过用模型提取了
(base) bokangz@xcdl210036:/group/dphi_algo_scratch_02/bokangz/exp/k2/pruned_transducer_stateless6/exp$ ln -s /group/dphi_algo_scratch_02/bokangz/data/hubert_k2/hubert_xtralarge_ll60k_finetune_ls960.pt hubert_models/
(base) bokangz@xcdl210036:/group/dphi_algo_scratch_02/bokangz/exp/k2/pruned_transducer_stateless6/exp$ ln -s /group/dphi_algo_scratch_02/bokangz/data/hubert_k2/dict.ltr.txt hubert_models/
(base) bokangz@xcdl210036:/group/dphi_algo_scratch_02/bokangz/exp/k2/pruned_transducer_stateless6/exp$ cp ../../../../data/hubert_k2/pruned_transducer_stateless6_hubert_xtralarge_ll60k_finetune_ls960/ download_codebook -r
#用单卡测试一下子k2) bokangz@xcdl210036:/proj/xcdhdstaff1/bokangz/project/k2/icefall-master/egs/librispeech/ASR$ sh distillation_with_hubert.sh
ModuleNotFoundError: No module named 'icefall'
(k2) bokangz@xcdl210036:/proj/xcdhdstaff1/bokangz/project/k2/icefall/egs/librispeech/ASR$ export PYTHONPATH=/proj/xcdhdstaff1/bokangz/project/k2/icefall:$PYTHONPATH


#找不着librispeech的原始数据
(k2) bokangz@xcdl210036:/proj/xcdhdstaff1/bokangz/project/k2/icefall/egs/librispeech/ASR$ ln -s /proj/xcdhdstaff1/bokangz/project/k2/icefall/egs/librispeech/ASR/data/fbank/* data/vq_fbank/ 然后再run sh distillation_with_hubert.sh 可以找到数据了
Traceback (most recent call last): 
File "./pruned_transducer_stateless6/train.py", line 1153, in <module> 
main() 
File "./pruned_transducer_stateless6/train.py", line 1146, in main 
run(rank=0, world_size=1, args=args) 
File "./pruned_transducer_stateless6/train.py", line 1033, in run 
scan_pessimistic_batches_for_oom( 
File "./pruned_transducer_stateless6/train.py", line 1112, in scan_pessimistic_batches_for_oom 
loss, _ = compute_loss( 
File "./pruned_transducer_stateless6/train.py", line 616, in compute_loss 
codebook_indexes, _ = extract_codebook_indexes(batch) 
File "./pruned_transducer_stateless6/train.py", line 569, in extract_codebook_indexes 
codebook_indexes, codebook_indexes_lens = collate_custom_field(
File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/dataset/collation.py", line 239, in collate_custom_field
first_manifest = getattr(cuts[0], field)
File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/cut.py", line 910, in __getattr__
raise AttributeError(f"No such attribute: {name}")
AttributeError: No such attribute: codebook_indexes`

**Comment by marcoyang1998** [comment]
I assume that you didn't execute the last section in stage 2, is that right?

**Comment by BuaaAlban** [comment]
Yes, you are right, It failed as I didn't install fairseq,  is that the reason?
And I check the data in data/vq_fbank/librispeech_cuts_train-clean-100-vq.jsonl.gz
It has keyword "codebook_indexes" in it

**Comment by marcoyang1998** [comment]
You will have to execute the last section in stage 2 because it merges `data/vq_fbank/librispeech_cuts_train-clean-100-vq.jsonl.gz` with the original manifest so that the original manifest will contain the field "codebook_indexes".

**Comment by BuaaAlban** [comment]
Ok, I see. thanks a lot ~
And I will check the method 
`    extractor.reuse_manifests()
    extractor.join_manifests()
`

**Comment by BuaaAlban** [comment]
During  the last section in stage 2, I have met with this error, can you please help to take a look?
`> /proj/xcdhdstaff1/bokangz/project/k2/icefall/egs/librispeech/ASR/pruned_transducer_stateless6/vq_utils.py(249)join_manifests()
-> cuts_vq = cuts_vq.sort_like(cuts_ori)
(Pdb) c
Traceback (most recent call last):
  File "./pruned_transducer_stateless6/extract_codebook_index.py", line 94, in <module>
    main()
  File "./pruned_transducer_stateless6/extract_codebook_index.py", line 90, in main
    extractor.join_manifests()
  File "/proj/xcdhdstaff1/bokangz/project/k2/icefall/egs/librispeech/ASR/pruned_transducer_stateless6/vq_utils.py", line 249, in join_manifests
    cuts_vq = cuts_vq.sort_like(cuts_ori)
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/cut.py", line 4087, in sort_like
    assert set(self.ids) == set(
AssertionError: sort_like() expects both CutSet's to have identical cut IDs.
`

**Comment by marcoyang1998** [comment]
It seems that the IDs of the cuts from the original manifest and the downloaded vq manifest do not match.

Could you please check the length of the two manifests? You can do this by 
```
from lhotse import load_manifest
manifest_dir = "/path/to/manifest"
cuts = load_manifest(manifest_dir)
print(len(cuts))
```

**Comment by BuaaAlban** [comment]
```
4083        def sort_like(self, other: "CutSet") -> "CutSet":
4084            """
4085            Sort the CutSet according to the order of cut IDs in ``other`` and return the result.
4086            """
4087 ->         assert set(self.ids) == set(
4088                other.ids
4089            ), "sort_like() expects both CutSet's to have identical cut IDs."
4090            return CutSet.from_cuts(self[cid] for cid in other.ids)
(Pdb) len(set(self.ids))
85617
(Pdb) len(set(other.ids))
85617
```

**Comment by BuaaAlban** [comment]
```
(Pdb) len(set(other.ids)|set(self.ids))
171234
(Pdb) 85617*2
171234
(Pdb) len(set(other.ids)&set(self.ids))
0
```

**Comment by BuaaAlban** [comment]
I  got the manifest of original by prepare.sh in librispeech
And the manifest of vq is downloaded from https://huggingface.co/Zengwei/pruned_transducer_stateless6_hubert_xtralarge_ll60k_finetune_ls960

Could you please share one so that I can know which file go wrong?

**Comment by marcoyang1998** [comment]
Could you please print out a few samples from `self.ids` and `other.ids`?

**Comment by BuaaAlban** [comment]
![image](https://user-images.githubusercontent.com/25258181/209104850-d75130ac-0812-4aa8-9471-96e5b17570f7.png)
![image](https://user-images.githubusercontent.com/25258181/209104878-7be39296-a15b-45a4-ba75-4ecbef8831d1.png)

**Comment by marcoyang1998** [comment]
It seems that lhtose has changed its naming convention. The original manifest you generated with `prepare.sh` is using the latest lhtose, whereas the manifest from huggingface are created with a previous version of lhotse. This results in the ID mismatch.

I will upload a new version to huggingface soon.

**Comment by marcoyang1998** [comment]
@BuaaAlban 
Could you please show me the results of the following command? lhotse is changing constantly and I don't want to upload another wrong version...
```python
from lhotse import load_manifest
manfiest_dir = "data/fbank/librispeech_cuts_train-clean-100.jsonl.gz" # the path to your clean-100 manifest
cuts = load_manifest(manfiest_dir)
ids = sorted(cuts.ids)
print(ids[:6])
```

**Comment by BuaaAlban** [comment]
I want to check the version of lhoste, but I failed. So I got the ids in this stupid way which should be the same. 
```
> /proj/xcdhdstaff1/bokangz/project/k2/icefall/egs/librispeech/ASR/pruned_transducer_stateless6/vq_utils.py(249)join_manifests()
-> cuts_vq = cuts_vq.sort_like(cuts_ori)
(Pdb) l
244                 )
245                 cuts_vq = load_manifest(vq_manifest_path)
246                 cuts_ori = load_manifest(ori_manifest_path)
247                 import pdb
248                 pdb.set_trace()
249  ->             cuts_vq = cuts_vq.sort_like(cuts_ori)
250                 for cut_idx, (cut_vq, cut_ori) in enumerate(zip(cuts_vq, cuts_ori)):
251                     assert cut_vq.id == cut_ori.id
252                     cut_ori.codebook_indexes = cut_vq.codebook_indexes
253  
254                 CutSet.from_cuts(cuts_ori).to_jsonl(dst_vq_manifest_path)
(Pdb) lhoste.__version__
*** NameError: name 'lhoste' is not defined
(Pdb) import lhoste
*** ModuleNotFoundError: No module named 'lhoste'
(Pdb) ori_manifest_path
PosixPath('data/fbank/librispeech_cuts_train-clean-100.jsonl.gz')
(Pdb) sorted(cuts_ori.ids)[:6]
['103-1240-0000-6586-0', '103-1240-0000-6586-0_sp0.9', '103-1240-0000-6586-0_sp1.1', '103-1240-0001-6587-0', '103-1240-0001-6587-0_sp0.9', '103-1240-0001-6587-0_sp1.1']

```

```
(k2) bokangz@xcdl210036:/proj/xcdhdstaff1/bokangz/project/k2/icefall/egs/librispeech/ASR$ python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(k2) bokangz@xcdl210036:/proj/xcdhdstaff1/bokangz/project/k2/icefall/egs/librispeech/ASR$ python3
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lhoste
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'lhoste'
```

**Comment by marcoyang1998** [comment]
Please have a look at this huggingface repository https://huggingface.co/marcoyang/pruned_transducer_stateless6_hubert_xtralarge_ll60k_finetune_ls960/tree/main. I will make a PR for this.

I'm using lhotse version 1.11.0, so I recommend you to re-run `prepare.sh` with the same version of lhotse for manifest generation and then execute `distillation_with_hubert.sh`. You can find your version of lhotse by printing `lhotse.verion.__version__`.

**Comment by BuaaAlban** [comment]
I am using hotse 1.4.0, I will try the latest manifest, and if I will re-run the prepare.sh if it still mismatch

**Comment by marcoyang1998** [comment]
Could you please try to upgrade lhotse to 1.11.0 and rerun `distillation_with_hubert.sh` with the latest master of icefall? We managed to solve the ID matching in a recent PR #790 so probably you won't need to run `prepare.sh` again.

**Comment by BuaaAlban** [comment]
Actually the process will take a little time because I have no internet access on my server, I will replace with your codeindex and change the code in vq_utils.py as in the PR to do some postprocess. I assume that I don't need to upgrade lhotse in this way and just try the distillation_with_hubert.sh is okay.

**Comment by BuaaAlban** [comment]
It seems work with modification as in your PR (currently it's processing monocut with some time  mismatch warning).
BTW, the loading of vq seems to be hard code as I changed the exp_dir it will report some path error.
```Traceback (most recent call last):                                                                                                                                
  File "./pruned_transducer_stateless6/train.py", line 1155, in <module>                                                                                   
    main()                                                                                                                                                     
  File "./pruned_transducer_stateless6/train.py", line 1148, in main                                                                                                
    run(rank=0, world_size=1, args=args)                                                                                                                                 
  File "./pruned_transducer_stateless6/train.py", line 978, in run                                                                                                        
    train_cuts = librispeech.train_clean_100_cuts()                                                                                                                                     
  File "./pruned_transducer_stateless6/train.py", line 1114, in scan_pessimistic_batches_for_oom                                                                  
    loss, _ = compute_loss(                                                                                                                               
  File "./pruned_transducer_stateless6/train.py", line 616, in compute_loss                                                                         
    codebook_indexes, _ = extract_codebook_indexes(batch)                                                                           
  File "./pruned_transducer_stateless6/train.py", line 569, in extract_codebook_indexes                                                                                                          
    codebook_indexes, codebook_indexes_lens = collate_custom_field(                                                                                                                              
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/dataset/collation.py", line 267, in collate_custom_field                                                  
    arrs = [torch.from_numpy(c.load_custom(field)) for c in cuts]                                                                                                                            
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/dataset/collation.py", line 267, in <listcomp>                                                                             
    arrs = [torch.from_numpy(c.load_custom(field)) for c in cuts]                                                             
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/cut.py", line 942, in load_custom                                                                                           
    return value.load(start=self.start, duration=self.duration)                                                                    
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/array.py", line 206, in load                                                                                                
    storage = get_reader(self.array.storage_type)(self.array.storage_path)                  
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/features/io.py", line 408, in __init__                                                                                      
    self.hdf = lookup_cache_or_open(storage_path)                                                                                                                                                
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/features/io.py", line 377, in lookup_cache_or_open                                                                          
    return h5py.File(storage_path, "r")                                                                                                                             
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/h5py/_hl/files.py", line 533, in __init__                                                                                          
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)                                                                                                                                              
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/k2/lib/python3.8/site-packages/h5py/_hl/files.py", line 226, in make_fid                                                                                          
    fid = h5f.open(name, flags, fapl=fapl)                                                                                                                                                                         
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper                                                                                                                                            
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper                                                                                                                                           
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open                                                                                                                                                                  
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'pruned_transducer_stateless6/exp/vq/hubert_xtralarge_ll60k_finetune_ls960/splits4/clean-100-3.h5', errno = 2, error message = 'No su
ch file or directory', flags = 0, o_flags = 0) ```

**Comment by marcoyang1998** [comment]
>currently it's processing monocut with some time mismatch warning
This is normal. This is caused by the padding and subsampling in `HuBERT`.

> loading of vq seems to be hard code
Do you mean `exp_dir` in `distillation_with_hubert.sh`? I think you won't encounter this problem if you **only** run stage 3 with a different `exp_dir`. Could you please have a try?

**Comment by BuaaAlban** [comment]
Yes I mean `exp_dir` in `distillation_with_hubert.sh`.  It seems to be trying to load file from the default path instead of the exp_dir I set.

No card to test now, I will update the result to you once I have a try.

**Comment by BuaaAlban** [comment]
I didn't encounter the problem if I only run stage 3 with a different `exp_dir` , and it do work with modification as in your PR without updating lhotse.

**Comment by BuaaAlban** [comment]
BTW, do you have a paper for the distillation exp? I only see some blogs

**Comment by marcoyang1998** [comment]
Please have a look at this https://arxiv.org/abs/2211.00508

**Comment by suzhenghang** [comment]
@marcoyang1998  Teacher是使用finetuned hubert，是否有尝试过将Teacher 替换成一个比Student更大的model（和student结构一致，但是参数量更大，字准率更高）。或者说这样是否make sense?
