### ISSUE TITLE
Failed to run YesNo recipe

### ISSUE THREAD

**Issue by AmirHussein96** [k2-fsa/icefall#794]
After installing lhotse, k2, kladifeat and icefall successfully 
I got the following error from kaldilm-1.14

```
2022-12-27 10:59:39 (prepare.sh:27:main) dl_dir: /speech/toolkits/icefall/egs/yesno/ASR/download
2022-12-27 10:59:39 (prepare.sh:30:main) Stage 0: Download data
Downloading waves_yesno.tar.gz: 4.49MB [00:12, 365kB/s]                                                                                                                                                    
2022-12-27 10:59:52 (prepare.sh:39:main) Stage 1: Prepare yesno manifest
2022-12-27 10:59:53 (prepare.sh:45:main) Stage 2: Compute fbank for yesno
2022-12-27 10:59:53,673 INFO [compute_fbank_yesno.py:65] Processing train
Extracting and storing features: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:00<00:00, 570.77it/s]
2022-12-27 10:59:53,841 INFO [compute_fbank_yesno.py:65] Processing test
Extracting and storing features: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 801.86it/s]
2022-12-27 10:59:54 (prepare.sh:51:main) Stage 3: Prepare lang
2022-12-27 10:59:54 (prepare.sh:63:main) Stage 4: Prepare G
Traceback (most recent call last):
  File "/speech/toolkits/espnet/tools/anaconda/envs/k2/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/speech/toolkits/espnet/tools/anaconda/envs/k2/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/speech/toolkits/espnet/tools/anaconda/envs/k2/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/speech/toolkits/espnet/tools/anaconda/envs/k2/lib/python3.8/site-packages/kaldilm/__init__.py", line 1, in <module>
    from .arpa2fst import arpa2fst
  File "/speech/toolkits/espnet/tools/anaconda/envs/k2/lib/python3.8/site-packages/kaldilm/arpa2fst.py", line 3, in <module>
    import _kaldilm
ImportError: /speech/toolkits/espnet/tools/anaconda/envs/k2/lib/python3.8/site-packages/libkaldilm_fst.so.6: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
```

Environment details:
`python3 -m torch.utils.collect_env`

```
Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.18.0
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Ti
Nvidia driver version: 525.60.13
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.7.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.7.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.7.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.7.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.7.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.7.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.12.0+cu113
[pip3] torchaudio==0.12.0+cu113
[pip3] torchvision==0.13.0+cu113
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] kaldifeat                 1.22            cuda11.3_py3.8_torch1.12.0    kaldifeat
[conda] mkl                       2022.1.0           hc2b9512_224  
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch                   1.12.0          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.12.0+cu113             pypi_0    pypi
[conda] torchaudio                0.12.0+cu113             pypi_0    pypi
[conda] torchvision               0.13.0+cu113             pypi_0    pypi
```

k2 details: `python -m k2.version`

```
python -m k2.version
Collecting environment information...

k2 version: 1.23.2
Build type: Debug
Git SHA1: a34171ed85605b0926eebbd0463d059431f4f74a
Git date: Tue Dec 13 11:06:38 2022
Cuda used to build k2: 11.3
cuDNN used to build k2: 8.7.0
Python version used to build k2: 3.8
OS used to build k2: Ubuntu 20.04.5 LTS
CMake version: 3.18.0
GCC version: 9.4.0
CMAKE_CUDA_FLAGS:  --compiler-options -rdynamic --compiler-options -lineinfo -Wno-deprecated-gpu-targets   -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -DONNX_NAMESPACE=onnx_c2 -gencode arch=compute_86,code=sm_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas 
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
PyTorch version used to build k2: 1.12.0
PyTorch is using Cuda: 11.3
NVTX enabled: True
With CUDA: True
Disable debug: False
Sync kernels : False
Disable checks: False
Max cpu memory allocate: 214748364800 bytes (or 200.0 GB)
k2 abort: False
__file__: /speech/toolkits/k2/k2/python/k2/version/version.py
_k2.__file__: /speech/toolkits/k2/build_debug/lib/_k2.cpython-38-x86_64-linux-gnu.so
```

**Comment by AmirHussein96** [comment]
Ok I tried installing kaldilm 1.11 and it worked

**Comment by AmirHussein96** [comment]
I managed to run the 
./prepare.sh
 
```
2022-12-27 23:58:45 (prepare.sh:27:main) dl_dir: /speech/toolkits/icefall/egs/yesno/ASR/download
2022-12-27 23:58:45 (prepare.sh:30:main) Stage 0: Download data
2022-12-27 23:58:45 (prepare.sh:39:main) Stage 1: Prepare yesno manifest
2022-12-27 23:58:49 (prepare.sh:45:main) Stage 2: Compute fbank for yesno
2022-12-27 23:58:51,113 INFO [compute_fbank_yesno.py:65] Processing train
Extracting and storing features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:03<00:00, 22.52it/s]
2022-12-27 23:58:55,123 INFO [compute_fbank_yesno.py:65] Processing test
Extracting and storing features: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 76.81it/s]
2022-12-27 23:58:55 (prepare.sh:51:main) Stage 3: Prepare lang
2022-12-27 23:58:56 (prepare.sh:63:main) Stage 4: Prepare G
/tmp/pip-install-g6q3nskt/kaldilm_ecf2aef43c634481b86fa201650f6c42/kaldilm/csrc/arpa_file_parser.cc:void kaldilm::ArpaFileParser::Read(std::istream&):79
[I] Reading \data\ section.
/tmp/pip-install-g6q3nskt/kaldilm_ecf2aef43c634481b86fa201650f6c42/kaldilm/csrc/arpa_file_parser.cc:void kaldilm::ArpaFileParser::Read(std::istream&):140
[I] Reading \1-grams: section.
2022-12-27 23:58:56 (prepare.sh:89:main) Stage 5: Compile HLG
2022-12-27 23:58:57,448 INFO [compile_hlg.py:123] Processing data/lang_phone
2022-12-27 23:58:57,448 INFO [lexicon.py:171] Converting L.pt to Linv.pt
2022-12-27 23:58:59,530 INFO [compile_hlg.py:48] Building ctc_topo. max_token_id: 3
2022-12-27 23:58:59,531 INFO [compile_hlg.py:52] Loading G.fst.txt
2022-12-27 23:58:59,549 INFO [compile_hlg.py:62] Intersecting L and G
2022-12-27 23:58:59,662 INFO [compile_hlg.py:64] LG shape: (4, None)
2022-12-27 23:58:59,662 INFO [compile_hlg.py:66] Connecting LG
2022-12-27 23:58:59,662 INFO [compile_hlg.py:68] LG shape after k2.connect: (4, None)
2022-12-27 23:58:59,662 INFO [compile_hlg.py:70] <class 'torch.Tensor'>
2022-12-27 23:58:59,662 INFO [compile_hlg.py:71] Determinizing LG
2022-12-27 23:58:59,714 INFO [compile_hlg.py:74] <class '_k2.ragged.RaggedTensor'>
2022-12-27 23:58:59,714 INFO [compile_hlg.py:76] Connecting LG after k2.determinize
2022-12-27 23:58:59,714 INFO [compile_hlg.py:79] Removing disambiguation symbols on LG
2022-12-27 23:58:59,780 INFO [compile_hlg.py:90] LG shape after k2.remove_epsilon: (6, None)
2022-12-27 23:58:59,781 INFO [compile_hlg.py:95] Arc sorting LG
2022-12-27 23:58:59,781 INFO [compile_hlg.py:98] Composing H and LG
2022-12-27 23:58:59,783 INFO [compile_hlg.py:105] Connecting LG
2022-12-27 23:58:59,783 INFO [compile_hlg.py:108] Arc sorting LG
2022-12-27 23:58:59,784 INFO [compile_hlg.py:110] HLG.shape: (8, None)
2022-12-27 23:58:59,784 INFO [compile_hlg.py:126] Saving HLG.pt to data/lang_phone
```
But when I run the training `python tdnn/train.py` 
it gives me 
`Segmentation fault (core dumped)`
any ideas?

**Comment by AmirHussein96** [comment]
Oh I found the solution https://github.com/k2-fsa/icefall/issues/674

**Comment by csukuangfj** [comment]
> Oh I found the solution https://github.com/k2-fsa/icefall/issues/674

So have you fixed it?

**Comment by AmirHussein96** [comment]
yes
