### ISSUE TITLE
k2 compiled without CUDA support

### ISSUE THREAD

**Issue by treya-lin** [k2-fsa/icefall#850]
Hi when installing k2 for icefall, I encountered with this error saying my k2 was compiled without CUDA support

Here is how I installed k2:
```
conda activate env_k2
git clone https://github.com/k2-fsa/k2.git
cd k2
export K2_MAKE_ARGS="-j6"
python3 setup.py install
```
(actually I git cloned this image (git clone https://hub.yzuu.cf/k2-fsa/k2.git) because github is too slow from mainland. Shouldn't be a problem?)

after installing k2 I ran the test and it worked fine.
```
python
Python 3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import k2
>>> 
... 0 1 -1 0.1
... 1
... '''
>>> fsa = k2.Fsa.from_str(s)
>>> print(fsa)
k2.Fsa: 0 1 -1 0.1
1
properties_str = "Valid|Nonempty|TopSorted|TopSortedAndAcyclic|ArcSorted|ArcSortedAndDeterministic|EpsilonFree|MaybeAccessible|MaybeCoaccessible".
```

But the error appeared when I was testing if icefall was succesfually installed. Below are the commands and the error message.
```
cd icefall
python -m pip install -r requirements.txt
icefall_root=$(readlink -f .)
export PYTHONPATH=$icefall_root:$PYTHONPATH
cd $workdir/icefall
cd egs/yesno/ASR
./prepare.sh
./tdnn/train.py
```
Error:
```
/home/user/anaconda3/envs/env_k2/lib/python3.8/site-packages/torchaudio/backend/utils.py:53: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(
2023-01-17 11:47:19,511 INFO [train.py:481] Training started
2023-01-17 11:47:19,511 INFO [train.py:482] {'exp_dir': PosixPath('tdnn/exp'), 'lang_dir': PosixPath('data/lang_phone'), 'lr': 0.01, 'feature_dim': 23, 'weight_decay': 1e-06, 'start_epoch': 0, 'best_train_loss': inf, 'best_valid_loss': inf, 'best_train_epoch': -1, 'best_valid_epoch': -1, 'batch_idx_train': 0, 'log_interval': 10, 'reset_interval': 20, 'valid_interval': 10, 'beam_size': 10, 'reduction': 'sum', 'use_double_scores': True, 'world_size': 1, 'master_port': 12354, 'tensorboard': True, 'num_epochs': 15, 'seed': 42, 'feature_dir': PosixPath('data/fbank'), 'max_duration': 30.0, 'bucketing_sampler': False, 'num_buckets': 10, 'concatenate_cuts': False, 'duration_factor': 1.0, 'gap': 1.0, 'on_the_fly_feats': False, 'shuffle': False, 'return_cuts': True, 'num_workers': 2, 'env_info': {'k2-version': '1.23.3', 'k2-build-type': 'Release', 'k2-with-cuda': False, 'k2-git-sha1': 'eda5d0d49d881468375186a37ae591fe1874732c', 'k2-git-date': 'Tue Jan 10 15:21:30 2023', 'lhotse-version': '1.13.0.dev+git.0335d5c.clean', 'torch-version': '1.7.1', 'torch-cuda-available': True, 'torch-cuda-version': '11.0', 'python-version': '3.8', 'icefall-git-branch': 'master', 'icefall-git-sha1': '142420b-clean', 'icefall-git-date': 'Wed Jan 11 16:45:24 2023', 'icefall-path': '/home/user/workspace/asr_space/next_gen_kaldi/icefall', 'k2-path': '/home/user/anaconda3/envs/env_k2/lib/python3.8/site-packages/k2-1.23.3.dev20230111+cpu.torch1.7.1-py3.8-linux-x86_64.egg/k2/__init__.py', 'lhotse-path': '/home/user/workspace/asr_space/next_gen_kaldi/lhotse/lhotse/__init__.py', 'hostname': 'mq2.example.com', 'IP address': '192.168.4.169'}}
2023-01-17 11:47:19,514 INFO [lexicon.py:168] Loading pre-compiled data/lang_phone/Linv.pt
2023-01-17 11:47:19,517 INFO [train.py:495] device: cuda:0
[F] /home/user/workspace/asr_space/k2/k2/csrc/device_guard.h:66:static int32_t k2::DeviceGuard::GetDevice() k2 compiled without CUDA support


[ Stack-Trace: ]
/home/user/anaconda3/envs/env_k2/lib/python3.8/site-packages/k2-1.23.3.dev20230111+cpu.torch1.7.1-py3.8-linux-x86_64.egg/k2/lib/libk2_log.so(k2::internal::GetStackTrace()+0x4f) [0x7fe35602512f]
/home/user/anaconda3/envs/env_k2/lib/python3.8/site-packages/k2-1.23.3.dev20230111+cpu.torch1.7.1-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x43a7a) [0x7fe356acaa7a]
/home/user/anaconda3/envs/env_k2/lib/python3.8/site-packages/k2-1.23.3.dev20230111+cpu.torch1.7.1-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x96ecd) [0x7fe356b1decd]
/home/user/anaconda3/envs/env_k2/lib/python3.8/site-packages/k2-1.23.3.dev20230111+cpu.torch1.7.1-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0xe3139) [0x7fe356b6a139]
python3(PyCFunction_Call+0x52) [0x4e0212]
python3(_PyObject_MakeTpCall+0x3eb) [0x4d0eab]
python3() [0x4e897b]
python3(_PyEval_EvalFrameDefault+0x4d38) [0x4cbd18]
python3() [0x4e8717]
python3(_PyEval_EvalFrameDefault+0x4d38) [0x4cbd18]
python3(_PyEval_EvalCodeWithName+0x1f5) [0x4c5e95]
python3(_PyFunction_Vectorcall+0x19c) [0x4da1cc]
python3(_PyObject_FastCallDict+0x25f) [0x4d04df]
python3() [0x4e44aa]
python3(_PyObject_MakeTpCall+0x34b) [0x4d0e0b]
python3(_PyEval_EvalFrameDefault+0x5605) [0x4cc5e5]
python3(_PyEval_EvalCodeWithName+0x1f5) [0x4c5e95]
python3(_PyFunction_Vectorcall+0x19c) [0x4da1cc]
python3(_PyEval_EvalFrameDefault+0x17bf) [0x4c879f]
python3(_PyFunction_Vectorcall+0x106) [0x4da136]
python3(_PyEval_EvalFrameDefault+0x907) [0x4c78e7]
python3(_PyEval_EvalCodeWithName+0x1f5) [0x4c5e95]
python3(PyEval_EvalCodeEx+0x39) [0x4c5c99]
python3(PyEval_EvalCode+0x1b) [0x5691ab]
python3() [0x588a71]
python3() [0x58268f]
python3() [0x58bf82]
python3(PyRun_SimpleFileExFlags+0x1a2) [0x58afa2]
python3(Py_RunMain+0x35c) [0x57ff1c]
python3(Py_BytesMain+0x39) [0x55ced9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fe4a286909b]
python3() [0x55cd8e]

Traceback (most recent call last):
  File "./tdnn/train.py", line 575, in <module>
    main()
  File "./tdnn/train.py", line 571, in main
    run(rank=0, world_size=1, args=args)
  File "./tdnn/train.py", line 497, in run
    graph_compiler = CtcTrainingGraphCompiler(lexicon=lexicon, device=device)
  File "/home/user/workspace/asr_space/next_gen_kaldi/icefall/icefall/graph_compiler.py", line 51, in __init__
    L_inv = lexicon.L_inv.to(device)
  File "/home/user/anaconda3/envs/env_k2/lib/python3.8/site-packages/k2-1.23.3.dev20230111+cpu.torch1.7.1-py3.8-linux-x86_64.egg/k2/fsa.py", line 1106, in to
    ans = Fsa(self.arcs.to(device), properties=self.properties)
RuntimeError: 
    Some bad things happened. Please read the above error messages and stack
    trace. If you are using Python, the following command may be helpful:

      gdb --args python /path/to/your/code.py

    (You can use `gdb` to debug the code. Please consider compiling
    a debug version of k2.).

    If you are unable to fix it, please open an issue at:

      https://github.com/k2-fsa/k2/issues/new
```

Here was how I installed pytorch before installing k2. My CUDA Version: 11.0
```
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=11.0 -c pytorch
```

May I know why it was not compiled with cuda support and how to fix it? Hopefully can still be done in a install-from-source manner. Thanks!

**Comment by treya-lin** [comment]
I think I figured out the reason. Let me try again.

**Comment by treya-lin** [comment]
Hi it seems there is some problem with my nvcc and my pytorch installation. I have fixed those, and restarting k2 compilation. It is compiling with cuda support now, but ran into other errors which I found a bit tricky. I post it in issues of k2 as it  is more relevant. https://github.com/k2-fsa/k2/issues/1143 Really appreciate it if you could take a look!
