### ISSUE TITLE
Encountered mutex error when preparing tedlium3 data.

### ISSUE THREAD

**Issue by by2101** [k2-fsa/icefall#853]
Hi,
I encountered multithread error when preparing tedlium3 data using icefall and lhotse.
The log is as follows:

2023-01-24 11:14:16 (prepare2.sh:53:main) Stage 0: Download data
2023-01-24 11:14:16 (prepare2.sh:73:main) Stage 1: Prepare tedlium3 manifests
2023-01-24 11:14:16 (prepare2.sh:84:main) Stage 3: Compute fbank for tedlium3
2023-01-24 11:14:23,363 INFO [compute_fbank_tedlium.py:79] Processing train
Extracting and storing features (chunks progress):   0%|                                                                                                                       | 0/15 [00:00<?, ?it/s]python3: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
python3: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Extracting and storing features (chunks progress):   0%|                                                                                                                       | 0/15 [01:32<?, ?it/s]
Traceback (most recent call last):
  File "./local/compute_fbank_tedlium.py", line 109, in <module>
    compute_fbank_tedlium()
  File "./local/compute_fbank_tedlium.py", line 91, in compute_fbank_tedlium
    cut_set = cut_set.compute_and_store_features(
  File "/opt/miniconda3/envs/k2/lib/python3.8/site-packages/lhotse/cut/set.py", line 1976, in compute_and_store_features
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/opt/miniconda3/envs/k2/lib/python3.8/site-packages/lhotse/manipulation.py", line 30, in combine
    return reduce(add, manifests)
  File "/opt/miniconda3/envs/k2/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/miniconda3/envs/k2/lib/python3.8/site-packages/lhotse/cut/set.py", line 1976, in <genexpr>
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/opt/miniconda3/envs/k2/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/opt/miniconda3/envs/k2/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/opt/miniconda3/envs/k2/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/opt/miniconda3/envs/k2/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/opt/miniconda3/envs/k2/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/opt/miniconda3/envs/k2/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

The versions of the tools:
torch                         1.10.2
torchaudio                    0.10.2
lhotse                        1.13.0.dev0+git.86eee9c.clean
The icefall is the latest version from github.

Thank you!

**Comment by csukuangfj** [comment]
@pzelasko 
Could you please have a look? I have never seen such an error before.

**Comment by pzelasko** [comment]
I also haven't seen it. You can probably decrease the number of parallel jobs (or just set it to 0) to work around it.

**Comment by by2101** [comment]
I re-installed a cpu version lhotse, and encountered another multi-thread problem. The error log is as follows:


2023-01-26 17:35:20,284 INFO [compute_fbank_tedlium.py:79] Processing train                                                                                                                           
Extracting and storing features (chunks progress):   0%|                                                                                                                       | 0/15 [00:00<?, ?it/s]
python3: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.                                                                                        
Extracting and storing features (chunks progress):   0%|                                                                                                                       | 0/15 [01:34<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                                    
  File "/home/baiye03/Speech/k2/icefall-master/egs/tedlium3/ASR/./local/compute_fbank_tedlium.py", line 109, in <module>                                                                              
    compute_fbank_tedlium()                                                   
  File "/home/baiye03/Speech/k2/icefall-master/egs/tedlium3/ASR/./local/compute_fbank_tedlium.py", line 91, in compute_fbank_tedlium
    cut_set = cut_set.compute_and_store_features(                                                                        
  File "/opt/miniconda3/envs/k2-cpu/lib/python3.9/site-packages/lhotse/cut/set.py", line 1976, in compute_and_store_features
    cuts_with_feats = combine(progress(f.result() for f in futures))                                             
  File "/opt/miniconda3/envs/k2-cpu/lib/python3.9/site-packages/lhotse/manipulation.py", line 30, in combine
    return reduce(add, manifests)                                                                                                                                                        
  File "/opt/miniconda3/envs/k2-cpu/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:                                  
  File "/opt/miniconda3/envs/k2-cpu/lib/python3.9/site-packages/lhotse/cut/set.py", line 1976, in <genexpr>          
    cuts_with_feats = combine(progress(f.result() for f in futures))            
  File "/opt/miniconda3/envs/k2-cpu/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()                                                                                                       
  File "/opt/miniconda3/envs/k2-cpu/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception                                                                                                                              
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

And when I set num_jobs to 1, the program ran well.
