### ISSUE TITLE
Error "File name too long" when decoding with fast_beam_search_nbest_LG in pruned_transducer_stateless7_streaming

### ISSUE THREAD

**Issue by pehonnet** [k2-fsa/icefall#935]
Command:
```bash
for m in fast_beam_search_nbest_LG; do   for epoch in 30; do     for avg in 12; do       ./pruned_transducer_stateless7_streaming/decode.py         --epoch $epoch         --avg $avg         --decode-chunk-len 32         --exp-dir pruned_transducer_stateless7_streaming/exp         --max-duration 600         --decoding-method $m;     done;   done; done
```

Error:
```bash
...
2023-03-08 09:33:26,293 INFO [decode.py:560] batch 40/?, cuts processed until now is 2561
Traceback (most recent call last):
  File "./pruned_transducer_stateless7_streaming/decode.py", line 817, in <module>
    main()
  File "/home/pe.honnet/Tools/miniconda3/envs/icefall/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./pruned_transducer_stateless7_streaming/decode.py", line 807, in main
    save_results(
  File "./pruned_transducer_stateless7_streaming/decode.py", line 575, in save_results
    store_transcripts(filename=recog_path, texts=results)
  File "/home/pe.honnet/Projects/icefall/icefall/utils.py", line 431, in store_transcripts
    with open(filename, "w") as f:
OSError: [Errno 36] File name too long: 'pruned_transducer_stateless7_streaming/exp/fast_beam_search_nbest_LG/recogs-test-clean-beam_20.0_max_contexts_8_max_states_64_num_paths_200_nbest_scale_0.5_ngram_lm_scale_0.01-epoch-30-avg-12-streaming-chunk-size-32-beam-20.0-max-contexts-8-max-states-64-nbest-scale-0.5-num-paths-200-ngram-lm-scale-0.01-use-averaged-model.txt'
```

**Comment by pehonnet** [comment]
Yes, I did that to make it work in my case, but in the general case the only way would be to drop some of the params in the filenames. It probably occurs only very rarely.

**Comment by csukuangfj** [comment]
> recogs-test-clean-beam_20.0_max_contexts_8_max_states_64_num_paths_200_nbest_scale_0.5_ngram_lm_scale_0.01-epoch-30-avg-12-streaming-chunk-size-32-beam-20.0-max-contexts-8-max-states-64-nbest-scale-0.5-num-paths-200-ngram-lm-scale-0.01-use-averaged-model.txt'

Looks like `beam-20.0-max-contexts-8-max-states-64-nbest-scale-0.5-num-paths-200-ngram-lm-scale-0.01-` appears twice in the filename.

Could you create a PR to fix it?

**Comment by pehonnet** [comment]
mmh actually it is not twice exactly the same, although very similar:
```
beam_20.0_max_contexts_8_max_states_64_num_paths_200_nbest_scale_0.5_ngram_lm_scale_0.01
beam-20.0-max-contexts-8-max-states-64-nbest-scale-0.5-num-paths-200-ngram-lm-scale-0.01
```
the first one comes from `key` and the second one from `params.suffix`. I guess it would mean changing things in one or the other.
```
I think if I just remove `key` it should be ok, as everything seems to be in `params.suffix` (and it contains a few more things).
See https://github.com/k2-fsa/icefall/pull/936
