### ISSUE TITLE
Error during filter bank calculation

### ISSUE THREAD

**Issue by AlexandderGorodetski** [k2-fsa/icefall#964]
Hello,

I am using tedlium recipe to train model from my inhouse data (5,0000 hours). I got following error during filter bank extraction. Could you help please.

Extracting and storing features (chunks progress):   0%|          | 0/15 [3:22:34<?, ?it/s]
Traceback (most recent call last):
  File "local/compute_fbank_tedlium.py", line 110, in <module>
    compute_fbank_tedlium()
  File "local/compute_fbank_tedlium.py", line 98, in compute_fbank_tedlium
    storage_type=LilcomChunkyWriter,
  File "/opt/conda/lib/python3.7/site-packages/lhotse/cut/set.py", line 1976, in compute_and_store_features
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/opt/conda/lib/python3.7/site-packages/lhotse/manipulation.py", line 30, in combine
    return reduce(add, manifests)
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.7/site-packages/lhotse/cut/set.py", line 1976, in <genexpr>
    cuts_with_feats = combine(progress(f.result() for f in futures))
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by pzelasko** [comment]
Is it possible you ran out of CPU memory? You can try a smaller number of workers.

**Comment by AlexandderGorodetski** [comment]
Guys, I found myself using only 5 workers. I suspect that the issue lies with lhotse's method of loading full waves into memory. Would it be feasible to modify lhotse to read wav files using smaller blocks, similar to older methods?

**Comment by csukuangfj** [comment]
> we might need a method that simulates online feature extraction for very long recordings

By the way, `kaldifeat` also supports streaming/online feature extraction.

please have a look at
- https://github.com/csukuangfj/kaldifeat/blob/bf2047023fd7c551c94673b8ead61a929e1243df/kaldifeat/python/tests/test_fbank.py#L16-L56

and

https://github.com/csukuangfj/kaldifeat/blob/bf2047023fd7c551c94673b8ead61a929e1243df/kaldifeat/python/kaldifeat/fbank.py#L16-L23

Note that it does not support batch processing for the online/streaming case.
